zinc-collective/convene

.gitignore, clients/zinc.tfvars, features/infrastructure/hosting-jitsi.feature, jitsi/install-letsencrypt-cert.sh, jitsi/provision, zinc.tf
There's a bunch of rough edges here, and it _only_ works for
meet.zinc.coop atm; but it should be possible to start parameterizing
pieces and figuring out how to organize it to support multiple
instances.
See https://github.com/zinc-collective/convene/issues/2
=> Operator may provision a a Jitsi instance programmatically

features/infrastructure/hosting-jitsi.feature, jitsi/build, jitsi/provision
To keep deploy time down for on-demand JITSI hosting, we want per-region
pre-built virtual machine images on a per-client basis. This makes it so
we can start an instance super-quick-like without having to do the full
jitsi installation process.
=> Add a scenario for building a Jitsi AMI for a client

README.md
Pursuant to https://github.com/zinc-collective/convene/issues/10#issue-614888597 the Readme has been updated with a link to the Customer Development Folder on G Drive.
=> Updated with link to Cust Dev G Docs Folder

infrastructure/features/video-workspaces.feature
Hosting Jitsi isn't the important part, it's an incidental detail.
This reframes to Video Workspaces, which gives us more space to play.
=> Reframing to center the feature of Video WorkSpaces

.env.example, .gitignore, bin/configure-pricing
See: https://github.com/zinc-collective/convene/issues/8
I was using this primarily to explore what it would look like to build
Product and Pricing setup into Compensated/Support, while also ensuring
we have a papertrail for setting up pricing for Convene.
=> Automate creation of the Convene pricing tier

infrastructure/clients/meet.zinc.coop/public.tfvars, infrastructure/clients/meet.zinc.coop/secrets-example.tfvars, infrastructure/jitsi/install
See: https://github.com/zinc-collective/convene/issues/23
=> Replace the meet.zinc.coop AMI with the latest JITSI build

infrastructure/features/video-workspaces.feature, infrastructure/features/workspace-reliability.feature
See: https://github.com/zinc-collective/convene/issues/17
I noticed that this particular feature was not documented with the
source code during confirmation of issue #17; despite it being a
relatively critical piece of our reliability strategy.
=> Communicate the intent for nightly restarts in our feature specs

infrastructure/clients/meet.zinc.coop/infrastructure.tf, infrastructure/clients/meet.zinc.coop/public.tfvars
Now whenever we do a build for meet.zinc.coop, a provision will use the
updated AMI without requiring us to update the variables.
=> Releasing meet.zinc.coop no longer requires code changes

infrastructure/clients/meet.zinc.coop/infrastructure.tf, infrastructure/clients/meet.zinc.coop/public.tfvars, infrastructure/clients/meet.zinc.coop/secrets-example.tfvars, infrastructure/features/video-workspaces.feature
#29 
Already built a Vultr snapshot for meet.zinc.coop
I believe @zspencer can run the following to destroy the Zinc Coop Convene instance on AWS and provision a Vultr instance after setting the additional `public_key` & `vultr_api_key` and run
```bash
jitsi/provision --client-domain=meet.zinc.coop --flush-dns-cache --ssh-username=zee
```
=> Migrate meet.zinc.coop to Vultr

convene-web/app/javascript/controllers/room_picker_controller.js, convene-web/app/views/lobbies/show.html.erb
Ref: https://github.com/jitsi/jitsi-meet/blob/7bfb2fc21907b2de499b3bed6fe5a4149fecad65/config.js#L489-L491
=> Expand view height to entire screen and allow mobile Jitsi video

convene-web/config/environments/production.rb
Already setup `https://convene.zinc.coop/` but forgot to enforce ssl.
=> Convene-web enforce ssl in production

features/discovering-rooms.feature, package.json
Connects: #39 
Checking this in while working on discovering rooms feature so we don't forget.
=> Checkin pending Discovering Rooms features spec

convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/app/controllers/application_controller.rb, convene-web/app/models/room.rb, convene-web/app/views/workspaces/show.html.erb, convene-web/spec/models/room_spec.rb, features/discovering-rooms.feature, package.json
Part of https://github.com/zinc-collective/convene/issues/39
Hold off from implementing `accessable_by` because we now treat every guest as members
=> Member only see listed rooms

convene-web/db/seeds.rb
I wound up having duplicated workspaces because the name and slug was
not unique after running the seeds multiple times.  Now running
`db:seed` should not create the same workspace or room on additional
runs, and it should also raise exceptions if it cannot perform an update
or create operation.
=> Seeds are idempotent and fail with an exception

infrastructure/clients/meet.zinc.coop/infrastructure.tf
I noticed that we had set some cloudflare records for convene that were not being managed.
I'm not 100% sure that this is _quite_ how I want to do this; for instance it's not a _client_ that we are setting the DNS for right now; but I'm not sure it's too important.
=> Automate creating DNS entries for Convene-Web on Heroku

convene-web/app/models/demo_workspace.rb
I had went through the trouble of creating a `client_repository` and
then went ahead and referenced `Workspace` and `Client`. This makes the
`Factory` class work with any class that's shaped like an
ActiveRecord::Relation with a structure that mirrors our database
schema.
=> Tidy the DemoWorkspace class up a bit

convene-web/app/views/rooms/show.html.erb
Fix this:
Because the JS was try to GET `https://meet.zinc.coop/Vivek's%20Desk` and it errors out.
=> Fix bug where invalid room name in pass onto Jitsi

features/discovering-rooms.feature, features/entering-rooms.feature
See: https://github.com/zinc-collective/convene/issues/59
I've added the `@built` tag to indicate which features have been
_built_, so that it's a bit easier for someone who wants to start doing
some test automation to figure out what feature files need more work.
=> Document how Entering Rooms works

convene-web/app/controllers/rooms_controller.rb, convene-web/app/models/room.rb
Part of https://github.com/zinc-collective/convene/issues/72
Member can enter unlisted room if they know the url.
@zspencer This should fulfill `Room Creators can discover their own unlisted rooms` if we assume room creator has ownership on the room, let me know what you think.
Thinking about implementation for `Room Previous Attendees can discover previously visited unlisted rooms`:
1. Introduce `AccessRecord` model (or some other better name), upon member visiting a room, create an `AccessRecord` linked to the room and member.
2. `accessable_by` will check on room ownership, listed and presence of `AccessRecord`.
With `AccessRecord`, we might be able to introduce a history of room access record in the future.
=> Non room creator can enter unlisted room if they know the url

convene-web/app/controllers/application_controller.rb, convene-web/app/views/layouts/application.html.erb, convene-web/app/views/rooms/show.html.erb, convene-web/app/views/workspaces/_room_card.html.erb
Before this pull request, switching room doesn't work smoothly, when users click another room when in different room, the http request to a new room got cancelled. 
I am not 100% sure why disabling turbolink doesn't work but then I know moving the jitsi external_api.js to head and re-enabling turbolink works.
I think it's a sign I need to start implementing system test.
=> Fix switch room doesn't work

infrastructure/videobridge/install
While Jisti iframe Api `interfaceConfigOverride` mentioned APP_NAME,
APP_NAME doesn't have effect.
Jitsi team disabled APP_NAME due to users not respecting fair use instructions.
Convene is deploying its own instance of Jitsi so it's fair for us to
replace with Convene branding.
Ref: https://community.jitsi.org/t/app-name-doesnt-have-effect/71648/2
We might be able to dig into jitsi-meet React codebase to re-enable APP_NAME
but that would require us to build jitsi-meet frontend code upon deploy instead of
getting packages via apt-get.
If we ever have feature request for dynamic branding of Convene/ Jitsi, we could look into
that in the future.
If we want to have dynamic branding, I think we just need to edit [this file](https://github.com/jitsi/jitsi-meet/pull/7025/files) and built our …
=> Replace Jitsi Meet branding to Convene

app.json, convene-web/app/models/feature.rb, convene-web/app/models/system_test_workspace.rb, convene-web/db/seeds.rb
Setup review app for smoke test purposes.
Eventually we would want to setup review app for system test purposes but that would require us to automatically setup convene-pr-xxx.zinc.coop per review app.
=> Setup Heroku review app

features/discovering-rooms.feature, features/page-objects/WorkspacePage.js, features/steps/room_steps.js, package-lock.json, package.json
See: https://github.com/zinc-collective/convene/issues/72
See: https://github.com/zinc-collective/convene/issues/39
- You can bypass waiting for a room card to exist by passing `false` to
the findRoomCard method on workspace
We think that it would be nice to make the `findRoomCard` function to
return the roomCard itself, or return a false; and move the wait out of
it completely; which would push responsibility for knowing whether we
should "wait for it" to the step.
This would also allow us to "check" the value of the roomCard in steps.
- We use `cucumber-pretty` to format our output legibly
Co-authored-by: Tom Lee <user512@users.noreply.github.com>
Co-authored-by: CJ Joulain <joulain@gmail.com>
Co-authored-by: KellyAH <KellyAH@users.noreply.github.com>
=> Wire in scenarios for guests not discovering unlisted rooms

convene-web/bin/run
I sometimes do my development on a remote VM, so my browser's
`localhost` is not the same as the development machine's `localhost`
I probably should figure out a way to use nginx or haproxy or something
to sit in between the requests instead of making this change; but that
seems non-trivial and I was hoping to make some progress :(.
=> 🛠 Developers may override the interface convene-web listens on

convene-web/.gitignore, convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/package.json, convene-web/yarn.lock
Not sure how they started drifting, but we had webpacker 4 in our
Gemfile and webpacker 5 in our package.json; which would make running
`bin/rails webpack:install` cause unnecessary churn.
=> 🛠 Align the webpack versions

convene-web/.env.example, convene-web/README.md, docker-compose.yml
For folks that already have docker set up, it saves a bit of effort to
use docker-compose to manage a postgresql database just for Convene.
=> 🛠 Add a docker-compose file to streamline dev setup

features/locking-rooms.feature, features/parameter-types/rooms.js, features/steps/room_steps.js
Paired with @cjoulain to flesh out the Feature definitions for Locking Rooms.
First, we noticed that there were a lot of scenarios that maybe didn't need to exist; and we collapsed them into a single scenario that lays out which people have which access rights.
Then, we noticed that there were some missing scenarios, like locking and unlocking the room. So we put those in as well.
Finally, we began to wire those scenarios into parameterTypes and step definitions so we can write user-level integration tests.
(P.s, I'm going to let @cjoulain merge after approval, so they get the `Co-Authored By` credit)
=> Begin to wire in feature test for Locking Rooms

app.json
Review app build failed because of missing `ADMIN_USERNAME` & `ADMIN_PASSWORD`
=> Fix review app build by requiring admin username and password

convene-web/app/javascript/src/video_room.js
Connects #115 
* Previously the `videoConferenceLeft` event will get triggered when user reload.
Use `readyToClose` event instead because it only got triggered when user intended to hangup.
=> Stay in video room when user refresh

features/locking-rooms.feature, features/steps/room_steps.js
* We want to keep the features defintions untouched, it was intentionally grouped this way.
=> Revert locking rooms features definitions

README.md
The readme doesn't clearly state that the convene app is a video conference app. The doc is getting rather long and you have to scroll through a lot of text to get to the info you want.
**Docs**
- Added Table of Contents (TOC) for easier navigation.
- Added summary sentence because it is currently not easily communicated what the Convene is.
E.g. 
```
- About Convene
- [add summary what the app is]
- [insert Objectives and Purpose - all the pretty marketing text]
- Contributing
- [insert info for any devs wanting to work on the app, link to Convene::Web/README.md]
- [insert Help and Support section]
- [insert "Convene is Community Owned...." sentence]
- [insert The Circle of Stewards section]
- Architecture
- [insert Budget section]
- Design
- Using Convene
- About the Zinc Collective
``` …
=> added table of contents and summary sentence

convene-web/README.md, convene-web/bin/setup
I propose adding `bin/rake db:seed` to the steps in `bin/setup`, because it seems needed for the System Test and other test/demo workspaces to be created.
I'm not sure if there is a downside to having this step always in `bin/setup`, but at first glance `seeds.rb` seems idempotent. An alternative would be to simply add a step in the README for the developer to separately run `bin/rake db:seed`.
I also attempted to clarify a couple of things in the README that I found unclear.
=> Add running db:seed to bin/setup, and clarify a couple of bits in the README that confused me

features/identification.feature
See: https://github.com/zinc-collective/convene/issues/118
There's a few things here, first we're focusing _purely_ on email based
authentication for now. I can imagine wanting to leverage something like
OpenId, OAuth, or IndieAuth for allowing someone to establish their
identity within Convene.
=> Sketch out feature definition for Identification

convene-web/app/models/room.rb, convene-web/app/views/workspaces/_room_card.html.erb, features/locking-rooms.feature, features/page-objects/WorkspacePage.js, features/parameter-types/rooms.js, features/parameter-types/workspaces.js, features/steps/room_steps.js
=> Wire in steps for entering a locked room

convene-web/yarn.lock
Dependentbot can't fix it so I fix it manually.
Ref: https://medium.com/@ayushya/upgrading-javascript-packages-deep-dependencies-using-yarn-8b5983d5fb6b
=> Upgrade node-forge to fix CVE-2020-7720

convene-web/app/javascript/packs/application.js, convene-web/app/javascript/src/application.scss, convene-web/app/javascript/src/custom_components/button.scss, convene-web/app/javascript/src/custom_components/form.scss, convene-web/app/javascript/src/custom_components/header.scss, convene-web/app/javascript/src/custom_components/icons.scss, convene-web/app/javascript/src/custom_components/room_card.scss, convene-web/app/javascript/src/tailwind.scss, convene-web/bin/run
74f53ef  provide live reload and compile frontend asset on JS / SCSS file change instead of waiting for a new request in development mode.
fbb02df optimize webpack recompile so recompile time is down to around 1 second.
Before fbb02df, making changes in any scss file that uses `@apply`
```
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Hash: afed0a07af075545d568
Version: webpack 4.44.1
Time: 9598ms
```
After fbb02df
```
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Hash: ead83387e0a910303855
Version: webpack 4.44.1
Time: 751ms
```
Please note that initial compile will still be slow but it'll be fine because developer only run `bin/run` once.
=> Live Reloading Frontend Asset in Development & Optimize Webpack Recompile

.github/workflows/test-convene-web.yml
* This GH actions allow us to automatically respect .ruby-version
* The GH actions community favor ruby/setup-ruby (Ref: https://github.com/actions/setup-ruby/issues/80)
* I can't set specific minor version in actions/setup-ruby and this new action allow me to do so
=> Use ruby/setup-ruby Github actions

features/support/env.js
Most of the time we need non headless mode during feature test development locally but headless mode on CI.
=> Run feature test in headless mode on CI and non headless mode during development

convene-web/app/javascript/controllers/room_edit_form_controller.js, convene-web/app/javascript/src/custom_components/form.scss, convene-web/app/views/rooms/edit.html.erb
Disabled access code input when actor intended to unlock the room.
=> Disable access code input when intended to unlock room

convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/app/controllers/application_controller.rb, convene-web/app/controllers/workspaces_controller.rb, convene-web/app/models/person.rb, convene-web/app/views/layouts/_header.html.erb, convene-web/config/locales/en.yml, convene-web/config/routes.rb, convene-web/db/migrate/20201112224155_create_passwordless_sessions.passwordless.rb, convene-web/db/migrate/20201112224355_add_uniq_idx_to_person_email.rb, convene-web/db/migrate/20201112231331_support_uuid_in_passwordless_sessions.rb, convene-web/db/schema.rb, features/identification.feature
Setup passwordless login but we are not using it for now.
People are created when identification happens if we don't already have a person matching the email.
* We allow people to be created when identification happens because we might allow guest to enter room and provide id information.
* Route for the signing form: `/people/sign_in`
=> Setup Passwordless Login

features/locked-rooms.feature, features/page-objects/RoomSettingPage.js, features/page-objects/WorkspacePage.js, features/page-objects/page-elements/RoomCard.js, features/parameter-types/rooms.js, features/steps/room_steps.js
See: https://github.com/zinc-collective/convene/issues/40
The changes here are intended to make it so our feature files and step definitions don't have to care as much about hardcoded values; thus making them easier to:
- Recompose into new story tests and...
- Parallelize the feature tests 
There's likely some more work to be done here; but this feels like a decent, safe step?
=> Improve composability of story tests and step definitions

convene-web/README.md
Looking for comments on language and placement. 
Currently I only added it to the convene-web README as it seems to be contributor facing more than explicitly for the public. 
I can easily add to the overall Convene README if desired or change the language as well.
I have also just sent the legal statement to operations so there shouldn't be any blockers on merging on that front.
=> Add link to updated personas document to convene-web README.

convene-web/app/controllers/application_controller.rb, convene-web/app/controllers/rooms_controller.rb, features/navigate-between-convene-and-other-systems.feature
See: https://github.com/zinc-collective/convene/issues/160
This builds on @hangtwenty's initial shift; while putting the responsibility into the existing helpers for page-titles; which should allow us to more clearly sign-post which Space & Room a particular Tab is. 
It also drops the Feature into the code-base; so that it's more clear that navigation between external-systems and Convene is something we care about; and may want to more refine with additional intentions.
=> Signpost the current page as a Convene Space more clearly

README.md, convene-web/README.md
Replace personas link to main README and tighten language in convene-web README around persona link.
Addresses feedback from #166
=> Clean-up from previous README update for adding Persona's link

convene-web/app/javascript/controllers/menu_controller.js, convene-web/app/javascript/src/custom_components/header.scss, convene-web/app/javascript/src/custom_components/icons.scss, convene-web/app/javascript/src/page_bem_class.scss, convene-web/app/models/guest.rb, convene-web/app/models/person.rb, convene-web/app/views/layouts/_header.html.erb, convene-web/app/views/workspaces/_room_card.html.erb, convene-web/public/avatar.svg
Connects: https://github.com/zinc-collective/convene/issues/118
Follow up on https://github.com/zinc-collective/convene/pull/163
Refactor navbar to semantic html and replace screenshot avatar image to svg provided by @colombene.
=> Refactor navbar to semantic html

convene-web/app/controllers/admin/base_controller.rb, convene-web/app/controllers/admin/clients_controller.rb, convene-web/app/controllers/admin/people_controller.rb, convene-web/app/controllers/admin/room_ownerships_controller.rb, convene-web/app/controllers/admin/rooms_controller.rb, convene-web/app/controllers/admin/workspace_memberships_controller.rb, convene-web/app/controllers/admin/workspaces_controller.rb, convene-web/config/environments/test.rb
I tried a few things to avoid eager loading:
1. Switch to classic loader instead of the default Rails 6 [Zeitwerk](https://github.com/fxn/zeitwerk#file-structure)
* It works but classic loader will be deprecated eventually, not recommended.
2. Rename `Admin::ApplicationController` to `Admin::BaseController`
* I wasn't 100% why it works but my guess is [Zeitwerk only made one autoload look up](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#less-file-lookups) and
the first one it found was `Admin::ApplicationController`, and raise the superclass mismatch error.
* There might be a way to config Zeitwerk to do a smarter look up but I think renaming
`Admin::ApplicationController` to `Admin::BaseController` makes sense, and we can treat
`ApplicationController` as a …
=> Avoid eager loading in test

convene-web/app/javascript/src/application.scss, convene-web/app/javascript/src/custom_components/button.scss, convene-web/app/javascript/src/custom_components/form.scss, convene-web/app/views/passwordless/sessions/create.html.erb, convene-web/app/views/passwordless/sessions/new.html.erb, convene-web/config/locales/en.yml
* When implementing the ok button, we were wondering the intent of the button
because we can't redirect people to their own email client,
skipping ok button in the implementation for now.
* UI Mockup:
https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/b1223ba7-c6bf-4e8e-94ee-0ef583a178cb/
https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/456d873b-accd-4f06-89a0-a1dfeadee38c/
Co-authored-by: Whitney <roseaboveit@users.noreply.github.com>
Co-authored-by: Zee <zspencer@users.noreply.github.com>
=> Styled login form and modified login new & create template wording

convene-web/Gemfile, convene-web/Gemfile.lock
Closes: https://github.com/zinc-collective/convene/issues/182
Ref: https://github.com/puma/puma/issues/2342
=> Avoid puma 4.3.5 that avoids bundle install

convene-web/app/lib/furniture.rb, convene-web/app/lib/furniture/base_controller.rb, convene-web/app/lib/furniture/breakout_tables.rb, convene-web/app/lib/furniture/videobridge_jitsi.rb, convene-web/app/models/blueprint.rb, convene-web/app/models/demo_space.rb, convene-web/app/models/furniture_placement.rb, convene-web/app/models/system_test_space.rb, convene-web/app/views/furniture/breakout_tables/_in_room.html.erb, convene-web/app/views/furniture/videobridge_jitsi/_in_room.html.erb, convene-web/app/views/rooms/show.html.erb, convene-web/config/routes.rb, convene-web/db/seeds.rb, convene-web/lib/tasks/release.rake, convene-web/spec/models/furniture_placement_spec.rb
See https://github.com/zinc-collective/convene/issues/186
In order to support more diverse use cases, I'm trying to move the Videobridge into a piece of Furniture that can be placed in a Room. The intent here is to allow us to have Rooms that _don't_ use a VideoBridge, such as for the Fundraising ACH Tool
Can Haz Review on:
1. [x] Running `bin/setup` completes successfully?
2. [x] Running `convene-web/bin rake release:after_build` makes sure all the rooms on your machine have a videobridge?
3. [x] Sanity check?
=> Refactor Jitsi videobridge as Furniture

convene-web/Procfile
There is probably a smarter way to do this, but what I think is
happening is because `db:prepare` is being called in the same process
that is doing the loading of the data, the models haven't had their
underlying mapping to the database tables "refreshed" which is causing
the builds to fail.
=> Fix review apps

convene-web/config/application.rb, features/identification.feature
Connects: https://github.com/zinc-collective/convene/issues/118
We haven't figured out how to expire a session due to inactivity,
so we just expire the session after seven days regardless.
=> Expire sessions after seven days

convene-web/config/initializers/action_mailer.rb
This logic was accidentally inverted: we want to set the port explicitly when we are _not_ running on the default port.
(Extracting this fix from https://github.com/zinc-collective/convene/pull/199, so that we can have it merged in sooner.)
=> Fix initializer logic for setting the ActionMailer port

.github/workflows/test-convene-web.yml, convene-web/.ruby-version
Address https://github.com/zinc-collective/convene/issues/209 by caching bundled gems and installed node_modules in the CI environment.
Zippy builds are here:
=> Cache setup / installation steps when running in the CI environment

convene-web/config/environments/development.rb
For some reason, after switching to Hivemind, I no longer see the server logs.
This pull request fixes it.
=> Expose server logs in development

convene-web/config/initializers/passwordless.rb
This PR addresses some of the issues we uncovered when doing manual testing for https://github.com/zinc-collective/convene/issues/118:
* add a better "from" address for magic link emails
* set an explicit token timeout setting
* set explicit sign in, sign out, and failure redirect paths
* add an explicit setting for redirecting "back" after sign in (where possible)
=> Better configure Passwordless, add an initializer

.github/workflows/test-convene-web.yml
Before Hivemind, we curl system-test.zinc.local to trigger asset built before running `bin/test`.
Now with Hivemind, we have dedicated asset process to run `webpack-dev-server` so we need to check if the `manifest.json` is ready.
=> Wait for assets before running bin/run

convene-web/app/mailers/magic_link_mailer.rb, convene-web/app/views/magic_link_mailer/magic_link.text.erb, convene-web/config/initializers/passwordless.rb
This PR attempts to resolve an issue we found when testing https://github.com/zinc-collective/convene/issues/118, where a magic link URl was directing the user to the incorrect subdomain.
Another option might have been monkeypatching Passwordless, but to me this feels a little less brittle, more explicit, and hopefully easier to further extend in the future.
=> Use tweaked custom mailer to email magic links that point the user to the domain they were using

convene-web/app/views/spaces/show.html.erb, features/spaces.feature
Connects: https://github.com/zinc-collective/convene/issues/233
I didn't write test for this because:
1. This is breaking all `SpaceController#show` page so it's better to fix it sooner than later. I manually test it locally with a space with no entrance.
2. I want to get some advice/ directions on how to generate seed for different space configuration for feature test and implement in another pull request.
=> Gracefully handle error when space has no entrance

convene-web/spec/spec_helper.rb
It's OK for a test to have multiple asserts; especially given how
expensive most of the test setup/teardown is in rails.
=> Aggregate failures in rspec by default

bin/setup
Turns out, some dev machines do not yet have the mime info installed; and it's a system-level dependency
So we added it in our `bin/setup` script.
=> Eliminate error when running `bin/setup` on a Mac without shared-mime-info installed

convene-web/app/controllers/furniture_placements_controller.rb, convene-web/spec/factories/furniture_placement.rb, convene-web/spec/requests/spaces/room/furniture_placements_spec.rb, convene-web/spec/requests/waiting_rooms_request_spec.rb
To prevent non-space-members from messing with a Space's furniture.
=> Authorize updates to Furniture Placements in controller

CONTRIBUTING.md, bin/setup
This ensures local dev environment has firefox needed to run bin/tests
script.
=> moved install firefox to setup script

convene-web/app/javascript/src/base/layout.scss, convene-web/app/javascript/src/base/typography.scss, convene-web/app/javascript/src/components.scss, convene-web/app/javascript/src/components/branding.scss, convene-web/app/javascript/src/components/footer.scss, convene-web/app/javascript/src/components/header.scss, convene-web/app/javascript/src/components/room_card.scss, convene-web/app/models/guest.rb, convene-web/app/models/person.rb, convene-web/app/views/layouts/_header.html.erb, convene-web/app/views/layouts/application.html.erb, convene-web/app/views/waiting_rooms/show.html.erb, convene-web/config/breadcrumbs.rb, features/harness/PersonNavigationComponent.js
- Moves Convene to a Footer
- Adds Breadcrumbs to the Header and Footer
- Gets rid of Avatars since we don't have it yet
- Gets rid of the tap to Sign out / Sign In
=> Restructure Header and Footer to prioritize the Space

convene-web/app/javascript/src/components/icons.scss, convene-web/app/views/spaces/_room_card.html.erb
Small visual tweak, so that we no longer have a phone icon for rooms, since rooms might or might not have "call" capabilities.
Looks like this:
=> Replace phone icon with "open door" icon for the "Enter Room" button.

convene-web/.nvmrc
When working with CJ, we noticed that their environment was haivng some
weird issues. Turns out, the .nvmrc file in the convene-web directory
was not a valid symbolic link; which may have been throwing their
node-version manager for a loop.
Symbolic Links: https://www.lifewire.com/create-symbolic-links-ln-command-4059723
=> Fix broken symbolic link for nvmrc

bin/setup, convene-web/bin/setup
This PR tweaks a couple of things I noticed re-setting this repo from scratch:
* make our string handling in bash resilient to the cases where `$brew_output` or `$command_output` might contain spaces
* fix the check for existence of `$brew_output` to check for an empty string (I believe this check was previously logically inverted)
* make `convene-web/bin/setup` make a copy of `.env.example` if there isn't an existing `.env`
=> Small improvements to bin/setup

convene-web/app/javascript/src/components.scss, convene-web/app/javascript/src/components/breadcrumbs.scss, convene-web/app/javascript/src/components/icons.scss, convene-web/app/views/application/_breadcrumbs.html.erb, convene-web/app/views/layouts/_header.html.erb, convene-web/app/views/layouts/application.html.erb, convene-web/app/views/spaces/_room_card.html.erb, convene-web/app/views/spaces/edit.html.erb, convene-web/config/breadcrumbs.rb, convene-web/config/routes.rb, features/harness/Component.js, features/harness/Page.js, features/harness/RoomCardComponent.js, features/harness/RoomEditPage.js, features/harness/SpaceEditPage.js, features/lib/AccessLevel.js, features/steps/room_steps.js
Coops not cages wanted to update their content, but because they have an Unlisted Room as their Entrance Hall, there isn't any way for them to find the configure button!
We:
- Switched to a "Gear" for configure, which seems more in line with visual conventions
- Got our ass kicked by the CSS trying to get rid of the icon underline (But we did it!)
- Added a list of Rooms with links to Configure them on the Space Configuration page.
=> Streamline Space and Room configuration

.github/workflows/test-convene-web.yml, bin/setup
To speed up each run:
* cache the Homebrew cache between CI runs
* stop installing `shared-mime-info`, since we  no longer need it
=> Cache brew caches between CI runs

convene-web/config/initializers/action_mailer.rb
This change adds a `Rails.application.reloader.to_prepare do` around an initializer call to `ActionMailer::Base`. This removes the deprecation warning:
```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.
```
`Rails.application.reloader.to_prepare` is meant explicitly for autoloading during application boot, with the caveat that the contents of the block must be idempotent (which this code is) since it might be called twice. Rails docs: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots
We still have a handful of errors `warning: already initialized constant` on startup, but that seems more innocuous and also harder to fix.
=> Remove deprecation warnings related to autoloading

features/space-membership.feature, features/support/parameter-types/actors.js
I thought I had gotten all the "Space Admin" references from our Feature/Docs but alas, I had not. THis Also elaborates on the "Neighbor" actor, providing an affordance for test definitions between Space Member and Guest for navigating scenarios where that is a significant difference.
=> Finish transformation to Space Owner from Space Admin

convene-web/app/views/layouts/application.html.erb
Just a minimal change to make it possible for folks stumbling across a Convene space to know who is running this and maybe how to reach us.
=> Link "Convene" name in footer to Convene's landing page

.solargraph.yml
For those of us who use Solargraph for type-hinting, method definition / documentation previews and similar delightful features; you'll notice that Rails classes are often ... missing.
This should make that a little more consistent!
See:
- https://solargraph.org/guides/rails
- https://github.com/castwide/solargraph/issues/87
- https://github.com/iftheshoefritz/solargraph-rails
=> Add Rails support to Solargraph

convene-web/app/models/blueprint.rb, convene-web/app/models/utility_hookup.rb, convene-web/spec/models/blueprint_spec.rb, convene-web/spec/models/utility_hookup_spec.rb
When running `bin/setup`, we re-apply the blueprint for the System Test space.
Thich was clobbering the Furniture Placements and Utility Hookups and other such changes.
Now it should not clobber changes made on the local system.
=> Make Blueprint more Idempotent

convene-web/app/views/guides/_identification.md, features/harness/SignInPage.js, features/identification.feature, features/lib/Actor.js, features/steps/identification_steps.js
See: https://github.com/zinc-collective/convene/issues/159
This also un-pends the feature tests, and updates the test harness to
expose affordances for signing in via one-time-code.
=> Update authentication guide to include one time code

.editorconfig, .gitignore
.editorconfig lets us do fancy pants stuff like ensure everyone uses
two spaces; instead of tabs. The `tmp` folder is mostly so we have a
place we can put stuff.
=> Add an `.editorconfig` and `tmp`

.github/workflows/test-convene-web.yml
We keep having CI failures that appear to be caused by the application server not having actually started up. This should hit the server before hand to make sure rails finishes loading everything.
=> Warm the app server before running feature tests

features/harness/SignInPage.js, features/lib/Actor.js, features/steps/room_steps.js, features/steps/space_steps.js, features/steps/utility_hookup_steps.js, features/support/parameter-types/accessCode.js, features/support/parameter-types/accessLevel.js, features/support/parameter-types/actor.js, features/support/parameter-types/articleAdjective.js, features/support/parameter-types/publicityLevel.js, features/support/parameter-types/room.js, features/support/parameter-types/space.js
Previously, we were including article ajdectives in our paramater type
matches. This was convenient, because we could write Gherkin where "an"
or "the" or "a" was interchangable, hooray!
However, it was also a bit of a pain because each parameter type wound
up wanting these article adjectives, which meant more complex regexes.
And the more complex regex's meant translating between Gherkin and step
definition became more difficult as well.
This introduces an `a` paramater type; so that steps can Gherkin can be
written with either `a` or `an` or `the` and still get matched to the
appropriate step definition; but without requiring each parameter type
to include it.
Co-authored-by: CJ Joulain <cjoulain@users.noreply.github.com>
=> Simplify authoring of Parameter Types

app/models/blueprint.rb, app/models/space.rb, app/models/system_test_space.rb, db/migrate/20211106220854_remove_space_access_level_code.rb, db/migrate/20211106222232_remove_access_code_from_memberships.rb, db/schema.rb, spec/models/demo_space_spec.rb
To simplify and clarify things a bit.
=> Remove unused access_level and access_code from Space and SpaceMembership

Gemfile.lock
Errors like `Superclass Mismatch` and `undefined method app_views_...`
are getting thrown every which way in a few hours of coding. I don't
quite get why this is, but I am hopeful that upgradine zeitwerk may
help?
Alternatively, we may want to dig into puma?
=> Something is causing method / constant lookup to go sideways

.github/workflows/test-convene-web.yml
Connects: https://github.com/zinc-collective/convene/issues/235
so we can run test when contributors open pull request on their forked repo.
=> Run GH actions on forked repo

app/furniture/markdown_text_block/_form.html.erb, app/utilities/jitsi_utility/_form.html.erb, app/views/application/_error.html.erb, app/views/application/_password_field.html.erb, app/views/application/_select.html.erb, app/views/application/_text_field.html.erb, app/views/authenticated_sessions/_form.html.erb, app/views/rooms/_form.html.erb, app/views/spaces/edit.html.erb, app/views/waiting_rooms/show.html.erb, features/harness/WaitingRoomPage.js, features/steps/room_steps.js
Pulled from [our work cleaning up the payment form](https://github.com/zinc-collective/convene/pull/463); this should make it a bit more consistent when working with partials.
=> Consolidate naming of local variables in form partials

features/lib/MailServer.js, package.json
See: https://github.com/zinc-collective/convene/commit/602cc9fa93b0b12b7eb06d553949efe2701cc3fa#diff-1c67ac0004ed4084600492cb9d08dff4296781c983078ac9423474d646617a23R30
When we first started writing this, it seemed reasonable to use `delay`
(which looks like it's not built into node, or cucumber-js, so I have no
idea where the global function even came from?!) to wait for 10ms and try
again; however that appears to have resulted in race conditions when moving to
setInterval; so let's try to leverage `retry-promise` so we don't have
to keep hand-rolling trying again.
=> Leverage existing retry package over handrolled one

app/views/rsvps/show.html.erb, features/harness/InvitationResponsePage.js, features/harness/Page.js, features/harness/SignInPage.js, features/lib/Actor.js, features/lib/Invitation.js, features/lib/MailServer.js, features/spaces/invitations.feature, features/steps/invitation_steps.js, features/support/parameter-types/actor.js, features/support/parameter-types/space.js
See: https://github.com/zinc-collective/convene/issues/117
Strangely, there seems to be some Unobtrusive JavaScript left over in our application from the move to Turbo, which had broken the invitation flow!
Thankfully, our TDD ensemble discovered it as part of automating that check; and we fixed it!
This also:
- Reframes the Accepting an Invitation as a Guest Scenario to use existing Invitation Steps and the newer pattern we follow for defining steps
- Finds and resolves some greedy regexs in parameter types
=> Automate check for accepting an Invitation as a Guest

Gemfile, Gemfile.lock, app/assets/stylesheets/components/form.scss, app/furniture/check_dropbox/_in_room.html.erb, app/furniture/check_dropbox/check.rb, app/furniture/check_dropbox/check_policy.rb, app/furniture/check_dropbox/checks/_form.html.erb, app/furniture/check_dropbox/checks/_new.html.erb, app/furniture/check_dropbox/checks/new.html.erb, app/furniture/check_dropbox/checks_controller.rb, app/javascript/controllers/check_dropbox_controller.js, app/lib/item.rb, app/models/item_repository.rb, app/utilities/plaid/plaid_utility.rb, cassettes/check_dropbox/checks/create.yml, cassettes/check_dropbox/checks/index.yml, config/locales/furniture/check_dropbox/en.yml, spec/factories/furniture/check_dropbox.rb, spec/factories/utilities/plaid.rb, spec/furniture/check_dropbox/check_spec.rb, spec/furniture/check_dropbox/checks_request_spec.rb, spec/models/item_repository_spec.rb, spec/spec_helper.rb
See: https://github.com/zinc-collective/convene/issues/186
As we were doing a "cleanup" review of the interaction flow for the payment form, we realized that there are no validations on any of the data. This was in part because we were rushin', and also because the way we're doing Item as a thing independent of ItemRecord was making error handling a bit harder than if it were an ApplicationRecord instead of a Model.
=> Add Validation to Checks

app/furniture/media_box/README.md, features/furniture/media_box.feature, features/furniture/mediabox.feature, features/vendor-affiliates.feature
This is kind of a "Seed" of an idea; but wouldn't it be cool if people could write their reviews of particular pieces of media; including content warnings, thematic elements, and whether or not they endorse it; and Convene offered links to buy/rent the media in a way that generated affiliate revenue at the Neighborhood level?
There are likely three main use cases:
- "Reviewing Media" for people who like to keep a record and share what they've read/listened to/watched 
- "Finding Media" for people who are like "What do I wanna watch/read/listen to?"
- "Reading Media Reviews" for people who want a more in-depth way of evaluating potential media choices.
- "Acquiring Media" once people have made a "I want this!" decision.
Each Space operates a MediaBox and own their Reviews of the Media; …
=> Initial sketch of a "MediaBox"

package.json
Builds be like:
```
yarn install v1.22.17
[1/5] Validating package.json...
error convene@0.1.0: The engine "node" is incompatible with this module. Expected version "~16.13". Got "16.14.0"
error Found incompatible module.
```
But I think `^16.13` means `>16.13 <17.0`
=> Github is sad because ~16.13 does not include 16.14

package.json, yarn.lock
In https://github.com/zinc-collective/convene/pull/495, we thought we
didn't want to jump from 6 to 7 without bumping Rails first.
We also thought that maybe we didn't even need UJS, because we have no
use-cases where we are explicitely using it.
However, after removing UJS
https://github.com/zinc-collective/convene/pull/576 we discovered that
we _do_ use it for signing people out!
We did a review of the changelog and the commits between 6.X and 7.0 for
ujs, and they seemed computationally meaningless; so we think it's safe
to just bump and defer the deletion.
Co-authored-by: Naomi Quinones …
=> Rails-ujs is probably safe to bump to 7

app/models/invitation.rb, app/models/person.rb, app/views/rsvps/show.html.erb, app/views/space_invitation_mailer/space_invitation_email.text.erb, features/spaces/invitations.feature, features/spaces/moderation.feature, spec/models/invitation_spec.rb, spec/models/person_spec.rb
See: https://github.com/zinc-collective/convene/issues/117#issuecomment-962519714
@anaulin had noticed that the invitation emails were left dangling after
"Invited by..." when the Invitor doesn't have a name.
We've pulled out a `display_name` method for the Person, and delegate it
explicitely in the `Invitation` as the `invitor_display_name`.
This gives us a seam for making more intelligent decisions about how we
present peoples names/emails/identities/etc in the application, but does
not exercise that seam to aggressively.
=> Invitations include name _or_ email of the Invitor

app/models/person.rb, spec/models/person_spec.rb
I was doing some poking at the data on my machine, deleted a person, and
discovered that some of their PII and Context sticks around when it
probably shouldn't.
Now when a Person is destroyed, their Space Membershipsand
Authentication Methods do as well.
=> Also destroy Person's AuthenticationMethods and SpaceMemberships

features/spaces/blueprints.feature
See: https://github.com/zinc-collective/convene/issues/476
Ana had noticed that our Blueprint's overwrite stuff they probably
shouldn't; and I had noticed something similar previously as well. I had
initially tossed Blueprints into the codebase as an affordance for
developers to quickly create a Space with initial data.
However, I'm beginning to think that it makes sense to be a bit more
intentional with them, and am promoting them to a sub-feature of the
Space feature.
=> Sketch out the initial feature file for Space Blueprints

app/assets/stylesheets/base/layout.scss, app/assets/stylesheets/components/form.scss, app/furniture/embedded_form.rb, app/furniture/embedded_form/_form.html.erb, app/furniture/embedded_form/_in_room.html.erb, app/furniture/furniture.rb, app/furniture/markdown_text_block.rb, app/views/application/_url_field.html.erb, features/furniture/embedded_form.feature
Squashed commit of the following:
commit 6054b87ce21f8a07084d9ccd00f3d0c0c1fedcf6
Author: Zee Spencer <zspencer@users.noreply.github.com>
Date:   Wed Mar 9 20:05:15 2022 -0800
Add some todos for cleanup
commit ede2fbff74f634756b5ba6dfa7a76f765ea20307
Author: Zee Spencer <zspencer@users.noreply.github.com>
Date:   Wed Mar 9 19:58:10 2022 -0800
Sprout `EmbeddableForm` Furniture
As we begin this, we thought that it makes sense to start down the path
of using a generic piece of Furniture, so that we're catfooding what the
customer experience for other Spaces look like.
So we've sprouted a piece of furniture that can embed a form from
Airtable right into a Space! MAGIC!
Co-authored-by: Ana Ulin <ana@ulin.org>
commit 76b59e4b47b033882882ab93a24e778df14f2851
Author: Zee Spencer …
=> Sprout EmbeddedForm independent of Space Registration

app/controllers/authentication_methods_controller.rb, app/models/authentication_method.rb, app/models/authentication_method/serializer.rb, app/policies/application_policy.rb, app/policies/authentication_method_policy.rb, config/locales/authentication_method/en.yml, config/routes.rb, spec/factories/authentication_methods.rb, spec/models/authentication_method_spec.rb, spec/requests/authentication_methods_request_spec.rb, spec/requests/spaces_request_spec.rb, spec/support/auth_helpers.rb
The AuthenticationMethod API wants to be used in the feature tests to
make it a little bit easier to create People and authenticate as them
programmatically.
This pulls the work done in
https://github.com/zinc-collective/convene/pull/594 for exposing that
API out into it's own PR that we can merge independently, then rebase
into the feature branch for Invitations.
=> Sprout API for Creating Authentication Methods

bin/test, features/support/env.js, package.json, yarn.lock
We noticed that in orer to run `yarn test` locally, we had to prefix it
with `dotenv yarn test`, which was kinda silly.
This makes it so running `yarn test` will load whatever is in `.env` for
us, hooray!
=> Use `dotenv` package to populate .env in Cucumber

app/controllers/spaces_controller.rb, app/models/space.rb, app/models/space/factory.rb, spec/factories/space.rb, spec/models/space/factory_spec.rb
OK, so I agree that the callback system was probably a little fraught.
Complexity emerges at those seams.
It may make sense for us to pull the responsibility into a factory.
Now if we want to create a space without executing a pile of callbacks,
we can.
And if we want to keep the controllers focused on the secure translation
of the HTTP protocol into domain objects we can.
And it sides steps a `Service` class (which I find reminiscent of the
`Manager` classes of my JavaDays.
=> Collect responsibility for applying a Space::Blueprint

app/models/system_test_space.rb, features/lib/Api.js, features/lib/Invitation.js, features/lib/Space.js, features/lib/linkParameters.js, features/rooms/discovering-rooms.feature, features/steps/identification_steps.js, features/steps/space_steps.js, features/steps/utility_hookup_steps.js, features/support/env.js, features/support/parameter-types/space.js, package.json, yarn.lock
This swaps our scenarios to append test data to the local database, rather than re-use the `system-test` space over and over and over again.
It runs safely on CI, but if you run the test suite twice you start to see errors.
I believe this is because we're not applying a the `testId` to the Invitation Email, so when an invitation goes out it goes out to the same email address each time; which can result in race-conditions when following links.
It may be worth tilting at that windmill a bit more before merging; but I'm not sure.
Thoughts?
=> Spaces: Use Spaces API to create a Space in Scenarios

app/controllers/space_memberships_controller.rb, app/models/invitation.rb, app/models/space_membership.rb, app/models/space_membership/serializer.rb, app/policies/space_membership_policy.rb, config/routes.rb, spec/models/space_membership_spec.rb, spec/policies/space_membership_policy_spec.rb, spec/requests/space_memberships_request_spec.rb
While doing test setup for the Invitation tests, we needed to create a
SpaceMembership via the API. However, there was no API for
SpaceMemberships.
This sprouts an initial API, with policy objects, serializers, etc. so
that SpaceMemberships may be created programmaticaly
=> Sprout Space Membership API Endpoint

.github/workflows/deploy.yml
This is to replace the no-longer-working Heroku<->GitHub autodeploy.
For this to work, I'll need to set the `HEROKU_API_KEY` secret under Settings -> Secrets (I do not have access to this section of the settings at the moment).
=> Add GitHub Action to automatically deploy to Heroku

app/furniture/embedded_image.rb, features/furniture/spotlight.feature.md, features/lib/Furniture.js, features/lib/Model.js, features/lib/Room.js, features/steps/furniture/spotlight_steps.js, features/steps/furniture_steps.js, features/support/parameter-types/README.md, features/support/parameter-types/devices.js, features/support/parameter-types/furniture.js, features/support/parameter-types/furniture/spotlight.js
This builds on the infrastructure defined in the [Furniture: Livestream Owncast!](https://github.com/zinc-collective/convene/pull/669/files)
patch, which probably should be merged first (or I should decompose the
supporting bits)
Essentially, the "Image" furniture is a great start, but I'm hoping to
shift our design from the technical to the marketing / designer friendly
use-case.
Ideally, a Spotlight isn't just a hero image, but can also support the
little "Here's an icon + summary + call to action" that many sites use
to specify their value propositions.
By making the Spotlight responsible for exposing affordances like
alt-text, focal point, aspect ratio, etc. we can give folks who are
being intentional about the presentation of their digital storefront
with super-powers that help them …
=> Furniture: Spotlight - Describe feature and sketch out steps

app/models/space_membership/serializer.rb, spec/requests/space_memberships_request_spec.rb
Turns out, our `SpaceMembership::Serializer` was not smert enough to
handle when space_id or member_id were missing; which was causing a sad
error.
=> Space Memberships API Endpoint handles invalid parameters gracefully

app/controllers/rsvps_controller.rb, app/models/authentication_method.rb, app/models/blueprint.rb, app/models/rsvp.rb, app/views/rsvps/update.html.erb, config/locales/rsvp/en.yml, features/harness/SignInPage.js, features/lib/Actor.js, features/lib/Api.js, features/lib/AuthenticationMethod.js, features/lib/Space.js, features/lib/SpaceMembership.js, features/rooms/locking-and-unlocking-rooms.feature, features/spaces/invitations.feature, features/spaces/invitations/responding_to_invitations.feature, features/steps/invitation_steps.js, features/steps/room_steps.js, features/steps/space_steps.js, features/support/CustomWorld.js, features/support/env.js, features/support/parameter-types/actor.js, features/support/parameter-types/invitation.js, spec/factories/authentication_methods.rb, spec/models/blueprint_spec.rb, spec/requests/authentication_methods_request_spec.rb, spec/requests/spaces/invitations/rsvp_spec.rb
There were some strange behaviors with how Invitations work, in particular:
- We never confirmed that Guests had access to the email address; we just assumed if they had the link they were totally the right person. That's not a good idea; so we made it necessary for them to confirm their access to the email address by using a OneTimePassword
- Neighbors couldn't accept Invitations at all; which seemed not-great.
- Once an Invitation was accepted, the user  was just kinda left hanging.
This resolves those rough edges, as well as fleshes out the full feature test suite for inviting people to a Space.
See: https://github.com/zinc-collective/convene/issues/117
=> Invitations: Redesign Invitations

app/furniture/embedded_form.rb, app/furniture/embedded_form/_in_room.html.erb, spec/factories/furniture/embedded_form.rb, spec/furniture/embedded_form_spec.rb
https://github.com/zinc-collective/convene/issues/619
I got tired of having to go through the airtable menus to get the code
from their iframe embed document, and I wanted a win!
=> Embedded Forms can accept Any Airtable Form URL!

app/views/rooms/_room.html.erb
Furniture Placement's have a Slot, but the Slot doesn't get respected in ordering.
=> Rooms: Respect Furniture Placements' Ranks

Gemfile, Gemfile.lock
We probably don't want to roll our own one of these things, and with
more and more furniture being financially oriented it's probably a good
idea to start using it when we can.
=> Add `money` for handling currency values

Gemfile, Gemfile.lock, app/assets/stylesheets/components/button.scss, app/controllers/rsvps_controller.rb, app/models/invitation.rb, app/models/person.rb, app/models/rsvp.rb, app/views/rsvps/_ignored.html.erb, app/views/rsvps/show.html.erb, app/views/rsvps/update.html.erb, app/views/space_invitation_mailer/space_invitation_email.text.erb, config/locales/rsvp/en.yml, cucumber.cjs, db/migrate/20220707003459_add_invitation_status_enum.rb, db/schema.rb, features/harness/InvitationResponsePage.js, features/lib/Invitation.js, features/spaces/invitations.feature, features/steps/invitation_steps.js, features/test_reports/cucumber_test_report.js, spec/factories/invitation.rb, spec/mailers/previews/space_invitation_mailer_preview.rb, spec/models/invitation_spec.rb, spec/models/person_spec.rb, spec/requests/spaces/invitations/rsvp_spec.rb
Implement ignoring Invitations, the next step in https://github.com/zinc-collective/convene/issues/117
=> Invitations: Ignoring Invitations

Gemfile, Gemfile.lock, spec/factories/client.rb, spec/factories/invitation.rb, spec/factories/person.rb, spec/factories/room.rb, spec/factories/space.rb, spec/spec_helper.rb
Test run https://github.com/zinc-collective/convene/runs/7779315597?check_suite_focus=true failed due to the factory trying to make a Space with a duplicated name. This PR adds a sequential number to the Space Name to avoid such collisions.
Bonus: replaced FFaker with Faker, which is identical and better maintained.
=> Add a sequential number to Factory's Space name to avoid failures due to duplicated names

app/views/furniture_placements/_form.html.erb, app/views/furniture_placements/_furniture_placement.html.erb, app/views/rooms/_room.html.erb
Hello,
We have improved some nice styling to the furniture placement :) 
https://github.com/zinc-collective/convene/issues/782
Co-authored-by: Kelly Hong <k_ahong@yahoo.com>
=> Prevent furniture icons and heading overlapping

app/models/invitation.rb, app/models/rsvp.rb, app/models/space_membership.rb, app/views/space_memberships/_space_membership.html.erb, db/migrate/20220901010259_add_invitation_reference_to_membership.rb, db/schema.rb, spec/requests/spaces/invitations/rsvp_spec.rb
This PR adds some of the functionality outlined in https://github.com/zinc-collective/convene/issues/117:
* adds an `invitation_id` reference to the `space_memberships` table
* displays the invitor name on a membership, if it has an associated invitation
=> Add invitation reference to space_memberships table

Gemfile, Gemfile.lock
I set us to use the release candidate for the `rspec-rails` version that support Rails 7.x. (Looks like `rspec-rails` are in the process of changing their versioning scheme, so there isn't a non-RC version that fits us for now.)
=> Switch back to the mainline rails-spec gem

app/furniture/breakout_tables_by_jitsi.rb, app/furniture/embedded_form.rb, app/furniture/furniture.rb, app/furniture/livestream.rb, app/furniture/markdown_text_block.rb, app/furniture/marketplace.rb, app/furniture/marketplace/_in_room.html.erb, app/furniture/marketplace/_marketplace.html.erb, app/furniture/marketplace/product.rb, app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/products/_product.html.erb, app/furniture/marketplace/products_controller.rb, app/furniture/payment_form.rb, app/furniture/placeable.rb, app/furniture/spotlight.rb, app/furniture/video_bridge.rb, app/views/furniture_placements/_furniture_placement.html.erb, config/routes.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/products_request_spec.rb
This starts to shift our Furniture and Item system away from an inheritance oriented rails-adjacent structure to a more Rails-forward structure.
Furniture now places it's routes against the *room*, which allows it to support either Singleton-type Resource routes, or more traditional Resources routes.
Further, it brings the `Placeable` interface a bit closer to ActiveRecord; which should reduce pain-points as we unwind the current overly-restrictive and complex Furniture/Item design.
=> Marketplace: Products Controller persists Products!

app/furniture/spotlight/image.rb
So, it turns out there's a pretty nasty wart in the `furniture` implementation where setting the data requires you to know the type of the key being set in the dictionary.
That's pretty gross, and probably something we should fix at the architectural level, since it's cost us a ton of brain-space already and we're only just writing our first few bits of Furniture.
That said, in the meantime as you add additional attributes to the Image item, we should be able to follow the pattern of using string keys.
=> Spotlight: Use `"attr"` rather than `:attr` when setting Alt Text

README.md
remove duplicate TOC that displayed in root [README](https://github.com/zinc-collective/convene).
=> doc: remove duplicate TOC in README

app/models/membership.rb, app/views/memberships/show.html.erb, config/breadcrumbs.rb
I noticed when working on the
[Journal](https://github.com/zinc-collective/convene/issues/898) that when you click on the `Account` link, it kind of drops you into the middle of no where.
This adds a breadcrumb, so we can find our way back! Yay!
=> Memberships: Adds Breadcrumb from Membership: Show page

config/initializers/money.rb
As suggested in the instructions at https://github.com/zinc-collective/convene/pull/new/au/fix-deprecation
=> Turn on an explicit locale backend for the Money gem, to get rid of a deprecation message

app/furniture/furniture.rb, app/furniture/placeable.rb
OK, so the trajectory I am going with is we can get rid of the `Furniture`, `FurniturePlacement` and `Placeable` classes and the weird things they do in favor of standard-ass inheritance. I expect that most of the ways those pieces fit within the system will mostly coalesce into the `Furniture` class; but I'm not quite ready to make that leap just yet.
This will let us go through the `MarkdownTextBlock`, `Spotlight`, `VideoBridge`, and `PaymentForm` Furniture and cut their LoC by quite a bit; as well as get us into a much smoother groove when extending those features.
The refactor seemed to serve both the `Marketplace` and the `Journal` feature when we did [the first in an
Ensemble](https://github.com/zinc-collective/convene/pull/862/files#diff-d2a16da4475658ee74f5ff09ab97db7f2ec836b017ae7 …
=> Furniture: Extract seam to ease the elimination of Placeable

app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/products/_form.html.erb, app/views/application/_money_field.html.erb, spec/furniture/marketplace/product_policy_spec.rb, spec/furniture/marketplace/product_spec.rb
Added money input field with dollar sign in front of the money and the end of the number with @zspencer to see with the tailwind component. For now it is always dollar sign as a hard coded string.
=> Add money field with tailwind stylings

app/controllers/application_controller.rb, app/controllers/me_controller.rb, app/controllers/waiting_rooms_controller.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/products_controller.rb, app/policies/application_policy.rb, app/policies/guest_policy.rb, app/policies/person_policy.rb, app/policies/waiting_room_policy.rb, spec/furniture/marketplace/products_controller_request_spec.rb
https://github.com/zinc-collective/convene/issues/926
We noticed that, despite our lack-of-authorize calls in some of our Furniture controllers, Pundit was not throwing a shit-fit.
This should make pundit throw more shit-fits about missing Policy objects.
=> Prevent false-positives for Pundit's verify_authorized check

app/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/marketplace_spec.rb
See: https://github.com/zinc-collective/convene/issues/831
I keep forgetting that foreign keys need to be taken care of explicitly
in relations. I'm pretty sure there's a gem that notices mismatches
between dependent settings and database schemas but I don't remember
what it is :X.
=> Marketplace: Destroy Products when Destroying Marketplaces

app/furniture/marketplace/cart.rb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/shopper.rb, db/migrate/20221208013832_add_shopper_to_marketplace_carts.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/shopper_spec.rb
When there were multi Marketplaces in a neighborhood, the page would crash. Now the Cart is attached to a Shopper which prevents the conflict of trying to find the Cart by the same Id across Marketplaces.
=> Marketplace: Cart attach to Shopper

app/controllers/application_controller.rb, app/controllers/authenticated_sessions_controller.rb, app/controllers/furniture_placements_controller.rb, app/controllers/memberships_controller.rb, app/controllers/rooms_controller.rb, app/controllers/spaces_controller.rb, app/controllers/utility_hookups_controller.rb, app/helpers/rooms_helper.rb, app/models/authenticated_session.rb, app/views/authenticated_sessions/_form.html.erb, app/views/layouts/_header.html.erb, app/views/spaces/_room_card.html.erb, app/views/spaces/edit.html.erb, app/views/utility_hookups/_form.html.erb, app/views/waiting_rooms/show.html.erb, config/breadcrumbs.rb, config/routes.rb, features/harness/RoomEditPage.js, spec/requests/spaces/rooms_request_spec.rb, spec/requests/spaces/utility_hookups_spec.rb, spec/requests/spaces_request_spec.rb
OK so some work still to do here...
=> Spaces: Support BYO Domains Everywhere!

app/furniture/journal/entries_controller.rb
https://github.com/zinc-collective/convene/issues/898
It just feels weird not to have the actual title in the page...
=> Journal: Use the Entry Headline in Page Title

app/furniture/journal/entry.rb, app/furniture/journal/renderer.rb, app/lib/renders_markdown.rb, spec/furniture/journal/entry_spec.rb
https://github.com/zinc-collective/convene/issues/898
There's probably a better way to do this that takes into account that handles may not use the same format on every fediverse instance; but we'll cross that bridge when we come to it.
=> Journal: Entries with @handle@example.com link to https://example.com/@handle

app/controllers/application_controller.rb, app/controllers/authenticated_sessions_controller.rb, app/controllers/furniture_placements_controller.rb, app/controllers/memberships_controller.rb, app/controllers/rooms_controller.rb, app/controllers/spaces_controller.rb, app/controllers/utility_hookups_controller.rb, app/helpers/rooms_helper.rb, app/models/authenticated_session.rb, app/views/authenticated_sessions/_form.html.erb, app/views/layouts/_header.html.erb, app/views/spaces/_room_card.html.erb, app/views/spaces/edit.html.erb, app/views/utility_hookups/_form.html.erb, app/views/waiting_rooms/show.html.erb, config/breadcrumbs.rb, config/routes.rb, features/harness/RoomEditPage.js, spec/requests/spaces/rooms_request_spec.rb, spec/requests/spaces/utility_hookups_spec.rb, spec/requests/spaces_request_spec.rb
This had been bugging me for a bit, where the paths on the page would always include the spaces, even if they were being routed to a custom domain.
Now, we send folks to the domain that the space claims and drop the Space from the path, but only on urls built using Rails Polymorphic url builders.
For example:
`space_room_path(space, room)` will still go to
`current_domain.example.com/spaces/:space_id/rooms/:room_id`, while `url_for([space, room])` or `link_to([space, room])` will go to
`space_domain.example.com/rooms/:room_id`
=> Space: BYO Domains drop Space from polymorphic_urls

app/controllers/application_controller.rb, spec/requests/spaces_controller_request_spec.rb
https://github.com/zinc-collective/convene/issues/23
When I was testing #74 on https://beta.zeespencer.com/ I discovered that it didn't quite work, and was nesting sub-domains (i.e. `beta.zeespencer.com` became `beta.beta.zeespencer.com`)
This is likely because the [`domain` option for `url_for`](http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for) doesn't actually do the whole domain; just the TLD!
Womp womp!
=> Spaces: Support Sub-domains in BYO Domains

app/furniture/marketplace/checkout_policy.rb
(this PR is for merging into WIP https://github.com/zinc-collective/convene/pull/1031)
This PR updates the `CheckoutPolicy` implementation to satisfy the expectations in the spec. I do not know if this is precisely the behavior we want -- e.g. maybe we want a "marketplace admin" (space owner?) to be able to always see a Checkout -- but we can expand the behavior later.
This fixes the test failures in https://github.com/zinc-collective/convene/pull/1031
=> Update CheckoutPolicy to match spec expectations

.github/workflows/test-convene-web.yml
Trying to make the CI yml easier to scan/understand so its easier to [break out tests into parallel jobs](https://github.com/zinc-collective/convene/pull/1053) in the near future. May be via [matrix](https://www.testmo.com/guides/github-actions-parallel-testing).
Using [this](https://boringrails.com/articles/building-a-rails-ci-pipeline-with-github-actions/) sample format yml which has handy names before each action.
It's still a bit unclear in the current yml if it includes enough steps to split out building the app in a separate job and building the test enviro to run tests in another job.
=> add names to clarify github actions

Gemfile, Gemfile.lock, app/components/icon_button_component.rb, app/controllers/furniture_placements_controller.rb, app/furniture/furniture.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_product_policy.rb, app/furniture/marketplace/cart_products_controller.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/checkouts_controller.rb, app/furniture/marketplace/marketplaces_controller.rb, app/furniture/marketplace/product.rb, app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/shopper.rb, app/models/blueprint.rb, app/models/utility_hookup.rb, config/initializers/money.rb, db/migrate/20221208013832_add_shopper_to_marketplace_carts.rb, spec/components/icon_button_component_spec.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb, spec/furniture/marketplace/product_policy_spec.rb, spec/models/furniture_placement_spec.rb, spec/requests/utility_hookups_controller_request_spec.rb
So, I noticed a giant pile of red errors when rubocop was running; which was like... ok... and then it turned out that we were using the `standardrb` gem, which is not the same as the `standard` gem; so it was out of date...
So I updated *that* and then ran `bin/rubocop -a` which made a bajillion changes...
Computers are bad.
=> Lint: Apparently `standard` and `standardrb` are different

app/furniture/marketplace/README.md
From: https://github.com/zinc-collective/convene/pull/1057#discussion_r1082153560
=> Marketplace: Lay out the HCI for Shopper Purchasing Products

app/furniture/furniture.rb, app/furniture/marketplace.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_products_controller.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/checkouts/show.html.erb, app/furniture/marketplace/checkouts_controller.rb, app/furniture/marketplace/controller.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/order_policy.rb, app/furniture/marketplace/orders/_order.html.erb, app/furniture/marketplace/orders/show.html.erb, app/furniture/marketplace/orders_controller.rb, app/furniture/marketplace/products_controller.rb, app/furniture/marketplace/routes.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb
Where `Checkout` is useful for handling a Checkout flow for the Payment Processor, it doesn't make a ton of sense from a Buyer perspective once the Cart has been Checked out.
I've sprouted an `Order` model, with corresponding Controllers, and moved the `checkouts/show` and `checkouts/_checkout` views to `orders/show` and `orders/_order`.
=> Marketplace: Differentiate between Checkout and Order

config/environments/production.rb
See:
- https://developers.cloudflare.com/ssl/edge-certificates/encrypt-visitor-traffic/
- https://support.cloudflare.com/hc/en-us/articles/205893698-Configure-Cloudflare-and-Heroku-over-HTTPS
So, apparently if you force ssl when you're using Cloudflare on top it can put the application into a redirect loop.
This allows a Neighborhood who relies on Cloudflare for DNS + Security to disable Rails' built in SSL redirection by setting the `FORCE_SSL` environment variable to false.
Note: I would really prefer not to be using Cloudflare at all, however they continue to provide the best free plan and we can't afford to pay for a CDN at this time.
=> Neighborhood: Support Cloudflare SSL w/Heroku

app/lib/space_routes.rb, config/routes.rb
https://github.com/zinc-collective/convene/issues/1067
Turns out, having the Space routes split into two sections meant some of the updates to the routes did not get applied for spaces with BYO-Domains.
This... fixes that...
=> Spaces - BYODomains: Fix broken Space/edit page

app/controllers/furniture_placements_controller.rb
https://github.com/zinc-collective/convene/issues/709
When we were smoke-testing the Marketplace, I realized we had to destroy and re-create the Marketplace, but the way we delete them was... uhhh not respecting the (very prudent) foreign-keys we had added!
So now FurniturePlacements polymorph into their child implementation prior to destruction, so that all `dependent: :destroy`  etc. actions get carried out.
Co-authored-by: Dalton <daltonrpruitt@users.noreply.github.com>
=> Furniture: Destroying a Furniture respects `dependent:` settings

app/controllers/application_controller.rb, app/models/invitation.rb, app/models/rsvp.rb, app/views/invitations/index.html.erb, app/views/rsvps/_pending.html.erb, app/views/rsvps/update.html.erb, app/views/space_invitation_mailer/space_invitation_email.text.erb, spec/requests/spaces_controller_request_spec.rb
https://github.com/zinc-collective/convene/issues/1078
https://github.com/zinc-collective/convene/issues/117
There's probably a bunch of other domain objects that want `parent_location` set; but this should be good enough to get the invitations flow unbroken.
=> Memberships: Invitations work on BYO Domains

app/furniture/marketplace/checkout.rb
It may be better for us to include the option to select Delivery via Piikup here vs Take-out or Self-pickup; but this seems decent enough for now.
=> Marketplace: Collect delivery information at Checkout

app/controllers/application_controller.rb, config/environments/production.rb
Edit: TURNS OUT `request.host` and `request.domain` are different! `request.host` is the full host (i.e. `foo.example.com`); while `request.domain` is just the tld + domain name (i.e. `example.com`)
---
~~It's unclear why, but my best guess is that the CNAME record and Cloudflare are doing some degree of domain rewriting or something and causing them to go back and forth forever.~~
Logs for redirect loop here:
```
2023-01-31T16:52:47.701120+00:00 heroku[router]: at=info method=GET path="/" host=piikup-sandbox.zinc.coop request_id=b946577a-5ea4-4e2b-9a37-4619b1225911 fwd="2601:643:8980:ebb0:19f1:1a52:9f91:7d5c,172.71.154.35" dyno=web.1 connect=0ms service=12ms status=302 bytes=562 protocol=http
2023-01-31T16:52:47.508025+00:00 …
```
=> BYODomains: Prevent redirect loop on subdomains

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/stripe_accounts_controller.rb
The account link object was being made in the controller, and while that worked it was a mess.
This adjusts things so it's a little bit more order(ly) and places it in the model where it's "best."
Co-authored-by: Dalton <daltonrpruitt@users.noreply.github.com>
=> Marketplace: Refactor - Pull AccountLink up into Marketplace

app/models/demo_space.rb
A left-over from https://github.com/zinc-collective/convene/pull/1051, which is causing non-working video-bridges to magically re-appear in the Demo space.
=> Remove obsolete video_bridge placements from the Demo space

.github/workflows/test-convene-web.yml, docker-compose.yml
We had hardcoded in 12, but latest is probably more appropriate since postgresql's releases are generally top-notch and getting stuck in old postgres is a recipe for sad :'(
That said, it could also be a point of friction since it will mean we'll need to learn how to bump major versions of local / neighborhood databases... Anyway meh.
=> `Neighborhood`: Default to `postgres:latest` image for new databases

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/furniture/journal.rb, app/furniture/journal/journals/_journal.html.erb, app/furniture/journal/routes.rb, app/helpers/pagy_helper.rb, config/initializers/pagy.rb
I am poking with using [Pagy](https://github.com/ddnexus/pagy) since it has better performance characteristics and more regular commits than either Kamanari or will_paginate.
That said, it doesn't seem to have great affordances for overriding classes on the nav and has had 6 major releses since it's inception a few years ago.
Anyway, it seems like not the worst gem for the job? Especially since it supports many different styles of pagination (date, cursor, etc)
Thoughts?
=> `Journal`: `Entry`s are paginated

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/routes.rb, app/furniture/marketplace/stripe_accounts_controller.rb, app/furniture/marketplace/stripe_events_controller.rb, app/furniture/marketplace/unexpected_stripe_event_type_error.rb, spec/factories/furniture/marketplace.rb, spec/factories/utility_hookup.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb, spec/models/utility_hookup_spec.rb, spec/requests/rooms_request_spec.rb, spec/requests/utility_hookups_controller_request_spec.rb
OK, this is the first shot across the bow for listening to stripe checkout completions and sending the money onwards to Vendors
Co-authored-by: Dalton <daltonrpruitt@users.noreply.github.com>
**TODO**
=> `Marketplace`: `Vendor` receives `Payment` upon `Order` completion

app/furniture/furniture.rb, app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, db/migrate/20230210204421_rename_marketplace_carts_and_drop_foreign_key_constraint.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/marketplace_spec.rb, spec/requests/furniture_placements_controller_request_spec.rb
~I'm not 100% sold on this fixing the [Sentry Issue](https://github.com/zinc-collective/convene/issues/1110) that prompted me to do the patch, but hopefully it makes things a little tidier.~
That's because I had the wrong Sentry Issue! This one is the correct one [Sentry Issue](https://github.com/zinc-collective/convene/issues/1112)
In particular:
1. `Marketplace`s can be destroyed while preserving `Shopper`s `Order` history
2. `Furniture#from_placement` will raise a better error when attempting to load `Furniture` that doesn't exist  
3. the `FurniturePlacementController`s Request spec lives in a place that folks working from Rails standards will find more easily
=> `Marketplace`: Allow deletion of `Marketplace`

app/furniture/marketplace/marketplaces/_form.html.erb, app/views/application/_money_field.html.erb
This fix makes it possible to set a delivery fee with two decimals.
=> Fix settings for marketplace delivery fee field

app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/edit.html.erb
Instead of prompting to "connect stripe account", which fails if there is no Stripe API key, now we prompt to add a Space-level Stripe API key.
Initially I was linking directly to `utility_hookups/new`, but the problem with that is that it is possible to have already a utility hookup for stripe, but no API key, so going to `space/edit` seems better for now.
At some point we'll want to surround these buttons with policy checks, because maybe the vendor setting up the marketplace doesn't have permissions to set up the Stripe hookup for the space.
https://user-images.githubusercontent.com/6729309/219253804-57217199-06f2-49a0-9e37-034f3fd11158.mp4
https://user-images.githubusercontent.com/6729309/219254250-5764d484-8d53-4e32-931f-fbaa1ad2ee …
=> Show a link to add a Stripe API key if one isn't set

.vscode/settings.json, app/controllers/utility_hookups_controller.rb, app/policies/utility_hookup_policy.rb, spec/factories/utility_hookup.rb, spec/models/utility_hookup_spec.rb, spec/requests/utility_hookups_controller_request_spec.rb
https://github.com/zinc-collective/convene/pull/1072/
I had introduced a bug when [I tried to clean up the UtilityHookup design](https://github.com/zinc-collective/convene/pull/1072/)
=> `Utility`: 🐞🔨 `Member` may Set `Utility` Attributes

app/furniture/marketplace/README.md
=> `Marketplace`: Add instructions for handling events from Stripe

app/utilities/stripe_utilities/_form.html.erb, app/views/spaces/edit.html.erb, config/environments/development.rb, config/locales/utilities/stripe_utilities/en.yml
https://github.com/zinc-collective/convene/issues/1002
Because I need it every single time 😅
Also renamed "Utility Hookups" to "Utilities" in the UI.
=> `Stripe`: Add a bit of help to the UI about finding the Stripe API keys

app/furniture/marketplace/checkout.rb, app/furniture/marketplace/checkouts_controller.rb, app/furniture/marketplace/locales/en.yml, spec/furniture/marketplace/checkout_spec.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb
So, it turns out *sometimes* Stripe will fire off that checkout session completed event faster than we can handle it!
Now that we listen for webhook events, it makes sense that we don't need to send people back to show their checkout; and can send them right on to their order.
Note: We may be able to get rid of the stripe checkout session id bits completely, since we use the transfer group as our key for looking up which order to apply the charge to.
=> `Marketplace`: Prevent race-condition in `Checkout`

app/models/blueprint.rb, lib/tasks/release.rake
- https://github.com/zinc-collective/convene/issues/476
- https://github.com/zinc-collective/convene/issues/890
This was put in place to reduce cost-of-setup, but is no longer necessary.
=> `Neighborhood`: Delete dead `Client`-based `Blueprint`.

app/policies/space_policy.rb, app/views/spaces/edit.html.erb
Turns out, we had never exposed an affordance for setting the `Space` entrance! Whoopsie-doodle!
=> `Space`: `Entrance` may be set via UI

app/models/person.rb, app/policies/furniture_placement_policy.rb, app/policies/room_policy.rb, app/policies/space_policy.rb, app/policies/utility_hookup_policy.rb, db/migrate/20230227232512_add_operator_to_person.rb, db/schema.rb, spec/policies/room_policy_spec.rb, spec/policies/space_policy_spec.rb, spec/policies/utility_hookup_policy_spec.rb
- https://github.com/zinc-collective/convene/issues/103
`Operator`s run the whole show, and have broad permissions, including being able to create/update/destroy `Neighborhood`, `Room`, `Space`, `Utility`, `Furniture`, etc.
It may make sense for them to by default do anything on any object; but I didn't want to do that yet.
=> `Operator`: a `Person` may be a `Neighborhood` `Operator`

Gemfile.lock
This gets rid of the following deprecation warning:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call
`DidYouMean.correct_error(error_name, spell_checker)' instead.
```
=> 🧹 `Neighborhood`: Update `bundler` gem

app/controllers/application_controller.rb
- https://github.com/zinc-collective/convene/issues/117
This is likely a premature optimization, but my inclination is that a `Person` will likely have fewer `Membership`s than a `Space` does; which means the index on `Membership#space_id` will likely require more compute to locate the particular `Membership` than the `Membership#person_id` index.
=> 🏎️ `Membership`: Find `current_membership` through `Person`, not `Space` 

spec/requests/rsvps_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/117
`rspec-rails` wants request specs to:
1. Be nested in folders by namespace, rather than route
2. Be named for their `Controller`
3. Use the `describe "#action"` syntax, rather than the path
4. Start `context` block descriptions with `when`, `with`, and `without`
=> 🧹 `Invitation`: Follow `rspec-rails` conventions for Request spec

.rubocop.yml
- See: https://github.com/varvet/pundit/tree/v2.3.0#linting-with-rubocop-rspec
Before: `273 files inspected, 235 offenses detected, 94 offenses autocorrectable`
After:  `273 files inspected, 213 offenses detected, 98 offenses autocorrectable`
=> 🧹 `Neighborhood`: Respect `pundit`s syntax, `rubocop-rspec`!

app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, db/migrate/20230302202459_marketplace_encrypt_order_delivery_address.rb, db/schema.rb, lib/tasks/release.rake
So, I totally didn't think about how delivery addresses are PII and probably should not be stored in plaintext! Womp. Womp. Womp.
Now they ain't!
We'll want to delete the `release:after_build` bits after a prod deploy.
=> 🔐 `Marketplace`: Encrypt `Order#delivery_address`!

app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, db/migrate/20230303201956_drop_marketplace_orders_delivery_address.rb, db/schema.rb
Merge immediately after https://github.com/zinc-collective/convene/pull/1175
=> 🔐 `Marketplace`: Step 3 of encrypting `delivery_address`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_policy.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/carts/_total.html.erb, app/furniture/marketplace/carts_controller.rb, app/furniture/marketplace/checkout.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/carts_controller_request_spec.rb
While collecting the address via Stripe was reasonable at the time, if we want to support dynamic pricing, we'll need the address ahead of time.
This will also (theoretically) allow us to let people know when they are outside of the `Distributor` delivery area.
https://user-images.githubusercontent.com/50284/222832192-12b8f715-b0d5-4d1e-bd09-9dfdcf8f9d9a.mp4
https://user-images.githubusercontent.com/50284/222587195-9b7b01e9-5fd1-4732-824f-663516c5c83e.mp4
=> ✨ `Marketplace`: Collect `Shopper`s Delivery Address before `Checkout`

app/views/spaces/new.html.erb, spec/requests/spaces_controller_request_spec.rb, spec/support/auth_helpers.rb
- https://github.com/zinc-collective/convene/pull/1161
- https://github.com/zinc-collective/convene/pull/1141
Deleting the `Client` was great! But when we merged the `Neighborhood` first-run PR, we still had the `Client#name` field; which no longer exists.
So now there's two tests for the `SpacesController#new` action:
- 1 to catch any errors in the happy-path request/response cycle
- 1 to make sure `Guest`s cant create a Space
=> 🐞 `Space`: Fix broken `SpacesController#new` action

app/views/furniture_placements/_new.html.erb
- Extracted from: https://github.com/zinc-collective/convene/pull/1083
- https://github.com/zinc-collective/convene/issues/74
=> 🧹 `Furniture`: use `FurniturePlacement#location` in forms

app/models/utility_hookup.rb, app/views/utility_hookups/_form.html.erb, app/views/utility_hookups/new.html.erb, config/breadcrumbs.rb
- Extracted from htps://github.com/zinc-collective/convene/pull/1083
This is mostly for consistency and to start to close out a piece of work I started a while back but never finished.
=> 🧹 `Utility`: Use `UtilityHookup#location` in forms

app/views/layouts/component_preview.html.erb, config/application.rb
This is an intermediary step before we look into `LookBook` or similar which:
1. Makes it possible to define component previews in `spec/components/previews`
2. Creates a basic layout for showing Components
=> 🛠️ `Component`: Set up `view_component` `Preview`s

app/components/application_component.rb, app/components/card_component.html.erb, app/components/card_component.rb, spec/components/previews/card_component_preview.rb
This:
1. Adds a `CardComponentPreview`
2. Sprouts an `ApplicationComponent` which we can start to massage into playing well with tailwind's class syntax
(Originally was in https://github.com/zinc-collective/convene/pull/1190)
=> 🛠️🧹 `Component`: Sprout `CardComponentPreview`

app/controllers/application_controller.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/product.rb, app/furniture/marketplace/routes.rb, app/furniture/marketplace/tax_rate.rb, app/furniture/marketplace/tax_rate_policy.rb, app/furniture/marketplace/tax_rates/_form.html.erb, app/furniture/marketplace/tax_rates/_tax_rate.html.erb, app/furniture/marketplace/tax_rates/edit.html.erb, app/furniture/marketplace/tax_rates/new.html.erb, app/furniture/marketplace/tax_rates_controller.rb, app/views/application/_number_field.html.erb, db/migrate/20230305005417_create_marketplace_tax_rates.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/tax_rates_controller_request_spec.rb
Slaps some `update` and `create` actions together for setting `TaxRate`s.
That said, I  don't know that an integer or a float is better, since I suppose there could be a partial tax? 
Also, I tried to set it up so tax rates applied across all spaces; but then I ran into some weirdness... if y'all have ideas happy to hear.
=> ✨ `Marketplace`: Create and Update `TaxRate`

app/furniture/marketplace/cart_policy.rb, app/furniture/marketplace/cart_product.rb, app/furniture/marketplace/cart_product_policy.rb, app/furniture/marketplace/checkout_policy.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/order_policy.rb, app/furniture/marketplace/policy.rb, app/furniture/marketplace/product_policy.rb, app/policies/application_policy.rb, spec/factories/furniture/marketplace.rb, spec/factories/marketplace/checkouts.rb, spec/furniture/marketplace/cart_policy_spec.rb, spec/furniture/marketplace/cart_product_policy_spec.rb, spec/furniture/marketplace/checkout_policy_spec.rb, spec/furniture/marketplace/marketplace_policy_spec.rb, spec/furniture/marketplace/order_policy_spec.rb, spec/furniture/marketplace/product_policy_spec.rb
Since we're getting close to running orders through, I figured it would make sense to flesh out the tests for the `Policy` objects in the `Marketplace` domain.
This:
- Sprouts a `Marketplace::Policy` class with the default permissions for objects.
- Gets rid of `ApplicationPolicy#person` for `ApplicationPolicy#current_person`.
=> 🧹🔐🛠️ `Marketplace`: Fully exercise `Policy` objects

app/furniture/marketplace/product.rb, app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/product_tax_rate.rb, app/furniture/marketplace/products/_form.html.erb, app/furniture/marketplace/products/_product.html.erb, app/furniture/marketplace/products/index.html.erb, app/furniture/marketplace/tax_rate.rb, app/views/application/_collection_check_boxes.html.erb, db/migrate/20230307031329_create_marketplace_product_tax_rates.rb, db/schema.rb, spec/furniture/marketplace/products_controller_request_spec.rb, spec/requests/spaces_controller_request_spec.rb
There's a bit of low-hanging 🌸, but I don't want to block on them. In particular:
- It would be nice if we had a well-styled `Component` or partial for the `collection_check_boxes` form helper, since right now the `input[type="checkbox"]` and the `label` for each option are stacked on top of each other. Nasteh!
- There's probably a way to show the tax rate amount with a humanized percentage when selecting options, but I didn't want to figure it out
https://user-images.githubusercontent.com/50284/223316859-7f5fdc90-ace7-43f1-a576-ca7d9a651f10.mp4
=> ✨🥔 `Marketplace`: Adding `TaxRate`s to `Product`s

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/stripe_accounts_controller.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
Fixes https://github.com/zinc-collective/convene/issues/1113
With this change:
=> 🐞 `Marketplace`: catch Stripe errors during account connect and show them to the end user

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_policy.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/order.rb, app/furniture/marketplace/order_received_mailer/notification.html.erb, db/schema.rb, spec/furniture/marketplace/carts_controller_request_spec.rb, spec/mailers/previews/marketplace/order_received_mailer_preview.rb
Shopper can add a contact Phone Number to their order during the Checkout flow and it displays in the order_received_mailer.
**mobile mode**
**mailer**
Co-authored-by: Dalton Pruitt <daltonrpruitt@users.noreply.github.com>
=> ✨ `Marketplace`: Collect `Order#contact_phone_number` prior to `Checkout`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_product.rb, app/furniture/marketplace/carts/_total.html.erb, app/furniture/marketplace/checkout.rb, spec/furniture/marketplace/cart_spec.rb
Whoooo! `TaxRate` gets calculated! And collected!
https://user-images.githubusercontent.com/50284/223901634-e876eafa-106a-4eea-9558-dd454f14fa12.mp4
=> ✨`Marketplace`: Collect Taxes for `Product`s with a `TaxRate` on `Checkout`

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/order_policy.rb, app/furniture/marketplace/orders/index.html.erb, app/furniture/marketplace/orders_controller.rb, app/furniture/marketplace/routes.rb, spec/furniture/marketplace/order_policy_spec.rb
`Neighbor`s can see all their past `Order`s! And `Member`s can see all the `Order`s for a given `Marketplace`
It would be lovely if someone would take the `_order` partial and turn it into a `ViewComponent` that looks v pretty, instead of this hideous table monster I spawned.
=> ✨🥔 `Marketplace`: `Shopper` and `Distributor` `Order` History

app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/ordered_product.rb, app/furniture/marketplace/ordered_products/_ordered_product.html.erb, app/furniture/marketplace/orders/_order.html.erb, spec/furniture/marketplace/order_spec.rb
The entire `Marketplace::Order` page is potato-tier, but at least it exists!
=> 🥔✨ `Marketplace`: Show `Order#tax_amount` on `Marketplace::Order#show`

.rubocop_todo.yml, spec/furniture/embedded_form_spec.rb, spec/furniture/journal/entries_request_spec.rb, spec/furniture/journal/entry_policy_spec.rb, spec/furniture/markdown_text_block_spec.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb, spec/furniture/marketplace/products_controller_request_spec.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb, spec/models/furniture_spec.rb, spec/requests/furnitures_controller_request_spec.rb
- https://github.com/zinc-collective/convene/pull/1209#discussion_r1133016759
I don't really like the direction this pushes specs, but I can live with it.
In particular, a single assert per request/response seems... excruciatingly slow.
But there are other mechanisms we can explore to mitigate that as it gets out of hand.
=> 🧹 `Furniture`: Appease the Fuzz

app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/marketplaces/_form.html.erb, app/furniture/marketplace/marketplaces_controller.rb, app/policies/utility_policy.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
Added a `Marketplace#delivery_window` attribute, which is a plain-old-string for now. It's going to quickly become insufficient, because we *may* need to do date and time crap at one point.
But "quickly" could mean "months from now!" sooooooo.
=> ✨ `Marketplace`: `Distributor` may set `Marketplace#delivery_window`

app/furniture/markdown_text_block.rb, app/furniture/marketplace/marketplace.rb, app/models/furniture.rb, app/views/furnitures/_furniture.html.erb, app/views/rooms/edit.html.erb
I noticed that the Marketplace was not showing the `edit` gear in the Room edit form, so this PR fixes that. This is not the most elegant code I've ever written, but it communicates the intent and works. If we like this approach, we can polish it to have better method naming, etc.
Also took the chance to improve the Room `edit` page look a bit.
=> `Furniture`: Add a way for furniture to signal they have their own controller, and add link to kind-specific `edit` from Room edit form

app/controllers/application_controller.rb
Piikup-Sandbox is experiencing some sadness because of policy issues it seems.
=> 🛠️ `Neighborhood`: Send Authorization errors to Sentry

app/furniture/marketplace/orders_controller.rb
There is another 😬 with our `Order` and `Cart` table being the same, as technically `Order#created_at` is the `Cart#created_at` which may not be when the order is placed...
But this at least makes it look less chaotic.
It would have been nice to get some tests but I didn't have time, since I need to run!
=> ✨ `Marketplace`: `Order#index` is ordered chronologically

app/furniture/marketplace/stripe_events_controller.rb, db/migrate/20230319173737_add_placed_at_to_marketplace_orders.rb, db/schema.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Currently the `Order` datetime is based off when the `Cart` was created and not when the `Order` was created.
This fixes that by setting `placed_at` for `Order` after the order is successfully created in Stripe.
note: The `Cart` is created when the Marketplace page is loaded.
=> Set `Order` datetime based off actual order creation

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/tax_rate_component.html.erb, app/furniture/marketplace/tax_rate_component.rb, app/furniture/marketplace/tax_rates/index.html.erb, app/furniture/marketplace/tax_rates_controller.rb, spec/components/previews/marketplace/tax_rate_component_preview.rb, spec/furniture/marketplace/tax_rates_controller_request_spec.rb
- https://github.com/zinc-collective/convene/pull/1222
In a previous commit, we had tidied up the `Markeplace#edit` screen quite a bit, but we had also removed the list of `TaxRate`s on that screen.
This sprouts a `TaxRate#index` screen, that is linked to from `Marketplace#edit`, so that `Member`s of a `Space` may set the `TaxRate` for their Clients.
=> 🥔✨ `Marketplace`: Introduce `TaxRate#index`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_policy.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/locales/en.yml, db/migrate/20230320190449_add_delivery_window_to_marketplace_orders.rb, db/schema.rb, spec/furniture/marketplace/carts_controller_request_spec.rb
This is potato tier to be sure, but it makes it possible to say when they want to be delivered.
=> ✨🥔 `Marketplace`: `Shopper` sets `Delivery Window`

app/furniture/marketplace/tax_rates/_form.html.erb
While demoing with April, I learned that the tax rate for the Oakland City tax is 10.75%, so we need to be a little more precise.
=> ✨🥗 `Marketplace`: `TaxRate#tax_rate` can be set to the 100ths place

app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, db/migrate/20230320210304_encrypt_marketplace_order_contact_email.rb, db/schema.rb
- https://github.com/ankane/lockbox#migrating-existing-data
We already have a `Lockbox.migrate(Order)` in the post-release script; which I forgot to take out when I was migrating the other stuff.
Also, thanks to @KellyAH for suggesting this a while back and I punted on it until now but now I did it! Yah!
=> 🛠️ `Marketplace`: Encrypt `Order#contact_email`

app/furniture/marketplace/stripe_events_controller.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1236
It looks like the `PaymentIntent` shape changes depending on what features we request. In particular, `charges` is sometimes absent and since we're not collecting the address from them on `Checkout` it's not included.
It may be worth taking time to write a shot-across-the-bow feature test that:
1. Sets up Stripe in a Space
2. Sets up the Marketplace in a Space
3. Places an Order
4. Confirms the Order was received and emails went out
But that also sounds hard.
=> 🐞 `Marketplace`: `StripeEvent#create` was failing

app/components/card_component.html.erb, app/views/layouts/_header.html.erb, app/views/memberships/show.html.erb, config/locales/invitation/en.yml
This PR improves the look of the "Account" placeholder for logged-in users.
This also tweaks the styling for the Card Component to give it a little bit more breathing room.
=> 🌸 `Neighborhood`: Tidy up "Account" page

app/furniture/marketplace/cart.rb, app/furniture/marketplace/carts/_cart.html.erb, config/locales/en.yml, spec/furniture/marketplace/carts_controller_request_spec.rb
We probably want to do something a bit smerter with like, an `ActiveRecord::Attribute`, but for now this lets us handle nil or unparsed values more effectively
=> 🥗 `Marketplace`: Capture `Cart#delivery_window` as a DateTime

app/furniture/marketplace/marketplace.rb, app/models/furniture.rb, spec/models/furniture_spec.rb
This is a proposal for tightening our manually-added "settings-backed attribute" methods. What do y'all think?
Also maybe this is partially duplicative with the [existing `write_attribute` method](https://github.com/zinc-collective/convene/blob/main/app/models/furniture.rb#L49-L53)? Maybe a better approach is to add a `read_attribute`? (if that exists?)
=> 🧹 `Furniture`: Add a facility to add attribute-like fields backed by `settings`

app/assets/stylesheets/components/form.scss
We forgot to style date-time inputs in the same way as all the other inputs. This PR fixes that.
=> 🌸 `Neighborhood`: Apply standard form input styling to date-time input

app/furniture/embedded_form.rb, app/furniture/livestream.rb, app/furniture/markdown_text_block.rb, app/furniture/marketplace/marketplace.rb, app/models/furniture.rb, spec/models/furniture_spec.rb
As a follow-up to https://github.com/zinc-collective/convene/pull/1254, this PR:
* updates the `Furniture#setting` method to only convert the setting name to string once
* extends `Furniture#setting` to allow setting a default value
* updates all existing Furniture to use the `Furniture#setting` method to define their settings
=> 🧹 `Furniture`: Improve `Furniture#setting` helper, and migrate all Furniture kinds to use it

yarn.lock
Latest Heroku auto-deploy failed with the errors:
```
----> Installing dependencies
Installing node modules (yarn.lock)
yarn install v1.22.19
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
!     Outdated Yarn lockfile
Your application contains a Yarn lockfile (yarn.lock) which does not
match the dependencies in package.json. This can happen if you use npm
to install or update a dependency instead of Yarn.
Please run the following command in your application directory and check
in the new yarn.lock file:
$ yarn install
$ git add yarn.lock
$ git commit -m "Updated Yarn lockfile"
$ git push heroku main
```
I think I …
=> Update yarn.lock file to fix broken Heroku build

Gemfile, Gemfile.lock, app/furniture/marketplace/cart.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/settings.rb, app/models/furniture.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/marketplace_spec.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb, spec/rails_helper.rb
Fixes https://github.com/zinc-collective/convene/issues/1265 by using `StoreModel` to model `Marketplace#settings` with a bit more structure, including types.
=> 🐞 `Marketplace`: fix `delivery_window` type issues by giving more structure (and types!) to `Marketplace#settings`

app/furniture/marketplace/product.rb, spec/furniture/marketplace/product_spec.rb
- https://github.com/zinc-collective/convene/issues/1272
Forgot a `dependent: :destroy`
=> 🐞 `Marketplace`: Fix deleting `Product` with `TaxRate`

app/policies/membership_policy.rb, spec/policies/membership_policy_spec.rb
- https://github.com/zinc-collective/convene/issues/1267
We had written some logic to be like "Don't Revoke!" but that is causing exceptions in cases where we double-tap buttons and such
=> 🐞 `Member`s: You can double destroy it's fine

app/models/furniture.rb, app/models/room.rb, app/models/space.rb, spec/models/furniture_spec.rb, spec/models/room_spec.rb, spec/models/space_spec.rb
- https://github.com/zinc-collective/convene/issues/832
As I was working to onboard Piikup, I discovered I couldn't really write an easy script to merge into a space since I didn't have the associations together.
Now they're super tight! Yyyaaaaaaah!
=> 🧹 `Space`, `Furniture`, and `Room`: Fill in missing associations

app/assets/stylesheets/components/icons.scss, app/components/card_component.html.erb, app/views/rooms/_room.html.erb, app/views/spaces/_room_card.html.erb
This PR updates our Room Cards to:
* look a bit more button-y
* have more space
* better accommodate long room names
Also:
* added more space to standard card component
* tweaked the space around the main content container
=> 🌸 `Components`: improve room card styling

app/views/layouts/_hotjar.html.erb, app/views/layouts/application.html.erb
Addresses https://github.com/zinc-collective/convene/issues/1279
We had discussed enabling this only for space owners, but thinking more about it, I feel like it would be nice to be able to see guests trying to place a marketplace order as well, so for now I enabled this for all users.
=> 🛠️ `Neighborhood`: Add Hotjar session tracking and enable it for all users

app/javascript/application.js, app/javascript/sentry.js, app/views/layouts/application.html.erb, package.json, yarn.lock
Resolves https://github.com/zinc-collective/convene/issues/1278
I have not bothered setting up the whole webpack sourcemap integration, because it seems like a pain and also because maybe we'll move away from webpack to import-maps or js-bundling soon-ish. This makes the error report less detailed, so maybe it is not worth it adding this in that case, but I think it might still be helpful to at least see that we have an error.
Looks like this in Sentry:
https://zinc-collective.sentry.io/issues/4057031271/?project=6052513&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
=> 🛠️ `Neighborhood`: Report browser JavaScritp errors to Sentry

app/components/button_component.rb
- https://turbo.hotwired.dev/handbook/streams#streaming-from-http-responses
It turns out that `Turbo` only does turbo-streams when `PUT`/`POST`/`DELETE` are the request methods.
If we want to make `GET` requests use the `turbo-stream` request type, we need to specify it in the HTML output, i.e. `<a href="..." data-turbo-stream=true>`
I wasn't sure if this should be default behavior or not, so I leaned towards making it default to not 🤷
=> 🛠️ `Component`: `ButtonComponent` supports `GET` Turbo Streams

.rubocop_todo.yml, app/models/room.rb, app/policies/room_policy.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb, spec/models/room_spec.rb, spec/policies/room_policy_spec.rb
Fixes https://github.com/zinc-collective/convene/issues/1295
=> 🐛🔨 `Neighborhood`: Update Room policy scope to not show inaccessible rooms to users

spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
A continuation of https://github.com/zinc-collective/convene/pull/1255
- add `assert_select` to tests to make assertions about what the page will display. 
-  add assertions about how `DeliveryArea` controller #create changes the underlying data
=> modify `DeliveryArea` controller tests

app/models/room.rb, app/views/application/_radio_group.html.erb, app/views/rooms/_form.html.erb, db/migrate/20230403013014_add_default_publicity.rb, db/schema.rb, spec/models/room_spec.rb
As a follow-up on https://github.com/zinc-collective/convene/pull/1300, this PR replaces the visibility and access level select drop-downs in the Room edit form with radio groups.
My goal is to make the available options and current setting clearer.
I would like to soon add an "explanation text" to each of these options. I was experimenting with using [Tailwind's `peer/...` and `peer/...checked` classes](https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-peers) and I couldn't get them working reliably, so I've given up on that for now. But I'll be back.
I also:
* added a database-level default for the `publicity_level`
* converted the access and publicity levels to Rails enums, so that we can get the scopes and predicate methods and validations for free
=> 🌸 `Neighborhood`: Improve clarity of Room publicity and access level options

app/furniture/marketplace/cart.rb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/order.rb
- Fixes https://github.com/zinc-collective/convene/issues/1294
- Extracted from https://github.com/zinc-collective/convene/pull/1292
I wrote a unit test on the model to prove the data was being dropped; then fixed the bug, then deleted the test since there was no longer custom code on the model...
Also, the request specs in
https://github.com/zinc-collective/convene/pull/1292 cover this as well.
=> 🐞🔨 `Marketplace`: Stop dropping `Order#contact_email`

app/furniture/marketplace/marketplaces/edit.html.erb
A continuation of https://github.com/zinc-collective/convene/pull/1255
- add link on Configure Marketplace page so users can access the Delivery Areas index page. Currently the user needs to directly go to the URL e.g. `http://127.0.0.1:3000/spaces/system-test/rooms/listed-room-1/marketplaces/5be4d162-da4f-4ea8-9a15-808ba02e9447/delivery_areas`
------
Note: I tried and failed to Display configuration links in list format on the Configure Marketplace page to try to make them look neater. And to fix the links displaying squished together on wide screens.
**widescreen**
**Mobile**
**widescreen**
**Mobile** - **Oops I broke mobile mode view** 😱
=> Add `DeliveryArea#index` link to the Configure Marketplace page

app/models/authentication_method.rb, app/models/invitation.rb, spec/models/authentication_method_spec.rb, spec/models/invitation_spec.rb
- https://github.com/zinc-collective/convene/issues/1310
- https://github.com/zinc-collective/convene/issues/1311
So, the `AuthenticationMethodcontact_location` field is case insensitive from a *validation* perspective, but not from an assignment or lookup perspective.
So when someone had signed in with `Bob@example.com`, then tried to sign in as `bob@example.com` it had a sad day.
Similarly, `Invitation#email`
=> `Authentication`: Downcase email addresses

app/models/operator/route_constraint.rb, config/routes.rb, spec/models/operator/route_constraint_spec.rb
We have some sad background jobs in the queue, this will let me purge the heretics.
=> 🛠️ `Neighborhood`: Expose `sidekiq-web` ui to Operators

app/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/marketplace_spec.rb
When pairing with @KellyAH, it turned out she couldn't get rid  of `Marketplace`s in her local database because our `delivery_areas` stick around forever.
=> 🥗 `Marketplace`: Destroy `DeliveryArea` when destroying `Marketplace`

app/controllers/utilities_controller.rb, app/views/spaces/edit.html.erb, app/views/utilities/_form.html.erb, app/views/utilities/edit.html.erb, config/breadcrumbs.rb, config/locales/icon/en.yml, config/locales/utilities/en.yml, spec/requests/utilities_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/252
I noticed my local Space had two `Stripe` utilities and I wanted to get rid of one but I couldn't because the feature didn't exist.
So now it does.
I also ditched the `Utility` form from the `Space#edit` page and made the list of utilities look more like the list of furniture, with edit and trash buttons on the right.
=> 🧹🥔✨ `Utilities`: Tidy up `#edit` and `#destroy` use-cases

app/furniture/marketplace/cart/deliveries/_delivery.html.erb, app/furniture/marketplace/cart/deliveries/_form.html.erb, app/furniture/marketplace/cart/delivery.rb, app/furniture/marketplace/cart/delivery/edit_button_component.rb, app/furniture/marketplace/cart/delivery_policy.rb, app/furniture/marketplace/delivery_areas/_delivery_area.html.erb, db/migrate/20230408033925_carts_have_delivery_area.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb, spec/furniture/marketplace/cart/delivery_policy_spec.rb, spec/furniture/marketplace/cart/delivery_spec.rb
This also gets rid of some of the cruft that has accumulated at the top of the `Marketplace`, but the interaction design could use a much more thoughful eye.
After this, we'll probably want to connect the `DeliveryArea#price` to the `Order#delivery_fee`!
=> 🌸🥔✨ `Marketplace`: `Shopper` chooses `DeliveryArea` for their `Order`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart/delivery.rb, app/furniture/marketplace/delivery.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/delivery_spec.rb
Now the pricing reflects the delivery area when the Marketplace and Cart have them! Fancy!
I feel like this is a reasonable amount of test coverage for this change, but if we want to add `request` or `component` specs or something I could be persuaded...
=> 🧹🥗🥔 `Marketplace`: Use `DeliveryArea#price` to calculate `Cart#price_total`

app/furniture/marketplace/delivery_area.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/order/email_receipt_component.html.erb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/delivery_area_spec.rb, spec/furniture/marketplace/delivery_spec.rb, spec/furniture/marketplace/order/email_receipt_component_spec.rb, spec/furniture/marketplace/order_spec.rb
- https://github.com/zinc-collective/convene/issues/1325
I didn't use the `marketplace_order, :full` factory outside of the `Order::PlacedMailerPreview` and `Order::ReceivedMailerPreview`; and apparently had flubbed the implementation; so that was not working...
So I fixed it and used it in the `Order::EmailReceiptComponent` spec to test the `Order#delivery_area`
I also noticed we didn't wire in associations between the `Marketplace::DeliveryArea` into the `Marketplace::Cart` and `Marketplace::Order` so I added some specs for those.
=> 🥗🧹🥔✨ `Marketplace`: Show `DeliveryArea` in `Order::EmailReceiptComponent`

app/components/card_component.html.erb, tailwind.config.cjs
The `p-6` felt like just a bit too much on mobile screens; so I made it `p-4` and then when we get to tablet size it's `p-6`.
=> 🌸 `Components`: Reduce `Card` padding on small screens

app/furniture/marketplace/delivery.rb, app/furniture/marketplace/locales/en.yml, app/views/application/_error.html.erb, spec/furniture/marketplace/cart/delivery_spec.rb
This PR extends our `errors` partial to show association validation errors on the association foreign key field. This removes the need to have a duplicate presence validation on non-optional `belongs_to` relationships.
A more full solution is possible by patching ActionView::Helpers::ActiveModelInstanceTag, but it also would be more complex and doesn't seem worth it at the moment. If/when https://github.com/rails/rails/issues/28772 is resolved, we won't need this workaround anymore.
For an example of the more complete patch, see: https://web.archive.org/web/20190605211237/http://iada.nl/blog/article/rails-tip-display-association-validation-errors-fields
After this change, form errors look like so:
=> 🛠️ `Neighborhood`: Add error field workaround to display association errors correctly on forms

tailwind.config.cjs
Apparenltly our tailwind config wasn't detecting classes in furniture's `_component.rb` files. Womp. Womp.
=> 🛠️ `Components`: Tailwind Look for classes in `Furniture`

app/components/button_component.html.erb, app/components/button_component.rb, app/furniture/marketplace/cart/deliveries/_delivery.html.erb, app/furniture/marketplace/cart/delivery/edit_button_component.rb, app/furniture/marketplace/carts/_cart.html.erb, tailwind.config.cjs
**Changes**
- 🛠️ `Components`: Makes sure Tailwind notices `Furniture`'s `Component` files
- 🧹 `Components` I'm not sure if this is the right path or not but it decouples our `ButtonComponent` from the `button.scss` file, and makes it a bit easier to override the defaults for how we present buttons.
- 🌸 Gets rid of the extra `Marketplace::Cart::Delivery::EditButtonComponent` that hangs out underneath the cart
- 🌸 Tailors the `Marketplace::Cart::Delivery::EditButtonComponent` better for smaller screens.
=> 🌸🛠️🧹 `Marketplace`: Tidy up `Marketplace#show`

app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/products/_form.html.erb, app/furniture/marketplace/products/_product.html.erb, app/furniture/marketplace/products/index.html.erb, config/locales/en.yml
- https://github.com/zinc-collective/convene/pull/1338
I think I like the consistency of using the `icons.edit` / `edit.link_to` and `icons.destroy` / destroy.link_to` in the footer of the card, so there are words with the icons by default.
=> 🌸`Marketplace`: Bring `Product` and `TaxRate` UI closer

app/furniture/marketplace/tax_rate.rb, app/furniture/marketplace/tax_rate_policy.rb, spec/furniture/marketplace/tax_rate_spec.rb
This makes the relationships to `space` a bit easier to access from a given tax rate, as well as ensures we have good validations.
=> 🥗🛠️ `Marketplace`: Add associations and validations to `TaxRate`

app/furniture/marketplace/tax_rates_controller.rb, spec/furniture/marketplace/tax_rates_controller_request_spec.rb
- https://github.com/zinc-collective/convene/pull/1338
I don't know why the get actions and passing `as` do not play nicely together, but it is annoying as heck.
=> ✨🥗 `Marketplace`: `TaxRate` actions support Turbo

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml
continuation of https://github.com/zinc-collective/convene/pull/1255
-----
Refactor Edit a Delivery Area link to live in en.yml as requested in https://github.com/zinc-collective/convene/pull/1303#discussion_r1161900092
**before**
**after**
=> 🧹 `Marketplace`: The link to `DeliveryArea#edit` is translatable!

Gemfile, Gemfile.lock, config/initializers/strong_migrations.rb
- https://github.com/zinc-collective/convene/issues/1177
This change is part of an effort to add guard rails for devs writing migrations and catch *unsafe* and *illegal* operations on the database.
NOTE: There are other types of "bad" migrations that will not be caught by this gem. For example, referencing an Active Record model to execute DML. For those cases we should consider other static analysis methods like rubocop.
=> 🛠 `Neighborhood`: Adds strong_migrations gem 

app/furniture/marketplace/products/_product.html.erb, app/furniture/marketplace/tax_rate_component.rb
I noticed when deleting a `Marketplace::Product` or `Marketplace::TaxRate`, there was no "are you sure?" confirmation modal. This could lead to customer's accidentally deleting a product or tax rate.
- add deletion confirmation modal to `Marketplace::Product`.
- add deletion confirmation modal to `Marketplace::TaxRate`.
- apply new button component to `Marketplace::TaxRate` edit and delete buttons.
**before**
**after**
=> 🌸✨ `Marketplace`: Require confirmation before deleting `Product`s and `TaxRate`s

app/furniture/marketplace/tax_rates/_tax_rate.html.erb, spec/support/turbo.rb
This also makes our `have_rendered_turbo_stream` matcher play more nicely with `remove` actions.
Co-authored-by: Kelly Hong <KellyAH@users.noreply.github.com
=> 🧹`Marketplace`: Remove unused `TaxRate` partial!

app/components/application_component.rb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/tax_rate_component.rb
-  https://github.com/zinc-collective/convene/issues/1187
This gives us a little tiny factory method so it's easy to drop an `edit_button` into a page and have it look and feel very much like all our edit buttons.
I don't know that `ApplicationComponent` is the right target for pulling this up. Part of me wants a `ModelComponent` or something that inherits from `ApplicationComponent` and is used in cases where the component is for a particular `Model`, but I'm also available to wait on that until we start seeing more stuff that wants to be grouped into such a `Component`.
=> 🧹`Components`: Pull `edit_button` up into `ApplicationComponent`

app/lib/space_routes.rb, app/models/space.rb, app/models/space/agreement.rb, db/migrate/20230414040205_create_agreements.rb, db/schema.rb, spec/factories/space/agreement.rb, spec/models/space/agreement_spec.rb, spec/models/space_spec.rb
So, I don't really know what each Space's Terms of Service, Privacy Policy, or Content Policy will be.
I would love for us to offer a set of different terms of service tailored for different use-cases; but for now I think it's probably best to put the responsibility on the Space Members to make sure they have the appropriate agreements in place.
It's kind of a weird position to take, and not one I would advocate for if we had a space ~$30k to invest in legal, but we don't and I'm not sure if we have any capacity to do the work ourselves or find someone who can do it pro-bono.
So we have a very tiny `Agreement` Model which `Space`s can have many of, and maybe I'll even get to adding a `controller` with a `#show` action and finding a …
=> 🥔🥗✨`Space`: have `Agreement`s for "Terms of Service" etc.

.rubocop_todo.yml, spec/requests/invitations_controller_request_spec.rb, spec/requests/invitations_request_spec.rb
- https://github.com/zinc-collective/convene/issues/117
I noticed a leftover from when I had been exploring organizing our request specs based upon path.
Now this aligns with the `rubocop-rspec` defaults! Wooo!!!
=> 🧹 `Space`: `Invitation`s request spec lives where it should

app/views/spaces/edit.html.erb, config/locales/agreement/en.yml
This doesn't link to the Agreements, but it gives me a hook to add in the `#new`, `#edit` and `#destroy` bits in further PRs.
=> 🥔✨ `Agreements`: List `Agremeent`s  on `Space#edit`

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/views/layouts/application.html.erb, app/views/space/agreements/new.html.erb, app/views/spaces/edit.html.erb, config/breadcrumbs.rb, config/locales/agreement/en.yml, spec/requests/space/agreements_controller_request_spec.rb
This builds on the `Agreements#create` PR by exposing a UI for hitting that endpoint via a Browser.
Note: I updated the footer because `space.agreements.new` creates an un-persisted instance in the `space.agreements` collection.
=> 🥗🥔✨ `Agreement`: Expose path to `AgreementsController#new`

app/furniture/marketplace/cart/delivery_expectations_component.html.erb, app/furniture/marketplace/cart/delivery_expectations_component.rb, app/furniture/marketplace/carts/_cart.html.erb, config/locales/en.yml, spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb
As we were beginning to implement how we communicate the different expectations based on delivery area, we noticed there were not many tests on the current behavior; and that chunk of behavior had many many many permutations that were meaningful.
So we took some time to pull out a `DeliveryExpectationsComponent` that can take care of handling those permutations, and start to test them.
There is some minor wording improvements included here, specifically because we noticed things didn't always make a ton of sense as we added those tests; so it *does* include a bit of behavior changes.
=> 🥗🥔🧹✨ `Marketplace`: Test how we communicate `DeliveryExpectations`

app/furniture/marketplace/delivery/windows/_window.html.erb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/delivery_area_component.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/delivery_area_component_spec.rb
We added some tests to the `DeliveryAreaComponent` to make sure it looks reasonable in each use-case:
- `#delivery_window` with no data
- `#delivery window` with a string
- `#order_by` with no data
- `#order_by` with a string
We also included "by" in the `_window.html.erb` partial so that people don't have to write it in their `order_by`.
=> 🥗🥔✨ `Marketplace`: Show `DeliveryArea`'s `#order_by` and `#delivery_window`

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/policies/space/agreement_policy.rb, app/views/layouts/application.html.erb, app/views/space/agreements/new.html.erb, app/views/spaces/edit.html.erb, config/breadcrumbs.rb, config/locales/agreement/en.yml, spec/requests/space/agreements_controller_request_spec.rb
This is only for the classic HTML Request <=> Response Cycle. I realized I probably want to do the `#index` Routes before `#create`, or at least get started on the bits to expose adding an `Agreement` in the `Spaces#edit` page.
=> 🥗🥔✨ `Agreements`: can be `created`!

app/furniture/marketplace/delivery/windows/_window.html.erb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/delivery_area_policy.rb, app/furniture/marketplace/delivery_areas/_form.html.erb, app/furniture/marketplace/delivery_areas_controller.rb, app/furniture/marketplace/locales/en.yml, db/migrate/20230416172045_add_order_by_and_delivery_window_to_marketplace_delivery_areas.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/delivery_area_component_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
In order to support different timing for different `DeliveryArea`s, we've given them `delivery_window` and `order_by` fields.
These fields will be used to communicate on the `Cart#show` and `Order#show` screens what the timing expectations are for particular orders.
Example:
- Catering orders for Lions Dance Cafe can be placed any time and delivered anytime, but
- Dinner orders must be placed the same day by 3pm
=> 🥗🥔✨ `Marketplace`: add `order_by` and `delivery_window` to `DeliveryArea`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart/deliveries/_delivery.html.erb, app/furniture/marketplace/cart/deliveries/_form.html.erb, app/furniture/marketplace/cart/deliveries_controller.rb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/delivery.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplaces/_marketplace.html.erb, spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
This can use a lot more UI / visual love, but at least it is a sketch of a slightly improved experience: when we are missing delivery details, instead of just hiding the "Checkout" button, show a primary button asking for the delivery details.
https://user-images.githubusercontent.com/6729309/233237901-3c4f0bf9-1c56-417b-9be0-8c53686ac1a3.mp4
=> ✨ `Marketplace`: ask for missing delivery details to proceed to checkout

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart/deliveries/_form.html.erb, app/furniture/marketplace/cart/delivery.rb, app/furniture/marketplace/cart/delivery_policy.rb, app/furniture/marketplace/delivery.rb, app/furniture/marketplace/delivery_area.rb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/order.rb, app/furniture/marketplace/order/email_receipt_component.html.erb, db/migrate/20230427003441_rename_marketplace_orders_delivery_window.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb, spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb, spec/furniture/marketplace/cart/delivery_policy_spec.rb, spec/furniture/marketplace/cart/delivery_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb, spec/furniture/marketplace/delivery_spec.rb, spec/furniture/marketplace/order/email_receipt_component_spec.rb
* https://github.com/zinc-collective/convene/issues/1185
First step of several towards simplifying how we store and handle the "delivery window" on a Marketplace Order.
=> 🧹 `Marketplace`: Rename `marketplace_cart#delivery_window` to `delivery_notes`

spec/factories/furniture/marketplace.rb
`Faker` has stopped supporting `safe_email` and expect to drop it completely :soon:, so this gets rid of where we were using it.
=> 🧹 `Marketplace`: Fix `Faker` deprecation warning

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/marketplace_spec.rb
We could probably include better messaging, but for now `Marketplace`'s don't show up until they are configured enough to actually take orders.
=> ✨ `Marketplace`: Don't show to `Shopper`s unless it's ready

app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/delivery.rb, spec/furniture/marketplace/checkout_spec.rb
This is wildly insufficient, but it gets us to the point where we're able to test that the way we're calling `Stripe::Checkout::Session.create` is at least *close* to what it's supposed to be called with.
It would be far better to get a `spec/furniture/marketplace/system` that actually hits Stripe...
=> 🐞 `Marketplace`: Don't explode on `Checkout`

app/controllers/application_controller.rb, app/furniture/marketplace/cart_products/_cart_product.html.erb
A quick insertion of the photos into the cart view. We probably should do a broader redesign pass on the `Cart` UI :soon: but this seems decent enough?
=> 🥔✨ `Marketplace`: Show `Product::Photo` in `Cart`

app/furniture/marketplace/cart_products/_cart_product.html.erb, app/furniture/marketplace/product_component.html.erb, app/furniture/marketplace/products/_form.html.erb
* https://github.com/zinc-collective/convene/issues/1428
I feel like 500x500 can easily overwhelm the page, so I'm limiting the display size further. I picked this size based on some comparisons for other similar apps:
Yelp:
Instacart:
=> `Marketplace`: Further limit display size of `Product` photos

app/assets/stylesheets/base/typography.scss
Fix the "Add Agreement +" button overlapping agreement text on the `Spaces` edit page.
space.agreements.help_text on the `Spaces` `edit` page.
⚠️ **Warning**: This change could the layout of other elements on other pages that CSS &:last-of-type also applies too. But it's such a small change, it might not have a detrimental affect.
**Before**
**After**
=> 🌸 `Spaces`: Prevent Add `Agreement` button from overlapping

bin/test-changed, bin/test-changed-ruby
I could probably start doing `bin/rspec $(bin/list-changed-files | grep "_spec\.rb")` instead of sprouting a script...
But I like little scripts and I cannot lie.
=> 🛠️ `Neighborhood`: Microscript to run the changed tests

app/views/layouts/application.html.erb, app/views/spaces/edit.html.erb, config/locales/room/en.yml
https://github.com/zinc-collective/convene/issues/1472
Replace "Room" with "Section" in customer facing UI.
**Rooms List Page**
**create room form**
**edit room form**
Confirmed pages render on local with text changes.
Can create and edit a room/section.
🐛 cannot Delete a room/section
=> [#1472] Replace "Room" with "Section"

app/views/rooms/edit.html.erb, config/locales/furniture/en.yml, config/locales/room/en.yml
https://github.com/zinc-collective/convene/issues/1472
Replace `Furniture` with `Gizmo` and `Gizmos` in customer facing UI.
**furniture list page**
**update message**
**remove button**
**delete prompt modal**
Confirmed pages render on local with text changes.
Can create, edit and delete Furniture.
=> Replace `Furniture` with `Gizmo`

lib/tasks/release.rake
Since they're all attached and will be into the future we don't need to migrate
them on every deploy anymore.
=> `Marketplace`: Don't need `TaxRate` onto Bazaar every deploy

app/furniture/marketplace/marketplaces/show.html.erb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
- Pulled out of https://github.com/zinc-collective/convene/pull/1487
Missed a bit in my rename; so I added some tests to the endpoint to catch it
in the future.
=> 🥗 `Marketplace`: Quick spec for the `Marketplaces#show` endpoint

spec/furniture/marketplace/cart_product_component_spec.rb
- https://github.com/zinc-collective/convene/issues/1430
- Pulled from https://github.com/libvips/ruby-vips/blob/master/.github/workflows/test.yml
I'm not particularly pleased with this, but I didn't find a github action; and I'm not entirely sure why the test passes locally but not on CI.
=> `Marketplace`: Assert the `CartProduct` shows the `Product::Photo`

app/controllers/application_controller.rb, spec/requests/spaces_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1473
Visitors are redirected to https if they visit a space that Enforces SSL using HTTP
=> ✨ [#1473] `Space`: redirect Visitors to https if `Space` Enforces SSL

app/controllers/furnitures_controller.rb, app/models/furniture.rb, app/views/furnitures/_new.html.erb, app/views/rooms/edit.html.erb, config/locales/furniture/en.yml, config/locales/room/en.yml, spec/factories/furniture/journal.rb
* https://github.com/zinc-collective/convene/issues/1155
This PR:
* unifies the Gizmos section into one card
* changes the dropdown to require people to select a furniture kind, so that they don't add things by accident
* enforces that a `furniture_kind` value is set, and shows the error in the UI if there is one
It would be nice to improve this further so that it is not possible to submit the "add new" form without a valid type selected.
=> Improve "Gizmos" section of the Section (aka `room`) configuration view

app/mailers/space_invitation_mailer.rb, spec/mailers/space_invitation_mailer_spec.rb
- https://github.com/zinc-collective/convene/issues/1515
Turns out, when I had suggested we drop the Convene bits from the email I did not think about what that would mean from the email address perspective.
While I don't have a Github issue yet for Space's being able to send email from their domain; I think that would be a good thing for us to support at some point so our clients branding stays front and center and we stay in the background.
In the meantime, since it's coming from a convene domain, we should probably include the convene support name as well.
=> 🔨🐞 `Invitations`: are deliverable again since they come from a valid Email Address

app/components/neighborhood/link_component.rb, app/models/neighborhood.rb, app/views/layouts/application.html.erb, spec/components/neighborhood/link_component_spec.rb
- https://github.com/zinc-collective/convene/issues/74
I noticed that the `Convene` link in the footer was always to the current `root_url`, which will be the `Space` when visiting the `Space` via a `Domain`.
This shifts it to use the `APP_ROOT_URL`, and allows `Operator`s to configure the Neighborhood name and Tagline.
=> 🥗🔨🐞 `Neighborhood`: Footer links to the Neighborhood URL

app/furniture/marketplace/cart_product_component.html.erb
Depending on device bandwidth, even 150x150 `Product::Photo`s can
take a quarter to a half second to load.
When the photo does not have a set height; this results in the page
re-flowing as the photo loads in.
- Add several `Products` with a `Product::Photo` to a `Marketplace`
- Throttle your network connection to 2g (Firefox DevTools can do this)
- Visit the `Marketplace`
- **Before:** `Product`s would "bump" down the page as the photos load.
- **After:** `Product`s stay in the same dang place, even as the photos load
https://github.com/zinc-collective/convene/assets/50284/d848e44f-8c2a-4745-8bd0-7c5990e7ec38
https://github.com/zinc-collective/convene/assets/50284/cfbd6b2f-9559 …
=> 🌸 `Marketplace`: `Product::Photos` don't reflow the page

.rubocop_todo.yml, app/models/person.rb, app/models/room.rb, app/models/space.rb, spec/models/person_spec.rb, spec/models/room_spec.rb, spec/models/space_spec.rb
- https://github.com/zinc-collective/convene/issues/1536
- https://zinc-collective.sentry.io/issues/4200863641/?project=6052513&referrer=github_integration
`destroy_async` and foreign keys don't play particularly well together, it appears.
This should make it so if we can't destroy a particular `Space`, `Room`, `Person`, etc. it will at least tell us sooner rather than later.
I took the time to bundle in some linter fixes with the files I changed to prevent the error from re-occuring.
=> 🧹 Eliminate `dependent: :destroy_async`

app/mailers/application_mailer.rb, app/mailers/space_invitation_mailer.rb, config/environments/production.rb, spec/mailers/space_invitation_mailer_spec.rb
* https://github.com/zinc-collective/convene/issues/1518
Also tightened up an email spec and unified reading the `EMAIL_DEFAULT_FROM` env varialbe to one location.
I am not 100% certain of the behavior of `raise_delivery_errors`, but if it gets noisy (e.g. if it ends up throwing exceptions for all undeliverable addresses), we can refine this by adding a `rescue_from` to `ApplicationMailer` to report to Sentry only the errors that we can do something about.
=> 🛠️ `Neighborhood`: Raise exceptions on email delivery errors

docs/deployment.md
First steps to having actual deployment documentation. 
- #1449
I was not able to go through this process exactly due to not wanting to set up my personal credit card yet (since I can't link to an actual fork of convene without having my personal account fully set up), but I did include a link to the contact-us page of zinc for the case that people run into issues.
Feedback welcome, of course!
=> 📝  `Operators` : Add steps/discussion for GitHub->Heroku deployment

CONTRIBUTING.md, README.md, features/boops.feature, features/furniture.feature, features/furniture/spotlight.feature.md, features/membership-and-ownership.feature, features/navigate-between-convene-and-other-systems.feature, features/rooms.feature, features/support/parameter-types/README.md, features/utilities.feature
Change Ana [reccomended](https://github.com/zinc-collective/convene/issues/1472#issuecomment-1595647326) for [discussion](https://github.com/zinc-collective/convene/issues/1472#issuecomment-1595616304)  
- add note at the top of each doc mentioning that `Furniture` has been renamed to `Gizmo`
-  add note at the top mentioning that `Room` has been renamed to `Section`
=> docs: add note about renames of Room and Furniture

app/views/spaces/edit.html.erb, config/locales/space/en.yml
- For https://github.com/zinc-collective/convene/issues/1585
- Add help text to the Space config page when a Space is missing sections, an entrance and memberships.
=> ✨ Space config displays help text

.gitignore
I realized that `.env` is used in every environment (`production`, `test` and `development`); which means that the ActionMailer test deliveries ... actually go all the way through to maildev!
Which was not ideal.
=> `Contributor`: override .env.development

app/assets/stylesheets/components/button.scss, app/components/button_component.rb, app/views/furnitures/_form.html.erb, app/views/furnitures/_furniture.html.erb, spec/system/furniture_spec.rb
- https://github.com/zinc-collective/convene/issues/1565
OK this is also a bit much; but it does fix the bug. 
Basically, two `_method`s make things explode.
=> 🐞🔨 `Gizmo`: Fix bug where removing a Gizmo fails

app/components/button_component.rb, spec/components/button_component_spec.rb
As part of https://github.com/zinc-collective/convene/pull/1592 I needed a Button that used the `dange` variant and all the turbo-y goodness.
So I pulled a variant into the `ButtonComponent`; and then we can search for `--danger` and purge them.
=> ✨🥔 `Components`: Expose `ButtonComponent#danger` variant

app/assets/stylesheets/components/button.scss, app/models/room.rb, app/views/furnitures/_form.html.erb, app/views/furnitures/_furniture.html.erb, spec/factories/space.rb, spec/system/furniture_spec.rb
- https://github.com/zinc-collective/convene/issues/1565
- https://github.com/zinc-collective/convene/issues/1472
For some reason the automated check doesn't *FAIL* despite it failing when we manually execute it!
The "cause" is that the gizmo form has two `_method` fields, one is the hidden `_method` field that is automatically inserted by `form_with` when the `model` is `persisted?`; the other is added by a `button` that sets the `_method` to delete so that it can be removed.
In the system spec; the driven `firefox` takes the `_method` set by the clicked `button`. In the user-land; it sends *both* methods; and Rails picks the first one.
The "solution" will be to ditch the second `_method` (possibly even removing the ability to Remove a Gizmo from the `update` form.)
=> 🥗 `Gizmo`: System Spec to Add and Remove Gizmo

.github/workflows/test-convene-web.yml
Update test pipeline names to add clarity.
- change `Run tests` ➡️  `Run Rspec tests` because the pipe runs Rspec Unit tests and now, the new System test `spec/system/furniture_spec.rb` (added in https://github.com/zinc-collective/convene/pull/1588) which also includes some browser testing.
- change `Run browser tests`  ➡️ `Run Cucumber tests` because the pipe not no longer the only pipe that runs browser tests.
=> 🧹 `Neighborhood`: update CI pipeline names

app/models/space.rb, app/views/spaces/edit.html.erb
- https://github.com/zinc-collective/convene/issues/1585
Trying to fix an issue @daltonrpruitt  found in https://github.com/zinc-collective/convene/issues/1565#issuecomment-1606496774 and add a missing condition to an if statement that got forgotten when https://github.com/zinc-collective/convene/pull/1593 was built
**prompts that display, if no section, no entrance and no entrance gizmos exist**
**prompts that display, if 1 section exists, but no entrance is set**
**prompts that display, if 1 section exists, it is set as entrance, but entrance has no gizmo**
**prompts that display, if section entrance has gizmo**
=> 🐞🔨 `Space`: When the `entrance` is missing, it explodes

app/furniture/marketplace/locales/en.yml
While learning my way through Marketplace app setup I was surprised to discover I missed adding a Delivery Area until I snooped around the code to debug the warning toast: 
> Marketplace configuration missing
>
> This marketplace is not ready for shopping, and is not visible to the public. Add missing configuration by going to Manage Marketplace.
=> `Marketplace`: Updates warning message to reflect requirements

app/controllers/application_controller.rb, app/controllers/furnitures_controller.rb, app/furniture/embedded_forms/_form.html.erb, app/furniture/livestreams/_form.html.erb, app/furniture/markdown_text_blocks/_form.html.erb, app/furniture/marketplace/bazaar.rb, app/furniture/marketplace/marketplace.rb, app/models/blueprint.rb, app/models/furniture.rb, app/models/room.rb, app/models/room/serializer.rb, app/models/space.rb, app/policies/furniture_policy.rb, app/policies/room_policy.rb, app/views/furnitures/_new.html.erb, app/views/furnitures/create.turbo_stream.erb, app/views/rooms/_room.html.erb, app/views/rooms/edit.html.erb, app/views/spaces/edit.html.erb, features/lib/Room.js, features/steps/furniture_steps.js, spec/models/blueprint_spec.rb, spec/models/furniture_spec.rb, spec/models/room_spec.rb, spec/models/space_spec.rb, spec/requests/furnitures_controller_request_spec.rb, spec/requests/rooms_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1472
Theoretically, this will get us a bit closer to Gizmofication...
I'm available to do a big-bang rename; but I figured starting with replacing where we call `.furniture` and `.furnitures` with `.gizmo` and `.gizmos` would be a smaller step; but it also is a bit scatter-shot.
I *think* it should be possible to rename the `Furniture` class (and it's related `Controller`, `Policy`, and `Views`) but I got skeered.
=> 🧹 `Gizmo`: Access a `Room`'s Gizmos via `.gizmos`

.devcontainer/startup.bash, bin/copy-example-envs, bin/setup, bin/setup-rails
We were performing the same actions in three different places. 
This consolidates those into one single script.
This also fixes a bug in copying the `.env.development.example` file over the `.env` file, which was only being done in the `.devcontainer/startup.bash` script.
=> 🏠 `Neighborhood`: Consolidate default setup of `.env*` files

Gemfile, Gemfile.lock, app/models/invitation.rb, app/models/person.rb, spec/models/invitation_spec.rb, spec/models/person_spec.rb
This fixes https://github.com/zinc-collective/convene/issues/1607
I also threw in some downcasing of `Person.email`, to match the downcasing we are already doing on the `Invitation.email`.
=> 🐛 `Invitations` and `People`: strip extra whitespace from emails

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/management_component.rb, app/furniture/marketplace/marketplace_component.html.erb, spec/furniture/marketplace/marketplace_component_spec.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
-  https://github.com/zinc-collective/convene/issues/831
Now we have a small set of buttons where the vew code only has the *differences*! yay!
=> 🧹 Eliminate duplication in `Marketplace::ManagementComponent`

app/furniture/journal/entries/_form.html.erb, app/views/application/_text_area.html.erb
I was doing some writing and noticed that I tend to drag the text area to make it bigger.
Now I won't have to do that!
=> 🌸 `Journal`: The `Entry#body` form field fills the screen

app/furniture/journal/entries_controller.rb, app/furniture/journal/entry.rb, spec/furniture/journal/entries_request_spec.rb, spec/furniture/journal/entry_spec.rb
Womp womp; apparently I had forgotten to do the `unprocessable_entity`, which meant that `turbo` was failing miserably instead of replacing the form when creating or updating a journal entry.
Well; now it's fixed!
=> 🐞🔨 `Journal`: Show error messages when `Entry` cannot be saved

app/furniture/journal/entry.rb, spec/furniture/journal/entry_spec.rb, spec/support/strip_attributes.rb
- https://github.com/zinc-collective/convene/pull/1630#discussion_r1253762788
> Not really part of your PR, but now that we have the
> `strip_attributes` gem, it might be worth throwing that on for
> `headline` and `body`, just so that we don't store trailing/preceding
> whitespace.
=> `Journal`: Strip whitespace from `slug`, `headline`, and `name`

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/marketplaces_controller.rb, app/furniture/marketplace/order/received_mailer.rb, app/furniture/marketplace/routes.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb, spec/furniture/marketplace/order/received_mailer_spec.rb
- https://github.com/zinc-collective/convene/issues/1511
Now that the `Marketplace` no longer has any user modifiable attributes, I got rid of all the leftovers.
=> 🧹 `Marketplace`: Remove `Controller#update` and unused `.settings`

.rubocop.yml, db/migrate/20230615002110_add_marketplace_order_notification_methods.rb, db/schema.rb
- https://github.com/zinc-collective/convene/issues/1511
I also meant to revert the accidental rename itself; but I totally forgot to in my rush to unmuck the issue.
=> 🧹 `Marketplace`: One last tiny tidy  for the fumble

Gemfile, Gemfile.lock, app/furniture/marketplace/cart_products_controller.rb, app/furniture/marketplace/controller.rb, app/furniture/marketplace/delivery_areas_controller.rb, app/furniture/marketplace/marketplaces_controller.rb, app/furniture/marketplace/notification_methods_controller.rb, app/furniture/marketplace/orders_controller.rb, app/furniture/marketplace/products_controller.rb, app/furniture/marketplace/tax_rates_controller.rb, spec/furniture/marketplace/notification_methods_controller_request_spec.rb, spec/furniture/marketplace/orders_controller_request_spec.rb, spec/furniture/marketplace/products_controller_request_spec.rb
This demonstrates how the `decent_exposure` gem reduces LoC-per-Controller. Right now, I've isolated this to the `Marketplace` namespace; since I wasn't sure if this would be received as a useful abstraction or an obstraction...
There's some warts I'm not keen on:
1. It uses `Object.const_get` to try and load a model based upon the name... which isn't the end of the world but it sure as heck doesn't play well with namespaces...
2. It would be nice if we could use a `with: [:policy_scoped]` so we don't have to call `policy_scope` every time; but it didn't look like that was possible straight-off-the-docs so I didn't go down the path of trying to make it work.
Thoughts?
P.s. The majority of the new lines are from the test I wrote to make sure that the `Marketplace::OrdersController` wasn't …
=> 🧹`Marketplace`: Demonstrate usage of `decent_exposure`

app/components/svg_component.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/management_component.rb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/stripe_accounts/show.html.erb, app/furniture/marketplace/stripe_accounts_controller.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1576
- https://github.com/zinc-collective/convene/issues/1622
- https://github.com/zinc-collective/convene/issues/1641
This makes it possible to link directly to the `StripeAccount`. Maybe it should be `PaymentMethods` or something once we start adding in other payment sources; but this should do it for now; and make it a bit easier to start improving the Marketplace Onboarding flow.
=> 🧹 `Marketplace`: Pull `StripeAccount` to its own page

app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/onboarding_component.html.erb, app/furniture/marketplace/onboarding_component.rb, app/furniture/marketplace/onboarding_component.yml, app/furniture/marketplace/routes.rb, app/furniture/marketplace/stripe_accounts_controller.rb, spec/furniture/marketplace/onboarding_component_spec.rb, spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1641
- https://github.com/zinc-collective/convene/issues/1576
- https://github.com/zinc-collective/convene/issues/1622
Now we encourage people to set up their `StripeAccount`!
We still need cleaner UI for that, but @rosschapman is working on that part.
=> 🥔✨ `Marketplace`: Check `StripeAccount` when `Onboarding`

app/furniture/journal/entry.rb, spec/furniture/journal/entry_spec.rb
- https://github.com/zinc-collective/convene/pull/1633/
I noticed I'd left the active-record relationship cables on the `Journal::Entry` loose. Getting rid of `delegate`s in favor of the `has_one :x, through: :y`
=> 🥗🧹`Journal`: Make relationships of `Entry` Rails-able

app/controllers/spaces_controller.rb, app/policies/space_policy.rb, app/views/spaces/_website_settings.html.erb, spec/requests/spaces_controller_request_spec.rb
- For https://github.com/zinc-collective/convene/issues/1513
After setting a domain on Space configure page, the Space#update will redirect to that new domain and encounter the issue below. Thus users cannot load the Space configure page to see the domain setting on their space.
e.g. in below example, space.branded_domain = "games.local"
https://github.com/zinc-collective/convene/assets/50284/9945c53e-24cb-4331-a8a2-45ec13569584
=> 🥔✨ `Space`: `Member` may set `Domain`

app/furniture/journal/entry.rb, app/furniture/journal/keyword.rb, db/migrate/20230713230334_journal_add_keywords_to_entries.rb, db/schema.rb, spec/factories/furniture/journal.rb, spec/furniture/journal/entry_spec.rb, spec/furniture/journal/keyword_spec.rb
This gets us a little bit closer to being able to browse `Entry` by `Keyword`s, since each `Entry` will know it's keywords
=> 🧹 `Journal`: `Entries` store their `Keywords`

app/furniture/journal/entry.rb, spec/furniture/journal/entry_spec.rb
Turns out we were storing the keyword every time it was used; which... isn't bad but isn't great either!
=> 🥗🧹 `Journal`: `Entry` stores each `Keyword` it uses only once.

app/furniture/journal/entry.rb, app/furniture/journal/keyword.rb, app/furniture/journal/keyword_policy.rb, app/furniture/journal/keywords/show.html.erb, app/furniture/journal/keywords_controller.rb, app/furniture/journal/routes.rb, spec/factories/furniture/journal.rb, spec/furniture/journal/keywords_controller_request_spec.rb
...Truly, a thing of beauty...
=> 🥔✨ `Journal`: Sprout `Keywords#show`

app/furniture/journal/entries/show.html.erb, app/furniture/journal/entry.rb, app/furniture/journal/entry_component.html.erb, app/furniture/journal/entry_component.rb, app/furniture/journal/journals/_journal.html.erb, spec/furniture/journal/entry_component_spec.rb, spec/furniture/journal/entry_spec.rb
This refactor allows us to do post-processing of the markdown at the Component level, which has access to the rails URL builders; which should allow us to link to the `Keyword` within the `Entry#body`
=> 🧹 `Journal`: Move `Entry` rendering to `EntryComponent`

app/furniture/journal/entry.rb, app/furniture/journal/entry_component.rb, app/furniture/journal/keyword.rb, spec/furniture/journal/entry_component_spec.rb, spec/furniture/journal/entry_spec.rb
=> 🥔✨ `Journal`: `Entries` link to their `Keywords`

app/furniture/marketplace/order_policy.rb, app/furniture/marketplace/orders_controller.rb, spec/furniture/marketplace/order_policy_spec.rb
- https://github.com/zinc-collective/convene/issues/1657
- Alternative to https://github.com/zinc-collective/convene/pull/1685
This adjusts the `OrdersController` to use the `Shopper` for the `OrderPolicy::Scope`; which ensures
when `Guests` place an order, only the device used to place the `Order` will be able to see the `Order`
Pros:
- If the `Order` url  is intercepted by a nefarious actor, it won't leak the `Shopper`s information
Cons:
- `Shopper` for `Guests` is device-dependent, so if I order something on my laptop I can't open the `Order` on my phone.
=> 🐞🔨 `Marketplace`: `Guest` can see only their `Orders`

.env.example, .github/workflows/test-convene-web.yml, spec/factories/utility.rb, spec/furniture/marketplace/buying_products_system_spec.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb, spec/support/stripe_cli.rb, spec/support/system_helpers.rb, spec/system/furniture_spec.rb
The bug is fixed in https://github.com/zinc-collective/convene/pull/1685
For grokability reasons, I am considering splitting this into a few different PRs:
- A introduces the new ENV variable
- B extracts the shared system spec helpers
- C implements the stripe cli forwarding
- D implements the system test
=> 🥗 `Marketplace`: Buying `Products` as a `Guest` System Test

app/furniture/marketplace/cart/deliveries/_delivery.html.erb, app/furniture/marketplace/carts/_cart.html.erb
- https://github.com/zinc-collective/convene/issues/1325
- https://github.com/zinc-collective/convene/issues/1672
🍐 w/ @rosschapman 
- [MVP](https://docs.google.com/document/d/1wbXO82OeEkoIOj8zL6B24fiCC2Wg-w7949fo6wg3qhc/edit#heading=h.q036oj2sxhx6) part of https://github.com/zinc-collective/convene/issues/1672
display DeliveryExpectations above deliveryAddress because IMHO it looks better.
**Before**
Mobile
Desktop
**After**
Mobile
Desktop
=> 🌸 `Marketplace`: Group `Delivery` `Window` and `Address`

app/furniture/marketplace/orders/index.html.erb, app/furniture/marketplace/orders_controller.rb, spec/furniture/marketplace/orders_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1691
This just makes sure the orders index isn't overwhelming with all the un-checked-out-carts
=> 🐞🔨 `Marketplace`: Only list `paid` `Orders`

app/furniture/marketplace/stripe_events_controller.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1656
Stripe sends every event to every `Stripe::Webhook` listening for it's type; which makes a lot of sense but does not play well with our current design where every Marketplace creates their own `Stripe::Webhook`.
In the short-term, discarding events for orders that do not belong to the given `Marketplace` gets us away from accidental double-mailing (or worse, double-transfering!)
=> 🥗🐞🔨 `Marketplace`: Prevent duplicate `Order::Notification`

app/furniture/marketplace/order.rb, app/furniture/marketplace/stripe_events_controller.rb, db/migrate/20230725192832_marketplace_add_payment_processor_fees_to_order.rb, db/schema.rb, spec/furniture/marketplace/order_spec.rb
- https://github.com/zinc-collective/convene/issues/1327
In order to pull the splitting of the payment to a retriable background job; we need to cache the payment processor fee information.
=> 🧹 `Marketplace`: Cache the fee amount on the `Order`

app/furniture/journal/entry_component.rb
- https://github.com/zinc-collective/convene/pull/1684#discussion_r1270924805
Better name thanks to @RossChapman
=> 🧹 `Journal`: Rename the method that turns Keywords into Links

app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/event.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/stripe_events_controller.rb, db/migrate/20230727010141_create_marketplace_events.rb, db/schema.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/checkout_spec.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb, spec/furniture/marketplace/event_spec.rb, spec/furniture/marketplace/order_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1331
Start recording an audit trail of some of the key events, so that we can review what happened when.
Starting with:
- Cart Created
- Checkout Started
- Payment Received
- Notifications to Vendor and Distributor Sent
- Notification to Buyer Sent
- Payment Split
=> 🥔✨ `Marketplace`: Record `Order` and `Cart` events

app/furniture/journal/entry_component.rb, app/furniture/journal/keyword.rb, spec/furniture/journal/entry_component_spec.rb, spec/furniture/journal/keyword_spec.rb
- https://github.com/zinc-collective/convene/issues/1714
Turns out, it was a renderer-layer thing; where the shorter `Keyword` was getting linkfied prior to the longer `Keyword`, and when I switched to linkify the longer `Keyword` first it would double-down on the links putting a link to the shorter keyword within the longer one!
So now I'm matching the `#` as part of the `Keyword`, and replacing it with the html entity for `#`, (aka `&#35;`)
This makes it so when we linkify keywords long-to-short; the longer keywords no longer contain the shorter keyword; eliminating the nested `a` tags.
=> 🐞🔨 `Journal`: `Entry` supports overlapping `Keywords`

app/furniture/journal/journals/_journal.html.erb, app/furniture/journal/keywords/show.html.erb, app/furniture/journal/locales/en.yml, app/furniture/journal/new_entry_button_component.html.erb, app/furniture/journal/new_entry_button_component.rb
- https://github.com/zinc-collective/convene/issues/1713
I thought I would tilt at this while I waited for the build to go out; since I noticed I go from an `Entry` to a `Keyword` when trying to decide what to fill in next when world building.
It also auto-fills the new `Entry` body with the `Keywords` canonical version and it's aliases!
Which... I need to make a UI for soonish.
=> 🥔✨`Journal`: Enter `Entry#new` flow via `Keyword#show`

app/components/card_component.html.erb, app/components/card_component.rb, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/tax_rate_component.html.erb
Here's a before/after of the `Marketplace::ManagementComponent` on the Manage Marketplace landing screen. If there is no content, the content section will not display:
=> 🌸`Components`: Remove blank space from `Cards` without `content`

app/furniture/marketplace/stripe_events_controller.rb
- Recommended by @anaulin https://github.com/zinc-collective/convene/pull/1701#discussion_r1275566331
=> 🧹 `Marketplace`: Cause Stripe to Retry if we can't mark an `Order` as `paid`

app/furniture/journal/entry.rb, spec/furniture/journal/entry_spec.rb
Also part of the writing I'm doing on https://slipvector.games, I have a Journal for non-canon (well, several; depending on if it's worldbuilding or concept art or a story) and then a `Journal` for canon content.
I want to be able to take an entry and move it into the Canon journal; and I'm fine doing it from the rails console for now; but I probably will expose a command end-point like
`/journal/:entry_id/migrate_to?journal_id=...&keywords[]=AKeyword&keywords[]=BKeyword` and add a button on the `Entry#edit` screen to enter the flow for selecting the Journal / adding Keywords.
=> ✨ `Journal`: `Entry` can be migrated to another `Journal`

app/furniture/journal/keyword.rb, app/furniture/journal/keyword/merge.rb, spec/furniture/journal/keyword_spec.rb
- https://github.com/zinc-collective/convene/issues/1713
There's a number of things that can and will go wrong with this code eventually, including (but not limited to)
1. What happens when a `Keyword` has 1000s of entries?!
2. If this happens on-request-thread it will probably be very very slow; but if we do it *off* request-thread; the `Keyword#show` UI will be out-of-date; and we haven't implemented `ActionCable` yet
But hey, at least I will have a Heroku-CLI affordance for merging some of the `Keywords` that are synonyms...
I'll probably want to build out a WUI as well; but I wanted to get the basic logic written down and tested before I tilted at the WUI.
=> 🥗✨ `Journal`: `Keyword`s can be merged into one another

app/controllers/spaces_controller.rb
- https://github.com/zinc-collective/convene/pull/1727
Since we use the `current_space` in the application layout; and we alias `current_space` to the `space` being interacted with in the `SpacesController`, the tests for what should happen when someone who isn't allowed to create a `Space` hit the `new` endpoint began to fail.
This adjusts so that `current_space` will return `space` in the `SpacesController` when the user is unauthorized; which will give them the appropriate layout for the space but does not let them actually make data changes.
=> 🔨 `Space`: Properly 404 when `current_person` cannot create or update `Space`

app/models/furniture.rb
So, I tried a few things:
- "Maybe lockbox/rails needs updating!" (They didn't)
- "Maybe `secrets` is a reserved word?" (It wasn't)
And then while spelunking the stacktrace, I noticed that the exception was being thrown within the `RankedModel` gem!!!
So then I dug in a bit, calling `self.attributes` in a byebug within the `after_initialize` and realized that in the cases the exception was not being thrown the attribute was actually missing.
Which gave me the affordances for making the logical leap to [`ActiveRecord::QueryMethods.select`](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-select)
=> 🔨 `Gizmo`: Don't try to set default `secrets` if the `secrets_ciphertext` isn't loaded

spec/support/mailer.rb, spec/support/turbo.rb
I noticed this Sunday with Dalton, but don't know if I actually made any PRs with it...
Anyway, apparently the `MiniTest` namespace is no more; and it is only `Minitest`. It had been deprecated for a while but I am old and set in my ways.
=> 🧹 `Neighborhood`: Apparently `MiniTest` is no more

.gitignore, .vscode/extensions.json
- https://github.com/zinc-collective/convene/issues/1737
[Bust A Gem](https://marketplace.visualstudio.com/items?itemName=gurgeous.bust-a-gem) was recommended by @RossChapman as a way to provide jump-to-definition support for gems.
It seems neat, and seems worth adding to our recommended extensions / `.gitignore` so that folks who want/like to use it can do so.
=> 🥔✨ `Contributor`: Support `Bust A Gem` VSCode Extension

app/furniture/marketplace/split_job.rb, app/furniture/marketplace/stripe_events_controller.rb, db/migrate/20230814180326_marketplace_add_stripe_transfer_id_to_orders.rb, db/schema.rb, spec/furniture/marketplace/split_job_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1700
This may not be the right call, so I'm just tossing it up for conversation. In particular:
- Sidekiq does *not* guarantee once-and-only-once execution of jobs; which means if we have two workers and they both grab the job off the queue we might get two transfers. Not a good look.
- It would probably be better for us to explicitely record on our end that a Transfer has been created (or perhaps query the Stripe API?
- While automatic splitting seems like the right call; I don't know that splitting immediately upon payment is the right call. Stripe holds funds for 3 days; which indicates we should not pull it from the float until it's cleared?
Anyway, it should at least fix the bug where initial payment splits will fail if there is an …
=> 🥗🥔✨ `Marketplace`: Failed Automatic `Split` payments try again

app/components/card_component.html.erb
I noticed this when doing some debugging of some dom html issues.
It wasn't the problem; but I fix it anyway.
=> 🧹 Whoops! Extra "="

Gemfile, Gemfile.lock
- https://github.com/zinc-collective/convene/issues/1764
Since `solargraph` is a dev tool opted-in on a
contributor-by-contributor basis, I'm pulling it from the `Gemfile`.
Installing in a `Gemfile` isn't necessary for either `solargraph` or the VS Code extension to work; but it *does* add unecessary weight to our `Gemfile` and `Gemfile.lock`.
=> 🧹 `Contributors`: Don't mandate installation of `solargraph`

app/furniture/marketplace/orders/_order.html.erb
- https://github.com/zinc-collective/convene/issues/1331
- https://github.com/zinc-collective/convene/pull/1712#discussion_r1294632293
While either `History` or `Timeline` are way better than `Events`; `Timeline` felt better than `History`; since `Order History` feels like the history of all `Orders`; and `Order Timeline` feels like the `Timeline` for a single `Order`.
=> 🌸 `Marketplace`: Rename `Events` section to `Timeline`

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/cart/delivery_area_component.html.erb, app/furniture/marketplace/cart/delivery_area_component.rb, app/furniture/marketplace/cart/delivery_areas/_form.html.erb, app/furniture/marketplace/cart/delivery_areas/edit.html.erb, app/furniture/marketplace/cart/delivery_areas/show.html.erb, app/furniture/marketplace/cart/delivery_areas_controller.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplace_component.html.erb, app/furniture/marketplace/marketplace_component.rb, app/furniture/marketplace/routes.rb, app/views/application/_select.html.erb, spec/furniture/marketplace/buying_products_system_spec.rb, spec/furniture/marketplace/cart/delivery_areas_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1672
- https://github.com/zinc-collective/convene/issues/1325
So, in reviewing a bunch of the delivery app workflows, most of them have:
- Choose Pickup or Delivery
- Enter Address
- Browse Menu
- Tap Item
- Add Item to Order
This lends me to believe we want to switch to gathering the `DeliveryArea` *then* `DeliveryAddress` *then* showing the `Products` that are available.
This uses TurboFrames to replace pieces of the page, rather than relying on TurboStreams. On the one hand, it's lot easier (just respond with html with matching `turbo_frame_tag`s`).
Blerg; anyway, I'm checking this in now; but not sure if I like it enough. …
=> 🌸✨ `Marketplace`: `Shopper` chooses `DeliveryArea`

app/policies/membership_policy.rb, spec/factories/person.rb, spec/policies/membership_policy_spec.rb
Resolves https://github.com/zinc-collective/convene/issues/1659
- https://github.com/zinc-collective/convene/issues/1659
This was the root cause of why I was getting such weird behavior in production, not seeing any members in the Piikup Marketplace Space: it is because I was logged in with an account that is an operator, but not a member of the Piikup Space.
=> 🐞🔨 `Operators` always see all `Space` `Members`

app/components/marketplace/stripe_overview_component.rb, app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/payment_settings/index.html.erb, app/furniture/marketplace/payment_settings_controller.rb, app/furniture/marketplace/routes.rb, spec/components/marketplace/stripe_overview_component_spec.rb, spec/components/previews/marketplace/stripe_overview_component_preview.rb
This changeset is more the result of developer onboarding (for me) as I prototyped (in code) consolidating configuration for payment related things. This is merely a piece of a partial solve for requirements of https://github.com/zinc-collective/convene/discussions/1605 or https://github.com/zinc-collective/convene/discussions/1622. But was invaluable to help me understand _how to frontend_ in the Marketplace domain. I think this is going to be a boon for my 🍐 session with @KellyAH next week. 
- The CardComponent styling refactor does force automatically bottom-aligned CTAs. 
After:
=> 🌸✨ `Marketplace`: `Management` includes ` Payment Settings` screen

app/furniture/marketplace/cart/delivery_area_component.html.erb
- https://github.com/zinc-collective/convene/issues/1672
=> 🌸 `Marketplace`: Show the Delivery Expectations when choosing the Delivery Area

app/views/layouts/application.html.erb
Hat-tip: @joshmcarthur - https://www.joshmcarthur.com/til/2018/03/26/til-nested-layouts-in-rails.html
In the `Marketplace`, we are starting to wrap the entire UI in Turbo Frames; for maximum snappy-goodness.
However, it was quickly becoming an effort of copypastafarian proportions; so I thought "Hmm, wouldn't it be nice if we could do this using a layout?!"
Unfortunately, we had not set up our Rails view pipeline to support layouts. (Boooo! hiss! Boo!!!)
So now we do!
So long as the layout uses `content_for(:content)` it will support nested layouts!!
=> 🛠️✨ `Gizmos`: Support nested layouts

app/policies/invitation_policy.rb, app/policies/person_policy.rb, app/policies/rsvp_policy.rb, spec/policies/invitation_policy_spec.rb, spec/policies/person_policy_spec.rb, spec/policies/space_policy_spec.rb
Working on https://github.com/zinc-collective/convene/pull/1778, I noticed that we have a few Scopes that are defined as `scope.all` for all cases, and probably shouldn't be.
Some of these scopes might not be in use at the moment, but I figured I could fix them all up to prevent future issues.
=> 🛠️🔐 `Security`: Review Policy objects and constrain default access levels

app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/controller.rb, app/furniture/marketplace/marketplaces_controller.rb, app/furniture/marketplace/payment_settings_controller.rb
This may turn out to be a terrrrrrible idea; but it may also be fine.
Essentially, the `Marketplace` now lives within a turbo-frame; which means it's going to be replacing itself inline. Cool? Also, horrifying.
Basically, now every `Marketplace::*Controller` will want to inherit from `Marketplace::Controller`, so when we click a link it will auto-magically swap out the content without requiring us to do anything at all! Cool, huh?
=> 🧹🛠️ `Marketplace`: Wrap the whole thing in Turbo Frames

app/furniture/marketplace/order.rb
Results from `bin/rspec spec/furniture/marketplace/order_spec.rb`
Before:
```
Marketplace::Order
is expected to have many ordered_products dependent => destroy inverse_of => order
is expected to have many products through ordered_products inverse_of => orders
is expected to belong to marketplace class_name => Marketplace::Marketplace required: true inverse_of => orders
is expected to belong to shopper required: true inverse_of => orders
is expected to belong to delivery_area inverse_of => orders optional: true
is expected to have many events inverse_of => regarding dependent => destroy
#vendors_share
is expected to eq #<Money fractional:-85157 currency:USD>
#price_total
DEPRECATION WARNING: Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since …
```
=> 🧹 `Marketplace`: Fix deprecation warning in `Order#price_total`

app/components/button_component.rb, app/components/marketplace/stripe_overview_component.rb, app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/stripe_accounts/show.html.erb, spec/furniture/marketplace/collecting_payments_system_spec.rb
- https://github.com/zinc-collective/convene/issues/1806
- https://github.com/zinc-collective/convene/issues/1622
Turns out, there were a number of small bugs here:
- Both `Marketplace::Marketplace` and `Marketplace::StripeOverviewComponent` presumed that there would be a `StripeUtility` for the `Space`; when there may not be.
- The link to `Space#edit` does not have a turbo-frame for the marketplace; so it needed to have turbo disabled
- The `ButtonComponent` did not have a way to disable turbo!
This fixes all of that, and allows `Operators` and `Members` to set the Stripe API key via the `Marketplace#edit` flow.
=> 🥗🐞🔨 `Marketplace`: Test & Fix Setting `Stripe` API Key

app/furniture/marketplace/carts/_total.html.erb
- https://github.com/zinc-collective/convene/issues/1325
I think this is leftover from when we collected both the address and the area at the same time.
=> ✨ `Marketplace`: Show `DeliveryFee` when `DeliveryArea` is selected

app/controllers/application_controller.rb
https://github.com/zinc-collective/convene/issues/1844
I think we've reached the point where this is mostly just noise.
It's possible we should doing more; but the 404 page asks them to make sure they are logged in; so I think it should be fine.
Maybe one day we will add an "if you think you've reached this page in error" or something...
=> 🧹 `Neighborhood`: Stop telling Sentry about authorization errors

app/assets/stylesheets/components/header.scss, app/furniture/marketplace/marketplace_component.html.erb, app/furniture/marketplace/marketplace_component.yml, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, features/harness/Page.js, features/lib/Actor.js
- https://github.com/zinc-collective/convene/issues/832
- https://github.com/zinc-collective/convene/issues/621
- https://github.com/zinc-collective/convene/issues/833
The top navigation is a bit excessive, especially on mobile. 
This brings the UI to a much cleaner place; with breadcrumbs and sign in / out only on the bottom of the page.
=> 🌸 `Themes`/ `Mobile`:  Eliminate top navigation

app/models/room.rb, db/migrate/20231005005905_drop_publicity_level_from_rooms.rb, db/schema.rb
=> 🧹 `Section`: Drop the `publicity_level` column, since it is dead

app/models/authentication_method.rb, spec/models/authentication_method_spec.rb
- https://github.com/zinc-collective/convene/issues/1809
There's a couple things happening, one of which is if an `AuthenticationMethod` does not have a One Time Password Secret, it can't actually do the verification.
So i've added a check to make sure it returns false in cases when the OTP secret has not been set yet; as well as when a nil OTP is provided.
=> 🐞🔨 `Authentication`: Don't explode when OTP or OTP secrets are nil

app/models/authenticated_session.rb, spec/models/authenticated_session_spec.rb
- https://github.com/zinc-collective/convene/issues/1809
OK, so my working assumption is that the bug is caused by two requests being processed at the same time for a new email address, and the first one creates the `AuthenticationMethod` and the second one *tries* to, and fails; resulting in the validation error.
This requeries the database and retries the rest of the work.
Would love to have names for methods to pull this out into, rather than copy-pasting the method body but oh well.
=> 🐞🔨`Authentication` Prevent race condition when double-tapping sign-in

app/views/rooms/_form.html.erb, app/views/rooms/edit.html.erb, config/locales/room/en.yml, spec/system/sections_spec.rb
- https://github.com/zinc-collective/convene/issues/1841
So, this was caused by me being FANCY and putting the delete button in the same form as the edit and update. A bad idea.
Now, deleting a Section is handled in it's own independent form, rather than attempting to rewrite the forms hidden `_method` field to trick Rails into doing a destroy.
This is also better from a design perspective because:
A) omg, a delete button so close to the save button is DANGEROUS
B) Deleting a Section is kinda a big deal, and while it would be better  to bubble-wrap the heck out of it so people who *do* delete a  section don't wind up in a sad-mad state; we can at least give them  lots of "DANGER WILL ROBINSON DANGER" messaging. 
This is... irresponsible of us but what we can do now. If a motivated …
=> 🐞🔨 `Section`: Deleting Sections is possible again

app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb, spec/components/marketplace/stripe_overview_component_spec.rb, spec/furniture/marketplace/collecting_payments_system_spec.rb
Writing a component view spec encouraged me to "find" the actual conditional cases present here. Generally I prefer unwrapping these cases with separate rendering paths rather than doing more inline cleverness switching on value presence.
=> Adds content for Stripe Account settings component when Stripe utility missing

app/furniture/marketplace/cart/delivery_area_component.html.erb, spec/furniture/marketplace/cart/delivery_area_component_spec.rb
Follow-up to https://github.com/zinc-collective/convene/pull/1920
=> Adds view-level unit specs for `Marketplace::Cart::DeliveryAreaComponent'

Gemfile, Gemfile.lock, db/schema.rb
We upgraded to Rails 7.1 in https://github.com/zinc-collective/convene/pull/1901, but the migrations file was not updated, so if you run all migrations on a clean branch you get this diff to update the schema version in `schema.rb`. This PR fixes things so that there are no schema changes on a clean app install.
Also took the opportunity to tweak the Rails version constraint in the Gemfile, for added clarity.
=> Update `Gemfile` and `schema.rb` files to reflect the version of Rails we're using

Gemfile, Gemfile.lock, app/furniture/marketplace/flyer.rb, app/furniture/marketplace/flyer_policy.rb, app/furniture/marketplace/flyers/show.html.erb, app/furniture/marketplace/flyers_controller.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/routes.rb, app/views/layouts/nude.html.erb
- https://github.com/zinc-collective/convene/issues/1956
This gives us a QR-Code Flyer, but we should probably ditch the footer if we can...
I sprouted a "nude" layout (Ok it needs a better name) that gives us an empty page and breaks us out of turbo-frame land.
Anyway, to make pretty we need to:
- Attach a `Vendor`'s logo to the `Space`
- Attach a `Distributor`s logo to the `Marketplace`
- Actually work towards the fancy-pants design that Mari made!
But in the meantime, this is something that could exist and maybe even could get better.
[Zee's Pizza.pdf](https://github.com/zinc-collective/convene/files/13445705/Zee.s.Pizza.pdf)
=> `Marketplace`: Very Rough  `Flyer`

app/furniture/section_navigation.rb, app/furniture/section_navigation/README.md, app/furniture/section_navigation/section_navigation.rb, app/furniture/section_navigation/section_navigations/_section_navigation.html.erb, app/models/furniture.rb
Sprouts a tiny Gizmo for linking to Sections. At some point, we'll want to add a UI for picking which `Sections` to include, preferably an `AllowList` so that adding a `Section` doesn't immediately publish it.
=> ✨ `Gizmo`: `SectionNavigation`

app/furniture/marketplace/cart/deliveries/_form.html.erb, app/furniture/marketplace/cart/deliveries/edit.html.erb
Turns out, our `Delivery` form was going to a weird spot which may or may not be why we couldn't place orders on Crumble & Whisk
Anyway, now instead of posting to
`/marketplace/carts/:cart_id/delivery.:delivery_id` it will post to `/marketplace/carts/:cart_id/delivery`
=> 🐞🔨 `Marketplace`: `Buying Products` Fix `Delivery` Form

app/furniture/marketplace/checkouts/show.html.erb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/marketplaces/show.html.erb, spec/furniture/marketplace/buying_products_system_spec.rb
So, TIL about `data-turbo-action=advance` which tells turbo to update the URL when moving from spot to spot.
Now, when navigating through the Marketplace Management and Checkout flow the URL bar actually update! Magic! Ponies! Sparkles! Hooray!
=> `Marketplace`: The Back button works!

app/furniture/marketplace/marketplaces/show.html.erb
- Follow on for https://github.com/zinc-collective/convene/pull/1981
I noticed this and removed the duplication but forgot to commit it! Anyway, now it's a little tidier.
=> 🧹 `Marketplace`: eliminate some duplication

app/furniture/marketplace/marketplace_component.rb, spec/furniture/marketplace/marketplace_component_spec.rb
- https://github.com/zinc-collective/convene/issues/1962
There was a bug we noticed during the Sutty demo where carts were being cleared.
Turns out, if a `Marketplace` had multiple `DeliveryAreas` we would create a new `Cart` for the shopper every time the page loaded. Womp. Womp.
=> 🐞🔨 `Marketplace`: Don't clear `Cart` when switching `Marketplaces`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/carts/_footer.html.erb, spec/furniture/marketplace/buying_products_system_spec.rb
- https://github.com/zinc-collective/convene/issues/1983
Prevents `Shoppers` from visiting the `Checkout` screen until a `DeliveryArea` has been selected; which should prevent the sad bug.
=> 🐞🔨 `Marketplace`: `Checkout` is prevented without a `Cart::DeliveryArea`

app/furniture/marketplace/carts/_footer.html.erb
- https://github.com/zinc-collective/convene/issues/1983#issuecomment-1839919010
It feels odd that we have a `Checkout` button when you can't click it.
https://github.com/zinc-collective/convene/assets/50284/700694ad-6b78-4be7-98fe-81c66ea577f0
=> 🌸 `Marketplace`: `Checkout` button is not shown until you can Checkout

.env.example
`.env` is loaded in `test` environment; so if you uncomment the smtp lines in `.env` the action mailer delivery method gets clobbered; breaking the tests.
We already have `.env.development.example`, which includes the smtp settings; and that only gets loaded in the `development` environment! Hooray!
=> 🧹 Don't encourage people to set the SMTP in .env

spec/rails_helper.rb
Resolves this deprecation warning when running tests:
=> 🧹  Fix Rails 7.1 deprecation warning: `fixture_paths` are now plural, and an array

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplace_component.rb, spec/furniture/marketplace/marketplace_spec.rb
Following up to the convo in https://github.com/zinc-collective/convene/pull/1992#discussion_r1418188891, this PR tightens up the logic for finding or creating a cart for a shopper.
=> 🧹 `Marketplace`: Move logic for finding or creating a cart for a shopper into a factory method

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/views/layouts/_head.html.erb
- https://github.com/zinc-collective/convene/issues/2013
I think this should help with the "No Content" messages; but they'll still be errors.
=> 🐞🔨 `Neighborhood`: Force full page reload on error page

app/furniture/marketplace/flyers/show.html.erb, spec/furniture/marketplace/flyer_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2017
I apparently was testing the Flyer page with hard refreshes too much; this adds a system test to actually hit the flyer page and check that it has a URL.
It would be cool if I could figure out a way to check that it has the QR code too; but I don't feel smert enough to figure out how to do that.
=> 🐞🔨 `Marketplace`: `Flyer` page no longer shows "no content"

app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/delivery_areas/edit.html.erb, app/furniture/marketplace/delivery_areas/new.html.erb, app/furniture/marketplace/delivery_areas_controller.rb, spec/furniture/marketplace/delivery_area_component_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Now that we have a better idea how to use TurboFrames, the Streams seem pretty unnecessary.
This also makes it so following links within the
`Marketplace::ManagementComponent` update the browser URL.
=> 🧹 `Marketplace`: `DeliveryArea` Strip TurboStreams

app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/delivery_areas/edit.html.erb, app/furniture/marketplace/delivery_areas/index.html.erb, app/furniture/marketplace/delivery_areas/new.html.erb, app/furniture/marketplace/delivery_areas_controller.rb, spec/furniture/marketplace/delivery_area_component_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb, spec/furniture/marketplace/delivery_areas_system_spec.rb
Figure once a `DeliveryArea` is archived, we don't want it clogging up the main page. So now it goes behind an `archive` flag.
=> ✨ `Marketplace`: Put Archived `DeliveryAreas` behind the `Archive` link

app/views/furnitures/_furniture.html.erb, app/views/invitations/_invitation.html.erb, app/views/memberships/_membership.html.erb, config/locales/icon/en.yml
We don't need both a `remove` and `destroy` icon; and we use `destroy` in more places.
We also don't need an `edit` and `pencil`, so I dropped `pencil` since it was unused.
=> 🧹 `Neighborhood`: Drop extraneous icons

Gemfile, Gemfile.lock, app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/cart/delivery_area_component.rb, app/furniture/marketplace/cart/delivery_areas/_form.html.erb, app/furniture/marketplace/delivery_area.rb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/delivery_areas/edit.html.erb, app/furniture/marketplace/delivery_areas/index.html.erb, app/furniture/marketplace/delivery_areas/new.html.erb, app/furniture/marketplace/delivery_areas_controller.rb, app/furniture/marketplace/locales/en.yml, config/locales/en.yml, config/locales/icon/en.yml, db/migrate/20231212003521_marketplace_add_discarded_at_to_delivery_areas.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/delivery_area_component_spec.rb, spec/furniture/marketplace/delivery_area_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb, spec/furniture/marketplace/delivery_areas_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2014
This adds the `discard` gem so that we can archive objects. It also updates the workflow for removing DeliveryArea to have an `Archive` step first.
Once a `DeliveryArea` is archived, it can not yet be restored; but it can be removed if there are no `Orders` associated with the `DeliveryArea`
=> 🥔✨ `Marketplace`: `DeliveryAreas` may be `Archived`

app/views/rooms/edit.html.erb, spec/system/sections_system_spec.rb
=> 🐞 `Marketplace`: Fixes missing argument for translation string interpolation

app/furniture/marketplace/archivable/index_link_component.html.erb, app/furniture/marketplace/archivable/index_link_component.rb, app/furniture/marketplace/archivable/index_link_component.yml, app/furniture/marketplace/component.rb, app/furniture/marketplace/delivery_areas/index.html.erb, app/furniture/marketplace/product_component.html.erb, app/furniture/marketplace/product_component.rb, app/furniture/marketplace/products/index.html.erb, spec/furniture/marketplace/archivable/index_link_component_spec.rb, spec/furniture/marketplace/product_component_spec.rb, spec/furniture/marketplace/selling_products_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2023
This makes `Products` more consistent with `DeliveryAreas` by:
- Removing the `Remove` link from the `ProductComponent` unless the `Product` is already `archived?` 
- Adding a visual indicator that `Products` have been `archived` to the `ProductComponent`
- Moving the `archived` `Products` to another page.
I'm not convinced this Component is the right component to extract. Maybe a `DeliveryArea::ManagementComponent` and `Product::ManagementComponent` are the right step instead?
=> 🥗🌸✨ `Marketplace`: Hide `archived` `Products` from `Products#index`

app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/delivery_areas/edit.html.erb, app/furniture/marketplace/delivery_areas/index.html.erb, app/furniture/marketplace/delivery_areas/new.html.erb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/notification_methods/index.html.erb, app/furniture/marketplace/payment_settings/index.html.erb, app/furniture/marketplace/products/edit.html.erb, app/furniture/marketplace/products/index.html.erb, app/furniture/marketplace/products/new.html.erb, app/furniture/marketplace/stripe_accounts/show.html.erb, app/furniture/marketplace/tax_rates/index.html.erb
- While working on https://github.com/zinc-collective/convene/pull/2053, I thought to myself "Wait, what if... What if we didn't have to remember to wrap things in the `ManagementComponent` at all?! What if all that could be eliminated from the `new`/`edit`/`index`/`show` pages entirely?
So I did! Hooray!
=> 🌸 `Marketplace`: All `Member` pages are in the `ManagementComponent`

app/models/room.rb, app/views/layouts/_head.html.erb, app/views/rooms/_form.html.erb, db/migrate/20231221025246_add_section_description.rb, db/schema.rb, spec/models/room_spec.rb
- Meta description tags are useful for SEO; and maybe even useful for https://github.com/zinc-collective/convene/issues/1988
- I would love if we allowed `Section#title` to be set as well
=> ✨ `Section`: Allow `description` to be set for SEO

app/components/card_component.rb, app/views/layouts/application.html.erb
This won't do anything in most cases; but if a `CardComponent` is inside of an element with height, such as a `grid`; it will take up the entire thing.
It's possible that we should be using `items-stretch` or something?
Anyway, here's a few places where cards are:
=> 🧹 `CardComponent`: Cards fill as much space as they can

app/components/card_component.rb, app/furniture/section_navigation/section_navigations/_section_navigation.html.erb, app/views/layouts/application.html.erb, spec/furniture/section_navigation/section_navigation_system_spec.rb
- https://github.com/zinc-collective/convene/issues/1988
=> 🥔✨ `SectionNavigation`: Include `Section#description` in SectionLink

Gemfile, Gemfile.lock, app/assets/stylesheets/components/form.scss, app/controllers/authenticated_sessions_controller.rb, app/views/authenticated_sessions/_form.html.erb, app/views/authenticated_sessions/create.html.erb, app/views/authenticated_sessions/new.html.erb, config/locales/authenticated_session/en.yml, config/locales/en.yml
This PR:
* improves the look of our sign-in form
* updates our default submit button style throughout the site to not be 100% wide
* removes the emojis from the default "save" and "create" button strings
* adds the i18n-debug gem to help with figuring out which i18n keys are being looked up
=> Improve sign-in UI

app/furniture/marketplace/archivable.rb, app/furniture/marketplace/delivery_area_policy.rb, app/furniture/marketplace/delivery_areas/_form.html.erb, app/furniture/marketplace/delivery_areas/edit.html.erb, app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/products/edit.html.erb, config/locales/en.yml, spec/furniture/marketplace/delivery_areas_system_spec.rb, spec/furniture/marketplace/selling_products_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2014
- https://github.com/zinc-collective/convene/issues/2023
This allows a `Product` and `DeliveryArea` to be Restored; and also makes their forms look the same.
=> 🥔✨ `Marketplace`: `#restore` `Products` and `DeliveryAreas`

app/views/layouts/application.html.erb
=> Remove redundant edit icon from site footer

app/views/application/_text_area.html.erb, app/views/rooms/_form.html.erb, app/views/rooms/edit.html.erb
While reviewing https://github.com/zinc-collective/convene/pull/2055 I felt Space managers might be interested to know how `Description` would be used. 
Before: 
After:
=> Adds section description hint and makes styling consistent

app/models/room.rb, spec/factories/room.rb
- https://github.com/zinc-collective/convene/issues/1988
Apparently, some of the Expanse Quotes are quite long; making them [ill-suited for a 300 character limited
field](https://github.com/zinc-collective/convene/actions/runs/7403679313/job/20145303706?pr=2079).
This shortens those down so they don't explode.
=> 🐛🔨 `Section`: Shorten Factory Generated `Room#description`

app/assets/stylesheets/components/button.scss, app/components/button_component.html.erb, app/components/button_component.rb, app/components/svg_component.rb, app/views/spaces/_agreements.html.erb, app/views/spaces/_website_settings.html.erb, config/locales/agreement/en.yml, spec/components/button_component_spec.rb
This makes it possible for form buttons to look the same as buttons created via the `ButtonComponent`, by using the same CSS classes.
It also:
* updates the look of the buttons in the Agreements section of space management, so that they use SVG icons
* adds the missing `:money` SVG icon
* documents where we've been getting the icons from
=> Make all buttons look uniform, no matter if they use the `ButtonComponent` or not

app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/marketplaces_controller.rb, spec/furniture/marketplace/configuring_square_system_spec.rb
=> Displays flash messages on the Marketplace

app/components/card_component.html.erb, app/components/card_component.rb
- https://github.com/zinc-collective/convene/issues/2110
This is perhaps unnecessary; since `<header>` tags are easy to write; but maybe it's actually useful?
=> ✨`CardComponent`: Has a Header Slot

app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/notification_method_component.html.erb, app/furniture/marketplace/payment_settings/index.html.erb, app/furniture/marketplace/product_component.html.erb, app/furniture/marketplace/tax_rate_component.html.erb
This gets rid of all our custom footers/headers in the CardComponents in the `Marketplace`; which feels a little like brushing teeth?
=> 🌸🧹 `Marketplace`: Lean on CardComponent's Footer/Headers

app/components/card_component.html.erb
- https://github.com/zinc-collective/convene/issues/2110
If we enforce a gap at the card level, it makes it hard to format things nicely in contexts where there should not be a gap between the header and footer.
The `justify-between` is "enough" to ensure that the footer sticks to the bottom of the card, and the `header` and `footer` both provide padding.
So no need to set that intention + enforce it multiple places; and this place seemed like the one that was least tailorable to the immediate usage context.
The difference is subtle-if-not-invisible; but if you check out main and refresh then check out this branch and refresh then there is a difference!
=> 🌸 `Components`: `Card` does not need a `gap-y`

app/furniture/marketplace/product_component.html.erb, app/furniture/marketplace/product_component.rb, spec/furniture/marketplace/selling_products_system_spec.rb
This, I think, looks a lot nicer. It also presumes a 16:9 aspect ratio; which feels more "normal"
=> 🌸 `Marketplace`: `Product::Photo` Better handling of aspect ratio / resolution

app/furniture/marketplace/product_component.rb
-  https://github.com/zinc-collective/convene/issues/1428
Apparently `resize_to_limit` does not actually enforce the aspect ratio
This ensures they are always the aspect ratio we want them to be.
=> 🌸 `Marketplace`: `Product#hero_image` is always 16:9

app/furniture/marketplace/cart_products_controller.rb, spec/furniture/marketplace/cart_products_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/2155
Now that the Marketplace lives inside a TurboFrame, we don't need the turbo streams.
Extracted from https://github.com/zinc-collective/convene/pull/2072
=> 🧹 `Marketplace`: `Cart` no longer uses TurboStreams

app/furniture/marketplace/cart_product.rb, app/furniture/marketplace/cart_product/quantity_picker.rb, app/furniture/marketplace/cart_product/quantity_pickers/_quantity_picker.html.erb, app/furniture/marketplace/cart_product_component.html.erb, app/furniture/marketplace/cart_product_component.rb, app/furniture/marketplace/locales/en.yml, spec/furniture/marketplace/buying_products_system_spec.rb, spec/furniture/marketplace/cart_product_component_spec.rb
- https://github.com/zinc-collective/convene/issues/2155
This gets rid of a bunch of nonsense from the `CartProductComponent`, and tees up some parts that I use in the `Menu::ProductComponent`
Extracted from: https://github.com/zinc-collective/convene/pull/2072/
=> 🧹 `Marketplace`: Simplify changing `Product` quantities in `Cart`

.github/workflows/test-convene-journal.yml, app/furniture/journal/entries/_form.html.erb, app/furniture/journal/entry.rb, app/furniture/journal/entry_policy.rb, db/migrate/20240129014151_journal_add_description_to_entry.rb, db/schema.rb, spec/furniture/journal/entry_spec.rb, spec/furniture/journal/writing_entries_system_spec.rb
- When https://github.com/zinc-collective/convene-journal/issues/2, add an https://github.com/zinc-collective/convene-journal/issues/10 so we can eventually display it when https://github.com/zinc-collective/convene-journal/issues/4
=> ✨ `Journal`: `Author` provides `Entry#summary`

app/components/svg_component.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/routes.rb, app/furniture/marketplace/vendor_representative.rb, app/furniture/marketplace/vendor_representative_policy.rb, app/furniture/marketplace/vendor_representatives/_form.html.erb, app/furniture/marketplace/vendor_representatives/index.html.erb, app/furniture/marketplace/vendor_representatives/new.html.erb, app/furniture/marketplace/vendor_representatives_controller.rb, db/migrate/20240207040004_marketplace_create_vendor_representatives.rb, db/schema.rb, spec/furniture/marketplace/vendor_representatives_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2044
OK this should probably be split into a number of smaller steps, each with reasonable test coverage; but I wanted to get something working so we can turn the keys over to the folks at Oaklandia.
This makes it so:
- A `Neighborhood` `Operator` or `Space` `Member` can add a `VendorRepresentative` to a `Marketplace`
- The `VendorRepresentative` can add, remove, and update `Products`
YOLO YOLO YOLO
=> ✨🥗 `Marketplace`: `VendorRepresentative` manages `Products`

app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/buying_products_system_spec.rb, spec/furniture/marketplace/marketplace_spec.rb
- https://github.com/zinc-collective/convene/issues/2198
When we added [archiving delivery areas], I didn't take into account that `Marketplace#cart_for_shopper` was checking against all the delivery areas.
This fixes that and adds a system spec to make sure we can still checkout after!
[archiving delivery areas]: https://github.com/zinc-collective/convene/pull/2024
=> 🐞🔨`Marketplace`: `Buying Products` with one unarchived `DeliveryArea`

app/assets/stylesheets/actiontext.css, app/assets/stylesheets/application.postcss.css, app/javascript/application.js, app/views/active_storage/blobs/_blob.html.erb, app/views/layouts/action_text/contents/_content.html.erb, db/migrate/20240216213129_create_action_text_tables.action_text.rb, db/schema.rb, package.json, spec/rails_helper.rb, spec/spec_helper.rb, yarn.lock
- https://github.com/zinc-collective/convene/pull/2200#pullrequestreview-1879198110
Markdown is cool, but it's nerd-forward.
ActionText is a much more human-friendly way of implementing rich text in Rails applications.
I don't know enough about [Trix] to know if it will work in multi-user contexts; or how it will work with rich-embeds, ala Notion or Google Docs
But I think it's a good-enough-default for now; and if we get to the point where embeddables or multi-user editing of a field is important we can figure that out.
ETA: This is a direct output of `bin/rails action_text:install` and `bin/rails db:migrate`; since I didn't want to conflate structural changes with behavioral changes.
[Trix]: https://trix-editor.org/
=> ⚙️ `Gizmos`: Support `ActionText`

app/assets/stylesheets/base/layout.scss, app/models/media.rb, app/views/rooms/_room.html.erb
- https://github.com/zinc-collective/convene/issues/1961
This brings the hero image to the Section, and makes it take up a reasonable amount of space.
=> 🌸 `Section#hero_image`: takes little real-estate

app/views/spaces/_agreements.html.erb, app/views/spaces/_utilities.html.erb, app/views/spaces/_website_settings.html.erb
- https://github.com/zinc-collective/convene/issues/252
- https://github.com/zinc-collective/convene/issues/1513
Remove Moar italics! MOAR!
=> 🌸 `Space`: De-italicize help-text on `Space#edit`

app/components/svg_component.rb, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/management_component.rb, spec/furniture/marketplace/management_component_spec.rb
- https://github.com/zinc-collective/convene/issues/2220
The icons for `TaxeRates#index` and `Flyers#show` were the same, plus `Products#index` will conflict with `Tags#index`.
So now `Products#index` is :cake: and `Flyers#show` is :qr_code:
While I was doing this, I also made the following tidyings:
- ✨ `SvgComponent` has `#building_storefront` icon!
- ✨ `SvgComponent` has `#qr_code` icon!
- 🧹 `SvgComponent` icon-method names match Heroicon's label!
- 🧹 `SvgComponent#cake` does not need a wrapping `<svg ...>` tag!
- 🥗 `ManagementComponent` has every link it's supposed to
- 🧹 `ManagementComponent::Spec` uses `have_link` instead of `have_css`
- 🧹 `ManagementComponent` eliminates usage of `ButtonComponent`
We originally added the `ButtonComponent` to inject the tailwind CSS classes in Ruby, …
=> 🌸 `Marketplace`: Improve `ManagementComponent` iconography

app/assets/stylesheets/application.postcss.css, app/assets/stylesheets/extensions/pagy.scss, app/furniture/journal/journals/_journal.html.erb, app/furniture/marketplace/orders/index.html.erb, app/helpers/pagy_helper.rb, app/views/neighborhoods/show.html.erb
- https://github.com/zinc-collective/journal/issues/4
- https://github.com/zinc-collective/convene/issues/1661
- https://github.com/zinc-collective/convene/issues/2216
With the Pagy 7 upgrade; the helper I wrote so we could add spacing between the Pagination links broke.
This switches out from doing an in-ruby style override to an in-css style override.
=> 🐞🔨 `Pagination`: Fix missing translation error for `Next` and `Previous` links

app/furniture/journal/keywords/show.html.erb
- https://github.com/zinc-collective/journal/issues/5
Another de-italicization!
=> 🌸 `Journal`: Remove italics from `Keyword`

app/furniture/marketplace/product.rb, db/migrate/20240222004148_remove_marketplace_products_description.rb, db/schema.rb, lib/tasks/release.rake
- https://github.com/zinc-collective/convene/issues/2197
`ActionText` stores it's data in it's own table; so we don't need it.
=> 🧹 `Marketplace`: Remove `Product#description` column

spec/factories/furniture/journal.rb
This should prevent occasional test failures caused by trying to create a duplicate keyword, such as the one in https://github.com/zinc-collective/convene/actions/runs/8070888101/job/22049297163
=> 🧹 Ensure that factory for Journal::Keyword always uses a unique canonical keyword

app/furniture/layouts/marketplace.html.erb, app/furniture/marketplace/orders/_order.html.erb, app/furniture/marketplace/orders/index.html.erb
Changes are the same for guest or logged in shoppers.
Before
After
=> Cleans up Order and Order history UI

app/furniture/marketplace/order/email_receipt_component.html.erb, spec/factories/furniture/marketplace.rb
Because Mailers don't receive the request context, url generation in mailer templates is less straightforward than in templates backed by a controller. `*_url` helpers are recommended so that Rails can construct an absolute path. But In our case we need the `polymorphic_url` which works best with our `location` methods. 
See: https://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views. 
In addition to fixing the url, this PR includes a bite-sized effort to harden the associations in the Marketplace factories. While we pair debugged the mailer previews in the browser, @anaulin and I noticed inconsistencies in the data which prevented us from easily verifying the url was correct -- trying to visit the link as a guest or logged-in as the shopper was …
=> Fixes absolute paths in Marketplace mailers #2243 

app/furniture/marketplace/bazaar.rb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/policy.rb, app/furniture/marketplace/product.rb, app/furniture/marketplace/product/title_component.html.erb, app/furniture/marketplace/product_tag.rb, app/furniture/marketplace/products/_form.html.erb, app/furniture/marketplace/routes.rb, app/furniture/marketplace/tag.rb, app/furniture/marketplace/tag_policy.rb, app/furniture/marketplace/tags/_form.html.erb, app/furniture/marketplace/tags/index.html.erb, app/furniture/marketplace/tags/new.html.erb, app/furniture/marketplace/tags_controller.rb, db/migrate/20240208025354_create_marketplace_product_tags.rb, db/schema.rb, spec/furniture/marketplace/product_tags_system_spec.rb, spec/furniture/marketplace/tag_spec.rb
- https://github.com/zinc-collective/convene/issues/2189
Products can now be tagged with things like `Gluten Free` or `Vegan`,
and will show up as such under Product listings
=> ✨ `Marketplace`: Add `Product#tags`

app/furniture/section_navigation/section_navigations/_section_navigation.html.erb
- https://github.com/zinc-collective/convene/issues/1988
This is closer to the styling we had earlier, but without the bright orange, and without a change during hover.
(journal card shows hover state)
(journal card shows hover state)
=> 🌸 Make arrow in section navigation look more like a little button

app/components/select_component.html.erb, app/components/select_component.rb, app/views/spaces/_sections.html.erb
Yes, I _do_ remember we have an [outstanding issue](https://github.com/zinc-collective/convene/issues/2082) for a hint partial 😅. This was a small detour while working through how I want to present header and footer configuration for #2266 and my brain keeps forgetting what the _entrance_ field is.
After:
=> Adds a label and hint to the entrance field in the Space > Sections configuration form

app/furniture/section_navigation/section_grid_component.html.erb, app/furniture/section_navigation/section_grid_component.rb, app/furniture/section_navigation/section_navigations/_section_navigation.html.erb
* https://github.com/zinc-collective/convene/issues/1988
This PR refines the look of the section navigation component:
* when at least one of the sections has an image an others don't, it inserts a colored image placeholder in all the cards that don't have an image
* when at least one of the sections has a description text, it makes sure that all the cards have the same description height, even if they don't have a description text
=> Improve look of section navigation cards when at least one section has an image

app/furniture/section_navigation/section_grid_component.rb, app/models/room.rb
* https://github.com/zinc-collective/convene/issues/1988
Followup to https://github.com/zinc-collective/convene/pull/2302 to correctly identify if a Room has a hero image, taking into account that sometimes a Room might have a hero image association, but the associated Media object might not have an attachment.
A related question that this PR doesn't address is: why do we have Media objects with no attachment?
=> Fix logic for determining if a Room has a hero image (aka header image)

Gemfile, Gemfile.lock
Part of work for https://github.com/zinc-collective/convene/pull/2361. Should be merged first.
=> Adds positioning Gem 

docker-compose.yml
The top-level version keyword in the docker-compose.yml spec has been deprecated, and using now triggers a warning. See: https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md
=> Remove obsolete docker-compose top-level `version` keyword

.github/workflows/test-convene-web.yml
This is to get rid of these warnings:
=> Update GitHub workflows to use latest action versions

spec/furniture/marketplace/buying_products_system_spec.rb
I'm not sure why or what for was this necessary in the past, but it seems it is no longer available in the Stripe checkout form.
=> [FIX BUILD] Remove reference to `enableStripePass` hidden checkbox in system tests

.github/workflows/test-convene-web.yml
This step often fails due to intermittent network records, making our CI extra-flaky.
I'm hoping throwing in the occasional retry will make things less flaky without adding too much delay to the CI.
=> Add up to 3 retries to the CI step that installs the Stripe CLI

Gemfile.lock
This is to prevent the annoying diff I get every time I run `bundle install` locally on this project. This shouldn't affect developers who are not on a darwin system.
=> Update Gemfile.lock to contain platform-specific lines for Darwin installations

spec/furniture/marketplace/buying_products_system_spec.rb
At least one of the CI failures appears to be caused by changes to the Stripe Checkout flow which now defaults to asking them to save their Stripe Link contact info
=> Ensure "Remember Me for Stripe Link" Checkbox is unchecked

config/initializers/redis.rb, config/initializers/sidekiq.rb
See:
- https://help.heroku.com/HC0F8CUS/redis-connection-issues
- https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-ruby
This should fix our Redis connection, but I don't think it will recover anything that failed to get written to redis...
=> Upgraded Redis requires SSL, and Heroku self-signs their certs

config/initializers/redis.rb, config/initializers/sidekiq.rb
- #2625
Sooo, apparently the documentation provided by Heroku is not-quite-accurate; or perhaps I am not following it right, but we have `RedisClient` not `Redis`
=> RedisClient is the appropriate one, not Redis

app/furniture/marketplace/cart/delivery_area_component.html.erb, app/furniture/marketplace/cart/delivery_area_component.rb, app/furniture/marketplace/delivery.rb, app/furniture/marketplace/delivery_area.rb, app/furniture/marketplace/delivery_area_component.html.erb, app/furniture/marketplace/delivery_area_component.rb, app/furniture/marketplace/delivery_area_policy.rb, app/furniture/marketplace/delivery_areas/_form.html.erb, app/furniture/marketplace/order.rb, app/views/application/_percentage_field.html.erb, db/migrate/20241010004915_marketplace_add_fee_as_percentage_to_delivery_areas.rb, db/schema.rb, spec/factories/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/delivery_area_component_spec.rb, spec/furniture/marketplace/delivery_areas_controller_request_spec.rb, spec/furniture/marketplace/delivery_areas_system_spec.rb, spec/furniture/marketplace/delivery_spec.rb, spec/furniture/marketplace/order_spec.rb
- https://github.com/zinc-collective/convene/issues/2641
Todo:
April has adjusted her fee schedule, and catering orders are now 12% and regular orders are $10 flat. This simplifies things quite a bit; hooray! But alas, we had already built out stuff to support different fees for every vendor and across regions (i.e. SF it's $20, Oakland it's $10)
I think it's probably for the best to leave that flexibility in for now, and have updated it so we now have another attribute for how to calculate fees.
I've made the Executive Decision to treat these fees as cumulative (i.e. $10 plus 12%) if both the `DeliveryArea#price` and the `DeliveryArea#fee_as_percentage` are set; rather than trying to figure out how to break ties or validate only one is set or whatever. This may be a poor decision.
=> `Marketplace`: `DeliveryArea` fees as a percentage

app/furniture/marketplace/order/mailer.rb, app/furniture/marketplace/order/placed_mailer.rb, app/furniture/marketplace/order/received_mailer.rb, spec/furniture/marketplace/order/placed_mailer_spec.rb, spec/furniture/marketplace/order/received_mailer_spec.rb
- https://github.com/zinc-collective/convene/issues/2639
When I placed my order last week, the replies started going to Convene Support, rather than the customer / seller.
This should reduce that happening.
=> `Marketplace`: Set `reply_to` on `Order::Mailer`s

app/views/layouts/application.html.erb
- Fixes https://github.com/zinc-collective/convene/issues/2640
=> A bit of spaciousness on small screens

app/furniture/marketplace/cart_product/notes/_form.html.erb, app/furniture/marketplace/cart_product/notes/_note.html.erb, app/furniture/marketplace/cart_product/notes/edit.html.erb, app/furniture/marketplace/cart_product/notes/new.html.erb, app/furniture/marketplace/cart_product/notes/show.html.erb, app/furniture/marketplace/cart_product/notes_controller.rb, app/furniture/marketplace/checkouts/show.html.erb, app/furniture/marketplace/order/email_receipt_component.html.erb, app/furniture/marketplace/routes.rb, db/migrate/20241017003307_marketplace_add_note_to_cart_product.rb, db/schema.rb, spec/factories/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/buying_products_system_spec.rb
=> Shopper may add Notes to a Product in their Cart on checkout

Gemfile, Gemfile.lock, config/environments/production.rb
This brings our production logs to a more browsable starting point
=> Tame our log output

app/javascript/sentry.js
The `TypeError: Load failed` error is a bit of  a mess to diagnose and debug. I could take some guesses (Turbo, for example, may be doing pre-fetching) but rather than (potentially) spinning my wheels guessing I'm going to get some more data before digging in.
See:
- https://github.com/zinc-collective/convene/issues/2705
- https://zinc-collective.sentry.io/issues/6036564075/
- https://sentry.io/answers/load-failed-javascript/
=> Capture console errors in Sentry for debugging
