.gitignore, README.md, bin/setup, bin/test, features/infrastructure/hosting-jitsi.feature, package-lock.json, package.json
See: https://github.com/zinc-collective/convene/issues/2
=> 🔧📝✅ Install cucumber-js and move feature definition to repo

features/infrastructure/hosting-zulip.feature, package.json
Including Zulip feature request and update npm test command to use the unscheduled tag.
=> Zulip feature request.

README.md
See: https://github.com/zinc-collective/convene/issues/10
In order to make it clearer who we are building Convene for,  I've added the link to our
persona definition document to the README
=> Link to Persona documentation

infrastructure/clients/convene-test.zinc.coop/infrastructure.tf, infrastructure/clients/convene-test.zinc.coop/public.tfvars, infrastructure/clients/meet.zinc.coop/public.tfvars, infrastructure/jitsi/provision
I wrote this to confirm building & provisioning a new convene instance on its own subdomain.
#2
=> Setup convene-test client for automatic test setup

infrastructure/jitsi/install, infrastructure/jitsi/post-release
Connects: #23 
Remove Jitsi watermark
=> Remove Jitsi watermark icon

infrastructure/jitsi/install
Restart instance nightly as a temp solution to stabilize Convene.
=> Restart instance every PST midnight

infrastructure/clients/convene-test-vultr.zinc.coop/infrastructure.tf, infrastructure/clients/convene-test-vultr.zinc.coop/public.tfvars, infrastructure/clients/convene-test-vultr.zinc.coop/secrets-example.tfvars, infrastructure/clients/convene-test.zinc.coop/secrets-example.tfvars, infrastructure/features/video-workspaces.feature, infrastructure/jitsi/provision, infrastructure/jitsi/vultr.json
* TODO: Automatically fetch snapshot id to provision server
* TODO: Still need to figure out a way to get ssh_key_ids from terraform before packer build?
=> Spike on using Vultr

.gitignore, features/locking-rooms.feature, features/parameter-types/README.md, features/parameter-types/actors.js, features/parameter-types/rooms.js, features/steps/room_steps.js, package.json
I sprouted some initial parameter types so that we can drape additional
behavior for particular actors or rooms and what not.
=> Document Locking Rooms feature

convene-web/app/javascript/controllers/room_picker_controller.js, convene-web/app/javascript/controllers/video_room_controller.js, convene-web/app/javascript/src/custom_components.scss, convene-web/app/javascript/src/custom_components/meeting_room.scss, convene-web/app/javascript/src/video_room.js, convene-web/app/views/workspaces/_room_card.html.erb, convene-web/app/views/workspaces/show.html.erb, convene-web/package.json, convene-web/yarn.lock
Still need some help on using `EventTarget`.
My understanding is we'd like to scope down `document.dispatchEvent` into `someEle.dispatchEvent`.
=> Refactor video room stimulus controller

convene-web/app/javascript/controllers/room_picker_controller.js, convene-web/app/views/workspaces/_room_card.html.erb
Add back video host data attribute to init VideoRoom with video host.
=> Fix null video host

convene-web/.gitignore, convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/Procfile, convene-web/app/models/demo_workspace.rb, convene-web/app/models/feature.rb, convene-web/app/models/workspace.rb, convene-web/bin/setup, convene-web/db/seeds.rb, convene-web/lib/tasks/release.rake, convene-web/spec/models/demo_workspace_spec.rb, features/demoing-convene.feature, features/parameter-types/rooms.js, features/parameter-types/workspaces.js, features/steps/deployment_steps.js, features/steps/room_steps.js, features/steps/workspace_steps.js
See https://github.com/zinc-collective/convene/issues/61
=> Sprout a Convene Demo Workspace

convene-web/app/javascript/controllers/video_room_controller.js, convene-web/app/javascript/src/video_room.js, convene-web/app/models/workspace.rb, convene-web/app/views/rooms/show.html.erb
=> Move end call button back to jitsi iframe

convene-web/app/models/workspace.rb, convene-web/spec/models/workspace_spec.rb
Follow up PR on https://github.com/zinc-collective/convene/pull/80#discussion_r468875669
=> Test allow mulitple nil branded_domain

convene-web/.env.example, convene-web/app/models/system_test_workspace.rb, convene-web/app/views/workspaces/_room_card.html.erb, features/entering-rooms.feature, features/page-objects/Page.js, features/page-objects/WorkspacePage.js, features/parameter-types/rooms.js, features/parameter-types/workspaces.js, features/steps/room_steps.js, features/steps/workspace_steps.js, features/support/env.js, package-lock.json, package.json
Would love to get some early feedback out the first system test to see if this is the correct direction.
=> System test `Entering Room via Room Picker from Workspace Dashboard`

convene-web/app/javascript/controllers/video_room_controller.js, convene-web/app/javascript/src/video_room.js, features/entering-rooms.feature, features/page-objects/WorkspacePage.js, features/steps/generic_step.js
=> Fix a bug where hitting brower back button would show two jitsi iframe

CHANGELOG.md, convene-web/CHANGELOG.md, infrastructure/CHANGELOG.md
Part of #59 
I used https://github.com/mperham/sidekiq/blob/master/Changes.md as a ref for CHANGELOG format and think once we cut release, we can move items in `HEAD` to versions.
=> Checkin web & infra changelog

infrastructure/clients/zinc/infrastructure.tf
We're at the point where a single videobridge isn't enough to keep our
clients at capacity. So I've tripled the videobridges performance.
=> Bump the zinc-videobridge to a dual-cpu server

convene-web/app/controllers/application_controller.rb, convene-web/app/controllers/rooms_controller.rb, convene-web/app/helpers/rooms_helper.rb, convene-web/app/javascript/packs/application.js, convene-web/app/javascript/src/custom_components.scss, convene-web/app/javascript/src/custom_components/button.scss, convene-web/app/javascript/src/custom_components/form.scss, convene-web/app/javascript/src/custom_components/header.scss, convene-web/app/models/room.rb, convene-web/app/models/system_test_workspace.rb, convene-web/app/views/layouts/_header.html.erb, convene-web/app/views/layouts/application.html.erb, convene-web/app/views/layouts/video_room.html.erb, convene-web/app/views/rooms/show.html.erb, convene-web/app/views/rooms/waiting_room.html.erb, convene-web/app/views/workspaces/_room_card.html.erb, convene-web/config/routes.rb, convene-web/package.json, convene-web/spec/models/room_spec.rb, convene-web/yarn.lock, features/locking-rooms.feature, features/page-objects/WorkspacePage.js, features/steps/room_steps.js
* Implementing: https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/04ee266e-931b-4bde-bcf9-af94c7ac444e/
=> User can enter locked room

convene-web/app/models/demo_workspace.rb
=> Seed a locked demo room

features/membership-and-ownership.feature
See: https://github.com/zinc-collective/convene/issues/117
=> Sketch out Feature Definition for Space Membership

features/purchasing-space.feature
https://github.com/zinc-collective/convene/issues/8
=> Sketch out feature definition for purchasing a space

features/membership-and-ownership.feature
I wasn't sure if we would like this scenario but this is pretty common on
a lot of applications.
=> Adding Email Invitation Code Times out Scenario

features/locking-rooms.feature
See: https://github.com/zinc-collective/convene/issues/40
=> Unwip entering locked-rooms feature

convene-web/app/javascript/src/custom_components/icons.scss
Forgot to checkin `icons.scss`.
=> Checkin missing icons scss file

convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/app/controllers/rooms_controller.rb
Connects: https://github.com/zinc-collective/convene/issues/40
* Wrong type casting on string vs symbol
=> Fixing flow for editing a locked room

features/locking-rooms.feature, features/page-objects/RoomSettingPage.js, features/page-objects/WorkspacePage.js, features/steps/room_steps.js
Connects: https://github.com/zinc-collective/convene/issues/40
Co-authored-by: KellyAH <KellyAH@users.noreply.github.com>
Co-authored-by: CJ Joulain <cjoulain@users.noreply.github.com>
=> Feature test unlock room

features/page-objects/RoomSettingPage.js, features/page-objects/WaitingRoom.js
Decompose the responsibility for interacting with the WaitingRoom from the RoomSettingsPage, resolve concern on https://github.com/zinc-collective/convene/pull/157/files#r533904802
=> Separate WaitingRoomPage from RoomSettingPage

CONTRIBUTING.md, README.md
See: https://github.com/zinc-collective/convene/issues/20
=> Improve Contributing Guide

convene-web/Gemfile.lock, convene-web/app/helpers/rooms_helper.rb, convene-web/app/lib/furniture/breakout_tables.rb, convene-web/app/models/furniture_placement.rb, convene-web/app/models/room.rb, convene-web/app/models/system_test_workspace.rb, convene-web/app/views/furniture/breakout_tables/_in_room.html.erb, convene-web/app/views/furniture/breakout_tables/show.html.erb, convene-web/app/views/rooms/show.html.erb, convene-web/config/environments/test.rb, convene-web/config/routes.rb, convene-web/db/migrate/20201224010740_initial_furniture_architecture.rb, convene-web/db/schema.rb, convene-web/spec/models/furniture_placement_spec.rb, convene-web/spec/rails_helper.rb, features/furniture/breakout-tables.feature
https://github.com/zinc-collective/convene/issues/154
=> Room Occupant may take a Seat at a Breakout Table

README.md, convene-web/README.md
Fix broken development setup links.
=> Fix README links

convene-web/app/javascript/packs/application.js, convene-web/app/javascript/src/application.scss, convene-web/app/javascript/src/custom_components/button.scss, convene-web/app/javascript/src/custom_components/form.scss, convene-web/app/javascript/src/custom_components/header.scss, convene-web/app/javascript/src/custom_components/room_card.scss, convene-web/app/javascript/src/custom_components/room_edit.scss, convene-web/app/views/furniture/breakout_tables/show.html.erb, convene-web/app/views/passwordless/sessions/new.html.erb, convene-web/app/views/rooms/edit.html.erb, convene-web/app/views/rooms/show.html.erb, convene-web/app/views/waiting_rooms/show.html.erb, convene-web/tailwind.config.js
See: https://github.com/zinc-collective/convene/issues/23
Co-authored-by: Whitney <roseaboveit@users.noreply.github.com>
=> Global color update

features/identification.feature, features/page-objects/RoomSettingPage.js, features/page-objects/WaitingRoomPage.js
https://github.com/zinc-collective/convene/issues/118
The goal here is to set up the mental model for how Convene does
Identification in a way that designers, developers and testers can use
to deepen their understanding of how identification, authentication, and
authorization work both as general information security concepts, as
well as within Convene.
=> Clearer framing for Identification and Authentication

features/identification.feature, features/page-objects/SignInPage.js, features/steps/identification_steps.js
Created a SignInPage.js for modeling Sign In in Step Definitions
Co-Authored-By: Ana Ulin <anaulin@users.noreply.github.com>
Co-Authored-By: Zee Spencer <zspencer@users.noreply.github.com>
:
=> Implements Given step for Email Identification feature test

CONTRIBUTING.md, features/space-membership.feature
Worked on https://github.com/zinc-collective/convene/issues/117 with @cjoulain and @zspencer in a Testing Mob session.
=> Docs and Test: 117/space membership/start tdd

features/furniture.feature
Also added developer context for understanding furniture.
=> Added a furniture.feature file to describe actions on furniture

features/furniture.feature, features/furniture/check-drop-off.feature
See: https://github.com/zinc-collective/convene/issues/186
=> Initial draft of feature file for check drop off feature

convene-web/bin/run
This addresses https://github.com/zinc-collective/convene/issues/206
=> Add message about Rails host and port to bin/run

convene-web/spec/tasks/release_after_build_spec.rb
Making sure release won't fail because of bad release task.
=> Test release task

.gitignore, .vscode/extensions.json, .vscode/ltex.disabledRules.en-US.txt, .vscode/settings.json
Turns out, I had tuned my VS Code but failed to share!
=> Share Project-level VS Code Settings

convene-web/app/controllers/spaces_controller.rb, convene-web/app/models/blueprint.rb, convene-web/app/models/space.rb, convene-web/app/models/system_test_space.rb, convene-web/app/views/spaces/show.html.erb, convene-web/config/breadcrumbs.rb, convene-web/db/migrate/20210417233343_add_entrance_to_spaces.rb, convene-web/db/schema.rb, convene-web/spec/models/space_spec.rb, features/spaces.feature
Entrances are kind of a landing page for a Space, so that the Spaces
home page can have furniture.
=> Spaces may have an Entrance

bin/setup
Check if a brew package is installed using `brew ls --versions`
Not all packages is in `PATH`
=> Do not keep installing shared-mime-info

convene-web/app/models/room.rb
This resolves a deprecation warning in the application
=> `<<` into errors is not supported anymore

convene-web/app/models/blueprint.rb, convene-web/app/models/demo_space.rb, convene-web/app/models/furniture_placement.rb, convene-web/app/models/system_test_space.rb, convene-web/bin/setup, convene-web/db/seeds.rb, convene-web/lib/tasks/release.rake
- Added a Blueprint for Zinc's meet.zinc.coop domain
- Blueprints can add members using either a hash or a Person
- Call `release:after_build` as part of `bin/setup`
=> Clean up how population of the development and prod databases

README.md
The README was a bit out of date, so I took the time to muck about cleaning it up.
=> Reframe away from video

CONTRIBUTING.md, convene-web/app/views/spaces/edit.html.erb
Also tweaked dev setup documentation for clarity.
Co-authored-by: Egbet Abraha <eg-bet@users.noreply.github.com>
Co-authored-by: CJ Joulain <cjoulain@users.noreply.github.com>
=> Fixed bug when rendering the space edit page.

convene-web/config/application.rb, convene-web/config/locales/authenticated_session/en.yml, convene-web/config/locales/en.yml, convene-web/config/locales/waiting_room/en.yml
- Decomposes locale files on a per-domain basis
=> Use 'Sign in' when submitting the AuthenticatedSession form

convene-web/app/assets/config/manifest.js, convene-web/config/routes.rb
Heroku wasn't able to deploy Convene because Administrate was trying to compile it's assets, because I forgot to remove it :X
=> Clean up more Administrate issues

convene-web/app/lib/utilities/plaid.rb, convene-web/app/lib/utilities/plaid/_form.html.erb, convene-web/app/lib/utilities/utility.rb, convene-web/app/models/utility_hookup.rb, convene-web/app/views/utility_hookups/_form.html.erb, convene-web/db/migrate/20210710224638_encrypt_utility_hookup_configuration.rb, convene-web/db/schema.rb, convene-web/spec/factories/utility_hookup.rb, convene-web/spec/models/utility_hookup_spec.rb, convene-web/spec/requests/spaces/utility_hookups_spec.rb, features/utilities/plaid.feature
See: https://github.com/zinc-collective/convene/issues/186
Also, Utility Hookup configuration is now encrypted at rest; which
should make things a bit safer.
Co-authored-by: Ana Ulin <ana@ulin.org>
=> Plaid can be configured with secrets and environment

convene-web/app/javascript/controllers/check_dropbox_controller.js, convene-web/app/lib/furniture/base_controller.rb, convene-web/app/lib/furniture/breakout_tables_by_jitsi/controller.rb, convene-web/app/lib/furniture/check_dropbox.rb, convene-web/app/lib/furniture/check_dropbox/_in_room.html.erb, convene-web/app/lib/furniture/check_dropbox/checks_controller.rb, convene-web/app/lib/furniture/furniture_controller.rb, convene-web/app/lib/utilities/plaid.rb, convene-web/app/lib/utilities/plaid/_form.html.erb
We still have to:
But we can do that in a later PR!
=> Check Drop Box: Exchange Plaid's Public Token for Access Token

convene-web/app/lib/furniture/check_dropbox.rb, convene-web/app/lib/furniture/check_dropbox/_in_room.html.erb, convene-web/app/lib/furniture/check_dropbox/check.rb, convene-web/app/lib/furniture/check_dropbox/checks_controller.rb, convene-web/app/lib/furniture/placeable.rb, convene-web/app/lib/item.rb, convene-web/app/lib/utilities/plaid.rb, convene-web/app/models/furniture_placement.rb, convene-web/app/models/item_association.rb, convene-web/app/models/item_record.rb, convene-web/app/models/utility_hookup.rb, convene-web/db/migrate/20210814223027_create_item_records.rb, convene-web/db/schema.rb, convene-web/spec/factories/item_records.rb, convene-web/spec/models/item_record_spec.rb
=> Check Dropbox: Persist Checks to the Database

convene-web/CHANGELOG.md
See: https://github.com/zinc-collective/convene/issues/118
=> Write initial release notes for Authentication

convene-web/Gemfile, convene-web/Gemfile.lock, convene-web/app/javascript/packs/application.js, convene-web/app/lib/furniture/check_dropbox.rb, convene-web/app/lib/furniture/check_dropbox/_in_room.html.erb, convene-web/app/lib/furniture/check_dropbox/checks/_form.html.erb, convene-web/app/lib/furniture/check_dropbox/checks/create.html.erb, convene-web/app/lib/furniture/check_dropbox/checks/index.html.erb, convene-web/app/lib/furniture/check_dropbox/checks_controller.rb, convene-web/app/lib/furniture/placeable.rb, convene-web/app/models/item_association.rb, convene-web/app/views/layouts/application.html.erb, convene-web/config/cable.yml, convene-web/package.json, convene-web/yarn.lock
Adds a little bit more progress to "Check Dropbox" furniture (issue  #186):
* Adds Turbo to support swapping out bits of HTML without full page reloads.
* Uses Turbo to wrap the check dropbox UI.
* Adds UI bits to display feedback after a check has been deposited.
* Adds an index view to display all deposited checks to a Space Member.
=> Show feedback on Check deposit, add index of deposited checks

features/harness/Component.js, features/harness/RoomEditPage.js, features/lib/AccessLevel.js, features/steps/room_steps.js
On the one hand, a "Given" probably oughta take responsibility for making sure the data is in the right state.
On the other hand, it'd be lovely if we had an API (or were using cucumber-rails) so that we didn't have to do the changes via the UI.
=> Lock/Unlock the Space based upon the Given

docker-compose.yml
This explains why my computer is silly.
=> Persist Postgresql data between docker-compose restarts

convene-web/app/lib/furniture/check_dropbox/_in_room.html.erb, convene-web/app/lib/furniture/check_dropbox/check.rb, convene-web/app/lib/furniture/check_dropbox/checks/index.html.erb, convene-web/app/lib/utilities/plaid.rb
See: https://github.com/zinc-collective/convene/issues/186
Co-authored-by: Ana Ulin <ana@ulin.org>
=> Expose a Check's account number and routing number on the check list

convene-web/app/lib/furniture/check_dropbox.rb, convene-web/app/lib/furniture/check_dropbox/check.rb, convene-web/app/lib/furniture/check_dropbox/checks/index.html.erb, convene-web/app/lib/furniture/check_dropbox/checks_controller.rb, convene-web/app/lib/item.rb, convene-web/app/models/item_association.rb, convene-web/app/models/item_repository.rb, convene-web/spec/models/item_repository_spec.rb
We want to be able to track the status of Checks so we can remove the Items from Plaid eventually.
=> Check Dropoff's have a Status

convene-web/app/javascript/packs/application.js, convene-web/app/javascript/src/components/icons.scss, convene-web/app/views/spaces/_room_card.html.erb, convene-web/app/views/waiting_rooms/show.html.erb, convene-web/package.json, convene-web/yarn.lock, features/harness/RoomCardComponent.js
We are using more emojis for our iconography; instead of font-awesome.
=> Remove FontAwesome as a dependency

app/lib/furniture/check_dropbox/_in_room.html.erb
See: http://github.com/zinc-collective/convene/issues/186
=> Check Dropbox: Only show link to all checks to those who can see them

app/furniture/markdown_text_block/_in_room.html.erb, package.json, spec/furniture/markdown_text_block_spec.rb, tailwind.config.js, yarn.lock
=> [FIX] Make sure Markdown-generated HTML gets styled like HTML

app/assets/stylesheets/base/layout.scss
The gradient was causing some odd issues with different contrast in different
parts of the page. And the gray was a little... gray? So we made it less gray.
=> Remove background gradient, and make things less gray

app/assets/config/manifest.js, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/furniture/furniture_controller.rb, app/themes/desert_dunes/application/_header.html.erb, app/themes/desert_dunes/layouts/application.html.erb, app/themes/desert_dunes/styles.css, app/views/application/_flash_messages.html.erb, app/views/layouts/_header.html.erb, config/application.rb, config/initializers/assets.rb, db/migrate/20220323030401_add_theme_to_spaces.rb, db/schema.rb, tailwind.config.js
We had talked briefly about how, if we want to  move momentpark.com off SquareSpace and into Convene, we probably needed a way to give it different colors / typography / layout, so I made it possible for a Space to set a theme, which will then prioritize loading views from the `app/themes/#{space.theme}` directory.
Introducing "Desert Dunes", a totally unique theme!
=> Prototype: Themes!

app/controllers/application_controller.rb
Cleaning up a bit of log noise.
=> Fix Pundit deprecation warning

app/controllers/spaces_controller.rb, app/models/space.rb, app/views/spaces/edit.html.erb, config/locales/space/en.yml, spec/models/space_spec.rb, spec/requests/spaces_request_spec.rb, spec/support/auth_helpers.rb
- ~[ ] Flesh out the Scenario?~
=> Themes may be set by space owner

app/controllers/spaces_controller.rb
Fast follow for PR https://github.com/zinc-collective/convene/pull/623
=> Redirect to Space show page after successful update

app/assets/stylesheets/components/icons.scss, app/themes/desert_dunes/styles.css
Dunes, now with 38% more desertiness! 🏜️
=> Improvements to Desert Dunes theme, icon styling tweak

app/furniture/furniture.rb, app/furniture/livestream.rb, app/furniture/livestream/_form.html.erb, app/furniture/livestream/_in_room.html.erb, features/furniture/livestream.feature
See: https://github.com/zinc-collective/convene/issues/632
This sprouts a new Livestream Furniture, and makes it available to
Rooms.
=> Twitch Livestream may be embedded in a Room

Gemfile, Gemfile.lock, app/models/furniture_placement.rb, spec/factories/furniture_placement.rb, spec/models/furniture_placement_spec.rb
Fixes a bug we noticed while updating furniture in production.
=> Fix handling of FurniturePlacement slot order

app/controllers/spaces_controller.rb, features/steps/space_steps.js
Zee had done some YOLO Berserker Comment Changes in
https://github.com/zinc-collective/convene/pull/594, which (while
useful) didn't actually matter for the work.
This pulls it into it's own PR so the future contributors aren't
confused about why the git commit for the comment change has to do with
Invitations.
=> Tidy up Documentation of the Spaces Controller

.gitignore, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/authentication_methods_controller.rb, app/controllers/spaces_controller.rb, app/models/branded_domain_constraint.rb, app/models/default_space_constraint.rb, config/initializers/rswag-ui.rb, config/initializers/rswag_api.rb, config/routes.rb, spec/requests/authentication_methods_request_spec.rb, spec/requests/spaces_request_spec.rb, spec/support/api_helpers.rb, spec/support/auth_helpers.rb, spec/swagger_helper.rb
=> Refactor: Migrate all API based Specs to Swagger

app/controllers/spaces_controller.rb, app/models/application_serializer.rb, app/models/authentication_method/serializer.rb, app/models/space/factory.rb, app/models/space/serializer.rb
I also went ahead and added rswag so that we can generate API
documentation directly from our rspec tests
https://user-images.githubusercontent.com/50284/164836924-4179bcea-99e4-4c4a-9649-9fdd41c0e6be.mov
.
=> Spaces: API Serializes response Data

features/furniture/caterer-popup.feature.md, features/furniture/delivery-order-form.feature.md
This describes the two main scenarios, opening up a Pop-Up, and Placing
an Order at the Pop-Up.
There's more that could be built (in particular providing Space Owner's
with the ability to upload a Menu) but if we start here it should be
possible to throw together something that could work for Piikup as a
super-tiny proof of concept.
=> Sprout Catering Pop-Up Furniture Feature Definition

app/furniture/furniture.rb
I moved them all to `video_bridge`:
```rb
FurniturePlacement.where(furniture_kind: 'videobridge_by_jitsi').update(furniture_kind: 'video_bridge')
```
=> There are no longer any `videobridge_by_jitsi` Prod FurniturePlacements

app/furniture/spotlight/_in_room.html.erb, app/furniture/spotlight/image_files/edit.html.erb, app/furniture/spotlight/image_files_controller.rb, app/views/furniture_placements/_furniture_placement.html.erb, app/views/rooms/show.html.erb, app/views/spaces/show.html.erb
This may be a bit risky, but the intention here is to make all Furniture
live inside a Turbo Frame, so the "modify in-line" behavior "just works"
=> Always place Furniture inside a TurboFrame

app/furniture/spotlight/_form.html.erb
See: https://github.com/zinc-collective/convene/issues/201
=> Remove the Spotlight form from editing the page

app/views/layouts/_header.html.erb, features/harness/PersonNavigationComponent.js, features/lib/Actor.js, features/lib/MailServer.js, features/spaces/invitations/responding_to_invitations.feature, features/steps/identification_steps.js, features/steps/invitation_steps.js, features/support/assertDisplayed.js
https://github.com/zinc-collective/convene/issues/117
This demostrates that Authenticated people can successfully respond to invitations, as well as proves that nefarious actors cannot respond to invitations to other people.
=> Invitations: Test authenticated and adversarial Invitations

README.md
update readme with anaulin's reccomendations.
Co-authored-by: Neermala Thapa <nirmalathapa@users.noreply.github.com>
Co-authored-by: Zee Spencer <zspencer@users.noreply.github.com
=> update readme with anaulin's reccomendations.

README.md
In [our Q1 2022
Retro](https://github.com/zinc-collective/convene/discussions/737), we
discussed not being clear on the Product, and how that gets in the way
of figuring out what to do in our ensemble sessions.
We took an edit pass on the README, making it more clear that it's an
operating system; and trying to integrate Zee's weird hand wavey
ramble-rants into something that people other than Zee could understand.
=> Try to terse up README and make it more concrete

app/views/rsvps/_ignored.html.erb, app/views/rsvps/show.html.erb, config/locales/rsvp/en.yml, features/harness/InvitationResponsePage.js, features/lib/Invitation.js, features/spaces/invitations.feature, features/steps/invitation_steps.js
- Apply better styling to rsvp ignored page.
-  implement some test steps
Co-authored-by: Neermala Thapa <nirmalathapa@users.noreply.github.com>
=> Apply better styling to rsvp ignored page and implement some test steps

app/models/invitation.rb, config/locales/rsvp/en.yml, spec/models/invitation_spec.rb, spec/models/person_spec.rb
Zee, Naomi and I fixed the test for unignoring an invitation and fixed some of the messaging for the unignore button.
=> Ensemble/ignore invitations  117

app/views/application/_email_field.html.erb, app/views/authenticated_sessions/_form.html.erb
I needed this when building out the Marketplace Furniture Sketch, but
since it's likely that will take more time I wanted to get it merged in
independently
=> Extract `email_field` partial

app/models/invitation.rb, app/models/rsvp.rb, app/views/rsvps/_accepted.html.erb, app/views/rsvps/_expired.html.erb, app/views/rsvps/show.html.erb, app/views/rsvps/update.html.erb, config/locales/invitation/en.yml, config/locales/rsvp/en.yml, features/spaces/invitations/responding_to_invitations.feature, spec/models/invitation_spec.rb, spec/requests/spaces/invitations/rsvp_spec.rb
More progress on https://github.com/zinc-collective/convene/issues/117
=> Invitations: Invitations may Expire

app/views/spaces/edit.html.erb, config/locales/invitation/en.yml, features/spaces/invitations.feature
Thanks @anaulin 😄 
https://github.com/zinc-collective/convene/pull/783
- marks test Revoking Accepted Invitations as built. 
- translates revoking of invitations button
=> Address feedback for revoking invitations #783

config/database.yml, db/migrate/20220807184623_remove_sent_from_invitation_status_enum.rb, db/schema.rb
Initially, I thought the issue was caused by Heroku's recent changes to pg_extras; but maybe it's because values with the enum were still in the database?
Anyway, this fixes it!?
https://devcenter.heroku.com/changelog-items/2446
https://blog.testdouble.com/posts/2022-08-15-migrating-postgres-extensions-to-the-heroku_ext_schema/
=> Fix Failing Deployments

app/controllers/invitations_controller.rb, app/controllers/space_memberships_controller.rb, app/policies/space_membership_policy.rb, app/views/application/_current_tab.html.erb, app/views/application/_tab.html.erb, app/views/application/_tab_group.html.erb, app/views/space_memberships/_invitations.html.erb, app/views/space_memberships/_space_membership.html.erb, app/views/space_memberships/_space_memberships.html.erb, app/views/space_memberships/index.html.erb, app/views/spaces/edit.html.erb, config/locales/space_memberships/en.yml, config/routes.rb, db/migrate/20220811013601_add_timestamps_to_space_memberships.rb, db/schema.rb, features/harness/Pages.js, features/harness/SpaceEditPage.js, features/harness/SpaceMembershipsIndexPage.js, features/steps/invitation_steps.js, package.json, spec/policies/space_membership_policy_spec.rb, spec/requests/space_memberships_request_spec.rb, spec/requests/spaces/invitations_request_spec.rb, tailwind.config.cjs, yarn.lock
=> Space Memberships: Revoking a Space Membership

app/controllers/application_controller.rb, app/controllers/memberships_controller.rb, app/models/membership.rb, app/policies/membership_policy.rb, app/views/buttons/_remove.html.erb, app/views/furniture_placements/_furniture_placement.html.erb, app/views/invitations/_invitation.html.erb, app/views/layouts/_header.html.erb, app/views/memberships/_invitations.html.erb, app/views/memberships/_membership.html.erb, app/views/memberships/show.html.erb, config/locales/furniture_placement/en.yml, config/routes.rb, spec/models/membership_spec.rb, spec/requests/memberships_request_spec.rb
Co-authored-by: Ana Ulin <anaulin@user.noreply.github.com>
=> Memberships show who the Member has Invited

spec/factories/space.rb, spec/models/space/factory_spec.rb, spec/requests/spaces/invitations_request_spec.rb, spec/requests/spaces/rooms/furniture_placements_spec.rb
Also tweaked the Space factory to stop creating bogus slugs.
=> Fix test flakiness caused by poor path construction

CONTRIBUTING.md
co-authored-by: Ana Ulin <anaulin@users.noreply.github.com>
co-authored-by: Zee Spencer <zspencer@users.noreply.github.com>
=> Add login instructions to CONTRIBUTING.md

config/application.rb
=> Furniture: Locales may be included in Furniture directory

app/controllers/memberships_controller.rb
=> Space: Memberships - Error flash messages were being added wrong

app/furniture/journal/entries/_entry.html.erb, app/furniture/journal/entries_controller.rb, app/javascript/application.js, app/views/buttons/_remove.html.erb, app/views/layouts/_header.html.erb, app/views/rooms/_room.html.erb, package.json, yarn.lock
=> Remove UJS, which we don't use, and which argues with turbo.

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_products_controller.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, config/initializers/money.rb, spec/furniture/marketplace/cart_spec.rb
=> Marketplace: Cart Total Updates as Products are Added and Removed

app/furniture/marketplace/carts/_footer.html.erb
Fixes the horrible layout bug at https://piikup-marketplace.convene.zinc.coop
=> Marketplace: Close that tfoot tag :X

app/furniture/marketplace/marketplace.rb, spec/furniture/marketplace/marketplace_spec.rb
=> Marketplace::Marketplace and it's dependent carts can be destroyed

app/furniture/marketplace/cart.rb, app/furniture/marketplace/product.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/product_spec.rb
=> Marketplace: fill out inverse of and dependent destroys in models

app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/shopper.rb, db/migrate/20221211191259_create_marketplace_checkouts.rb, db/schema.rb, spec/factories/marketplace/checkouts.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/checkout_spec.rb, spec/furniture/marketplace/shopper_spec.rb
For starting checkout flow for https://github.com/zinc-collective/convene/issues/831
=> Marketplace: sprout `Checkout` model

app/furniture/journal.rb, app/furniture/marketplace.rb, app/policies/furniture_placement_policy.rb
It wasn't actually bringing anything to the table, so getting rid of them too.
=> Furniture: Drop Placeable on Marketplace and Journal

app/furniture/journal/breadcrumbs.rb, app/furniture/journal/entries/_entry.html.erb, app/furniture/journal/entry.rb, app/furniture/journal/journal.rb, app/furniture/journal/journals/_journal.html.erb, app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/_marketplace.html.erb, app/furniture/marketplace/product.rb, app/furniture/marketplace/products/_product.html.erb, app/furniture/marketplace/products/index.html.erb, app/furniture/marketplace/products_controller.rb, app/models/furniture_placement.rb, app/models/room.rb, app/models/space.rb, app/models/within_location.rb, spec/furniture/marketplace/cart_products_controller_request_spec.rb
There should be documentation and tests and such, but I smoke tested this pretty thoroughly?
=> Expose a `#location` method for Railsy-Routing

app/furniture/journal/breadcrumbs.rb, app/furniture/journal/entries/_entry.html.erb, app/furniture/journal/entries/index.html.erb, app/furniture/journal/entries_controller.rb, spec/furniture/journal/entries_request_spec.rb
See: https://github.com/zinc-collective/convene/issues/1026
See: https://github.com/zinc-collective/convene/issues/898
Welp, that's what I get for not testing that case! Now there's a test, it's not great... needs some actual assertions; but it exercised the error!
=> Journal: Don't explode on unpublished posts

app/furniture/marketplace/marketplace_policy.rb, spec/furniture/marketplace/marketplace_policy_spec.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
Just a basic "get the route, confirm it renders a template successfully for authenticated user and is a 404 when not"
=> Marketplace: MarketplacesController#edit Spec

spec/furniture/journal/entries_request_spec.rb
=> Make sure we compare HTML-encoded stuff to HTML-encoded stuff, to avoid test flakiness

CONTRIBUTING.md, docs/windows-wsl-dev-setup.md
Based on our experiences with getting my stuff working...
Co-authored-by: Zee <50284+zspencer@users.noreply.github.com>
Co-authored-by: Dalton <daltonrpruitt@user.noreply.github.com>
Co-authored-by: Kelly Hong <KellyAH@user.noreply.github.com>
=> Docs: Add windows dev setup doc

app/furniture/marketplace.rb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/checkouts_controller.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb
(merging into WIP https://github.com/zinc-collective/convene/pull/1031/)
There are a few things that I don't exactly love about this (the weird validation issue, needing the stripe url attributes on checkout), but I think it at least moves things in the right direction.
=> Handle the "failed to initiate checkout" case and add request specs

app/furniture/marketplace/checkout.rb
=> Marketplace: Record Transfer Group in Stripe Checkout Session

app/furniture/marketplace/README.md
continuation of https://github.com/zinc-collective/convene/pull/1064
=> Marketplace - added more mermaid diagrams for vendor connects stripe account 

app/furniture/marketplace/cart.rb, app/furniture/marketplace/carts/_footer.html.erb, app/furniture/marketplace/carts/_total.html.erb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/_form.html.erb, app/furniture/marketplace/marketplaces/edit.html.erb, app/furniture/marketplace/marketplaces_controller.rb, app/models/furniture_placement.rb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
We collect the delivery fee! Wooo!!!
=> Marketplace: Collect Delivery Fee

app/controllers/application_controller.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplaces/_form.html.erb, app/furniture/marketplace/marketplaces_controller.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/order_received_mailer.rb, app/furniture/marketplace/order_received_mailer/notification.html.erb, app/furniture/marketplace/stripe_events_controller.rb, app/mailers/application_mailer.rb, db/migrate/20230223012939_add_delivery_address_to_marketplace_orders.rb, db/migrate/20230223015357_add_contact_email_to_marketplace_orders.rb, db/schema.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart_spec.rb, spec/furniture/marketplace/order_received_mailer_spec.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb, spec/mailers/previews/marketplace/order_received_mailer_preview.rb
=> `Marketplace`: notify `Distributor` and `Vendor` of `Order`

.devcontainer/devcontainer.json
This also formats the JSON file with Prettier, so it follows the rest of our codebases conventions
=> `Dev`: Install Solargraph  on DevContainer

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/stripe_events_controller.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Distributors pay the Stripe Fees, so it takes them out from the $$$ they charge their clients.
=> `Marketplace`: Keep the Stripe Fee in `Distributor`s account

.devcontainer/Dockerfile
Trying to get git (and possibly other bash) completion to work in the devcontainer.
Refer to the [container repo page](https://mcr.microsoft.com/en-us/product/devcontainers/universal/about) and the [actual Dockerfile](https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/Dockerfile) for details on the `universal` container image.
=> `Dev`: Fix bash completion in codespaces

.env.example, app/controllers/application_controller.rb, app/controllers/authenticated_sessions_controller.rb, app/controllers/neighborhoods_controller.rb, app/controllers/spaces_controller.rb, app/models/authentication_method.rb, app/models/neighborhood.rb, app/models/space.rb, app/policies/neighborhood_policy.rb, app/policies/space_policy.rb, app/views/application/_breadcrumbs.html.erb, app/views/authenticated_session_mailer/one_time_password_email.text.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/neighborhoods/show.html.erb, app/views/rooms/_room.html.erb, app/views/spaces/_space.html.erb, app/views/spaces/new.html.erb, config/initializers/action_mailer.rb, config/locales/client/en.yml, config/routes.rb, features/rooms/entering-rooms.feature, spec/factories/space.rb, spec/models/space_spec.rb, spec/requests/spaces_controller_request_spec.rb
* https://github.com/zinc-collective/convene/issues/890
https://user-images.githubusercontent.com/50284/222006383-2dc0f1c8-aaa6-465a-8f8c-49a30dc13f4f.mp4
=> `Neighborhood`: Assign an `Operator` and create a `Space` on first run

app/policies/invitation_policy.rb, spec/policies/invitation_policy_spec.rb
- Introduced in: https://github.com/zinc-collective/convene/pull/1159
- See also:
- https://github.com/zinc-collective/convene/issues/117
- https://github.com/zinc-collective/convene/issues/103
Womp, missed one yesterday!
=> 🐞 `Membership`: `Operator` may create `Invitation`

app/views/spaces/edit.html.erb
- https://github.com/zinc-collective/convene/issues/74
- Extracted from: https://github.com/zinc-collective/convene/pull/1083
=> 🧹 `Space`: Use `Space#location` in forms

app/views/rooms/_form.html.erb
- https://github.com/zinc-collective/convene/issues/74
- Extracted from https://github.com/zinc-collective/convene/pull/1083
=> 🧹 `Room`: Use `Room#location` in form

.github/FUNDING.yml
Instructions on format for this file can be found here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
=> Add FUNDING.yml to display sponsorship link on repo

Gemfile, Gemfile.lock, config/routes.rb
Now we get even *shinier* components! Such shiny! Very browse! Much wow!
I went with the 2.0 beta because I figured it's close to prod.
=> 🛠️🌸 `Components`: Install `Lookbook` for Component Preview

db/migrate/20230310214954_add_contact_phone_ciphertext_to_marketplace_orders.rb, db/schema.rb
- https://github.com/zinc-collective/convene/pull/1201
None of us caught that a migration didn't exist! Womp womp womp
=> `Marketplace`: Add forgotten migration for `Order#contact_phone`

app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/marketplace_policy.rb, app/furniture/marketplace/marketplaces/_form.html.erb, spec/furniture/marketplace/marketplaces_controller_request_spec.rb
=> ✨`Marketplace`: `Distributor` may set `OrderBy`

app/views/application/_money_field.html.erb
A super cool person may want to actually make this a Component, which would be super cool.
=> ✨ `Neighborhood`: Make `money_field` look more like `text_field`

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/marketplaces/_form.html.erb, app/furniture/marketplace/marketplaces/edit.html.erb
=> 🌸 `Marketplace`: Tidy the `edit` form quite a bit

app/furniture/marketplace/tax_rate_policy.rb
=> ✨🔐 `Marketplace`: `Operator` may CRUD `TaxRate`

app/furniture/marketplace/cart.rb, app/furniture/marketplace/cart_product.rb, app/furniture/marketplace/carts/_footer.html.erb, spec/factories/furniture/marketplace.rb
Probably could do a little bit more but eh
=> ✨🥗 `Marketplace`: Hide `Cart`'s `Checkout` button when empty

app/assets/stylesheets/components/form.scss, app/views/application/_password_field.html.erb, app/views/application/_select.html.erb, app/views/utilities/new.html.erb, config/locales/utilities/en.yml
Another small UI tweak, including some tweaks to global form styles (based on a Tailwind UI component)
New Utility form:
Example other form:
New Utility form:
Example other form:
=> 🌸 `Neighborhood`: Tidy up "New Utility" form and tweak global form styles

app/furniture/marketplace/cart.rb, app/furniture/marketplace/order.rb, db/migrate/20230322235647_drop_marketplace_order_contact_email.rb, db/schema.rb
I skipped Step 2 Because I forgot that you're supposed to do the `ignore_columns` *prior* top dropping the columns but eff it.
=> 🔐 `Marketplace`: Step 3 for Encrypting `Order#contact_email`

package.json, yarn.lock
Addresses CVE-2023-28154 , resolves Dependabot alert https://github.com/zinc-collective/convene/security/dependabot/57
=> Update Webpack to 5.76.0 to address CVE-2023-28154

app/furniture/marketplace/cart.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/order.rb, app/furniture/marketplace/order_placed_mailer.rb, app/furniture/marketplace/order_placed_mailer/notification.html.erb, app/furniture/marketplace/stripe_events_controller.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb, spec/mailers/previews/marketplace/order_placed_mailer_preview.rb
~This is WIP, but I need to switch gears to figure out why Stripe is sad.~
TODO:
=> ✨🥔 `Marketplace`: `Shopper` receives `OrderPlaced#notification`

app/furniture/journal/entry.rb, app/furniture/journal/journal.rb, app/furniture/markdown_text_block.rb, app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/delivery_area.rb, app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/order.rb, app/furniture/marketplace/ordered_product.rb, app/furniture/marketplace/product.rb, app/furniture/marketplace/tax_rate.rb, app/models/furniture.rb, app/models/invitation.rb, app/models/room.rb, app/models/rsvp.rb, app/models/space.rb, app/models/within_location.rb, spec/models/within_location_spec.rb
`WithinLocation` is one of the most spooky of our pieces, so I took some time to at least get it covered in some (admittedly obtuse) tests.
=> 🛠️🧹🥗 `Neighborhood`: `WithinLocation` supports routing to singular resources

app/furniture/marketplace/orders/_order.html.erb, app/furniture/marketplace/orders/index.html.erb, app/furniture/marketplace/orders/show.html.erb
- https://github.com/zinc-collective/convene/issues/1331
This will look better when
https://github.com/zinc-collective/convene/pull/1333 gets merged,
I also thought about moving it into an `Order::OrderComponent` so it could be more easily tested...
=> 🌸 `Marketplace`: Tidy up `Order#show` and `Order#index`

.rubocop.yml
Surprised there weren't any errors, but I'll take it!
=> 🛠️ `Neighborhood`: Enforce `rubocop-capybara` and quiet the notice

spec/support/view_component.rb
…_path`
- https://github.com/zinc-collective/convene/pull/1338/files
There are probably other ways to do this, but this seemed like the most straightforward way 🙃
=> 🛠️ `Component`s: `spec`s with `type: :component` support `polymorphic_path`

app/components/application_component.rb, app/policies/application_policy.rb, spec/components/application_component_spec.rb
- https://github.com/zinc-collective/convene/pull/1338
=> 🛠️🥗 `Components`: expose `policy` method

CONTRIBUTING.md
This threw off a contributor recently 🙃
=> 🛠️📝 `Neighborhood`: Don't reference PostgreSQL 12 specifically

app/components/buttons/secondary_component.rb, app/furniture/marketplace/delivery_areas/index.html.erb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, app/furniture/marketplace/management_component.rb
Followup addressing some of the stuff pointed out in comments on https://github.com/zinc-collective/convene/pull/1329
No functional or user-visible changes.
=> 🧹 `Marketplace` `management` component cleanups

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/models/space/agreement.rb, app/policies/space/agreement_policy.rb, app/views/space/agreements/_agreement.html.erb, app/views/space/agreements/show.html.erb, config/breadcrumbs.rb, config/locales/en.yml, spec/requests/space/agreements_controller_request_spec.rb
This isn't the prettiest, but it'll do.
=> ✨🥔 `Agreement`: They can be shown!

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/models/space/agreement.rb, app/policies/space/agreement_policy.rb, app/views/layouts/application.html.erb, app/views/space/agreements/_agreement.html.erb, app/views/space/agreements/show.html.erb, config/breadcrumbs.rb, config/locales/en.yml, spec/requests/space/agreements_controller_request_spec.rb
It just puts them in a little list, but with the p-4 there's a lot of space. But it should be the right size for someone tapping on a phone I hope?
=> ✨🥔 `Agreement`s: Enumerate them in the Footer

app/furniture/marketplace/products/index.html.erb
Fixes https://github.com/zinc-collective/convene/issues/1368
=> 🐞  `Marketplace`: render products with new component

app/controllers/space/agreements_controller.rb, config/locales/agreement/en.yml
Some minor tidying from @anaulin's feedback and missing `'`
=> 🧹 `Agreements`: Add some quotes get rid of weird

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/policies/space/agreement_policy.rb, app/views/spaces/edit.html.erb, config/locales/agreement/en.yml, spec/requests/space/agreements_controller_request_spec.rb
=> 🥗🥔✨`Agreements`: Can be destroyed!

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/policies/space/agreement_policy.rb, config/locales/agreement/en.yml, spec/requests/space/agreements_controller_request_spec.rb
=> 🥗🥔✨ `Agreements`: Tee up the `#update` action

app/controllers/space/agreements_controller.rb, app/lib/space_routes.rb, app/views/space/agreements/_form.html.erb, app/views/space/agreements/edit.html.erb, app/views/space/agreements/new.html.erb, app/views/spaces/edit.html.erb, config/breadcrumbs.rb, config/locales/agreement/en.yml, spec/requests/space/agreements_controller_request_spec.rb
=> 🥗🥔✨ `Agreements`: Can be edited!

app/furniture/marketplace/cart.rb, app/furniture/marketplace/checkout.rb, app/furniture/marketplace/shopper.rb, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/checkouts_controller_request_spec.rb
=> 🥗🥔✨`Marketplace`: Buying `Product`s Pre-populate shopper email

spec/furniture/marketplace/checkout_spec.rb
Quick follow-up to https://github.com/zinc-collective/convene/pull/1434
=> `Marketplace`: Tighten up the `Checkout` spec

spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/products_controller_request_spec.rb
Quick spec on create, probably should add one for `update` soon too
=> 🥗 `Marketplace`: Test `Products#create` with `Product::Photo`

bin/lint-changed, bin/lint-changed-ruby, bin/list-changed-files
I normally just write these every time, but eh maybe someone else will benefit from me putting them in here.
I've also seen a really lovely `make`-a-like written in Rust that the former CTO of NPM seems to like; but I can't remember it's name 🙃.
=> 🛠️ `Neighborhood`: Add some `lint` scripts

app/furniture/marketplace/breadcrumbs.rb, app/furniture/marketplace/locales/en.yml, app/furniture/marketplace/management_component.html.erb, spec/furniture/marketplace/management_component_spec.rb
- https://github.com/zinc-collective/convene/issues/1331
=> 🐞 `Marketplace`: Fix link label to `Seller`'s `Order History`

.github/workflows/test-convene-web.yml, app/furniture/marketplace/cart_product_component.html.erb, app/furniture/marketplace/cart_product_component.rb, app/furniture/marketplace/cart_products_controller.rb, app/furniture/marketplace/carts/_cart.html.erb, app/furniture/marketplace/locales/en.yml, spec/factories/furniture/marketplace.rb, spec/furniture/marketplace/cart_product_component_spec.rb, spec/furniture/marketplace/cart_products_controller_request_spec.rb, spec/support/active_storage.rb, spec/support/view_component.rb
Initially I tried getting the ComponentSpec to kind of act like a system
spec; where I clicked the buttons and then asserted that the page
re-rendered correctly.
Unfortunately, I couldn't get it to work well enough to commit; so I
think I will stab at writing our first system specs in a separate PR.
=> 🥗🧹 `Marketplace`: Extract and test `CartProductComponent`

.devcontainer/startup.bash
Based on https://stackoverflow.com/questions/12399002/how-to-configure-git-bash-command-line-completion
=> 🛠️ `Neighborhood`: Enable bash autocompletion for git in devcontainer

README.md, docs/operator.md
* https://github.com/zinc-collective/convene/issues/1503
Expanding our docs with some basics to add new Spaces.
=> 📝 `Neighborhood`: Document how an `Operator` adds a `Space`

app/furniture/journal/journals/_journal.html.erb
- For https://github.com/zinc-collective/convene/issues/1567
- add new journal entry button to the top of the page
=> `Journal`: Add `New Entry` button to the top of the `Journal` view

config/locales/space/en.yml
- For https://github.com/zinc-collective/convene/issues/1585
A text change requested in https://github.com/zinc-collective/convene/pull/1593#discussion_r1241258286
=> ✨`Space`: tweak entrance gizmo prompt text

app/components/svg_component.rb
- https://github.com/zinc-collective/convene/issues/1511
Extracted from https://github.com/zinc-collective/convene/pull/1562
=> 🌸✨ `Component`: Add `bell` option to `SvgComponent`

CONTRIBUTING.md, app/controllers/application_controller.rb
Random debris left over form our removal of Jitsi video
=> Remove lingering obsolete references to video spaces

app/furniture/marketplace/stripe_accounts_controller.rb, spec/furniture/marketplace/collecting_payments_system_spec.rb
- https://github.com/zinc-collective/convene/issues/1810
Technically I think there is still an issue; but this adds a test!
In particular, I think there may still be a bug where *Operators* can't go to these pages.
I think it's worth merging this as is, so that it fixes the page for April
=> 🥗🐞🔨`Marketplace`: Fix broken Payment Settings page!

app/furniture/marketplace/marketplace.rb, app/furniture/marketplace/order.rb, spec/furniture/marketplace/stripe_events_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/1500
=> 🥗 `Marketplace`: Test `Seller` receives `Order` in their `Square` Point of Sale

app/assets/stylesheets/components/button.scss, app/assets/stylesheets/components/footer.scss, app/assets/stylesheets/components/form.scss, app/assets/stylesheets/components/header.scss, app/components/button_component.rb, app/components/card_component.rb, app/furniture/journal/entry_component.html.erb, app/views/application/_radio_group.html.erb, app/views/buttons/_minus.html.erb, app/views/buttons/_plus.html.erb, app/views/furnitures/_furniture.html.erb, app/views/spaces/_room_card.html.erb, spec/components/button_component_spec.rb, tailwind.config.cjs
- https://github.com/zinc-collective/convene/issues/832
- https://github.com/zinc-collective/convene/issues/621
While I would love to support multiple themes or palettes or something; I don't really have a solid enough idea for how to proceed. Meanwhile; Piikup's branding is orange; so it makes sense for Convene to reflect that.
=> 🌸 `Themes`: Make the primary theme Orange

app/components/alert_component.rb, app/furniture/marketplace/cart/deliveries/_delivery.html.erb
- https://github.com/zinc-collective/convene/pull/1858#issuecomment-1743768286
- https://github.com/zinc-collective/convene/issues/621
Now they're orange! Just like everything else! ORANGE ORANGE ORANGE
=> 🌸 `Themes`: Violet begats violets

app/controllers/application_controller.rb, app/controllers/rooms_controller.rb
Convene's branding isn't what's important, our client and community owners are!
=> 🌸 Remove `Convene` branding from Page titles

app/views/layouts/application.html.erb
- https://github.com/zinc-collective/convene/issues/1520
Well, that's embaressing.
=> 🐞🔨 `Contributors`: Fix link to Github

app/furniture/marketplace/cart/delivery_areas/_form.html.erb, app/furniture/marketplace/cart/delivery_areas_controller.rb, spec/furniture/marketplace/buying_products_system_spec.rb, spec/furniture/marketplace/cart/delivery_areas_controller_request_spec.rb
- https://github.com/zinc-collective/convene/issues/2002
There's probably a smarter way to do this; using `ActionCable` or some such; and maybe we'll need that sometime but for now; it's ok.
=> 🐞🔨 `Marketplace`: `Buying Products`: Updating `DeliveryArea` updates `Cart` `DeliveryFee` 

app/furniture/marketplace/archivable.rb
- https://github.com/zinc-collective/convene/pull/2030#discussion_r1428503777
=> 🧹 `Marketplace`: Use `unarchive` in favor of `retrieve`

app/policies/room_policy.rb, spec/factories/room.rb, spec/requests/rooms_request_spec.rb
- I forgot this in https://github.com/zinc-collective/convene/pull/2055. Which probably means I should write a system spec.
=> 🐞🔨 `Section`: Permit setting the `#description`

spec/requests/rooms_controller_request_spec.rb
https://github.com/zinc-collective/convene/issues/1155
Not really sure if I actually fixed it; but oh well; this is easier to read IMO
=> 🧹 `Sections`: Fix failing spec

app/furniture/marketplace/product.rb, app/models/media.rb, db/migrate/20240120011344_create_media.rb, db/schema.rb, spec/factories/media.rb, spec/models/media_spec.rb
- https://github.com/zinc-collective/convene/issues/2137
While exploring images for [Sections](https://github.com/zinc-collective/convene/pull/2101), it began to make sense for us to create a general purpose _media_ resource to handle file uploads. No time like the present, particularly because this avoids the complicatedness of writing forms or controller handling to manage the nested belongs_to image resource for Sections. Yes, Rails provides mechanisms for that -- `fields_for`, `accepts_nested_attributes`, etc... -- but we know that a _Media_ is a useful domain object on its own for any user experience beyond uploading a single image alongside other Section (currently _Room_)attributes
=> ✨ `Media`: Create `Media` Model and Database Tables

app/furniture/marketplace/menu/product_component.html.erb, app/furniture/marketplace/product/title_component.html.erb, app/furniture/marketplace/product/title_component.rb, app/furniture/marketplace/product_component.html.erb, app/furniture/marketplace/product_policy.rb, app/furniture/marketplace/products/_form.html.erb, db/migrate/20240201014607_marketplace_add_servings_to_products.rb, db/schema.rb, spec/furniture/marketplace/selling_products_system_spec.rb
- https://github.com/zinc-collective/convene/issues/2170
=> ✨🥡 `Marketplace`: Add `Product#servings`

app/furniture/marketplace/product/title_component.html.erb, spec/furniture/marketplace/menu/product_component_spec.rb
- https://github.com/zinc-collective/convene/issues/2170
- https://github.com/zinc-collective/convene/issues/2153
=> 🐞🔨 `Marketplace`: Don't show `Product#servings` on `Menu` when `blank?`

CONTRIBUTING.md
- https://github.com/zinc-collective/convene/issues/1520
Also fixes a broken link to PostgreSQL.
=> 📝 Add `redis` to our set of dependencies

.gitignore, package.json, yarn.lock
If anyone wants to play with it. Example output:
=> Adds webpack bundle analyzer and cli scripts

db/migrate/20240418194554_add_is_group_to_marketplace_tag.rb, db/migrate/20240422172820_add_position_to_marketplace_tag.rb, db/schema.rb
Part of work for https://github.com/zinc-collective/convene/pull/2361. Should be merged first!
=> Adds `is_group` and `position` column to Marketplace Tags

Gemfile, Gemfile.lock, config/environments/development.rb
Tools for lazy programmers! (I mean "lazy" in the exalted sense of not-too-clever.)
=> Adds Bullet gem

Gemfile.lock
@anaulin said that upgrading Bundler and running bundle install should fix it, so that's what I did.
=> For some reason, the Gemfile.lock file keeps changing
